### ISSUE TITLE
 CSRF Token Is Missing

### ISSUE THREAD

**Issue by ravenmullen** [cryptoadvance/specter-desktop#1152]
Hi,

Running v1.2.1 and getting the below message.

Would appreciate any help/insight possible :)

-----

Context is:

- Generated an unsigned transaction with Specter
- Signed the transaction away from this machine using Cobo and Paper Wallet (via Electrum)
- Am uploading a 2/2 signed transaction file (.txn) back to Specter (into 'upload from SD card option' in Unsigned Transactions)

At that point, I am encountering the below error message/pop-up box:

> Server error!
Exception: 400 Bad Request: The CSRF token is missing.

Back to the main page

Details:

Traceback (most recent call last):
  File "flask_wtf/csrf.py", line 256, in protect
  File "flask_wtf/csrf.py", line 91, in validate_csrf
wtforms.validators.ValidationError: The CSRF token is missing.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "flask/app.py", line 1948, in full_dispatch_request
  File "flask/app.py", line 2242, in preprocess_request
  File "flask_wtf/csrf.py", line 224, in csrf_protect
  File "flask_wtf/csrf.py", line 259, in protect
  File "flask_wtf/csrf.py", line 302, in _error_response
flask_wtf.csrf.CSRFError: 400 Bad Request: The CSRF token is missing.

**Comment by ben-kaufman** [comment]
Hi, this is an issue in that version. Please update to a higher version.

**Comment by ravenmullen** [comment]
Thanks for the quick reply Ben! Will try that.

p.s. thanks for all your great work.
