### ISSUE TITLE
Unable to get to sign transaction screen

### ISSUE THREAD

**Issue by bitcoinlizard** [cryptoadvance/specter-desktop#1163]
Important caveat, I am running this on Arch Linux using the native packaging system rather than PIP so it is possible that a dependency is missing although I did check over the requirements.txt document and should have all of the dependencies installed.  Additionally Arch uses Python version 3.9 which should hopefully not cause any issues.

I did confirm that the 2 of 2 multisig wallet was properly created by sending from electrum with the associated seeds.  This is a testnet wallet.  

Here is the error I have when I click open on the "Transactions Awaiting Signing:" screen:
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1499, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1485, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/lib/python3.9/site-packages/flask_login/utils.py", line 269, in decorated_view
    return func(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/cryptoadvance/specter/server_endpoints/wallets.py", line 807, in send_pending
    return render_template(
  File "/usr/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/usr/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/usr/lib/python3.9/site-packages/jinja2/environment.py", line 1289, in render
    self.environment.handle_exception()
  File "/usr/lib/python3.9/site-packages/jinja2/environment.py", line 924, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/usr/lib/python3.9/site-packages/cryptoadvance/specter/templates/wallet/send/sign/wallet_send_sign_psbt.jinja", line 2, in top-level template code
    {% set tab = 'send' %}
  File "/usr/lib/python3.9/site-packages/cryptoadvance/specter/templates/wallet/components/wallet_tab.jinja", line 1, in top-level template code
    {% extends "base.jinja" %}
  File "/usr/lib/python3.9/site-packages/cryptoadvance/specter/templates/base.jinja", line 63, in top-level template code
    {% block main %}
  File "/usr/lib/python3.9/site-packages/cryptoadvance/specter/templates/wallet/components/wallet_tab.jinja", line 12, in block 'main'
    {% block content %}
  File "/usr/lib/python3.9/site-packages/cryptoadvance/specter/templates/wallet/send/sign/wallet_send_sign_psbt.jinja", line 199, in block 'content'
    <button type="button" class="btn signing-column-btn" id="{{ device.alias }}_tx_sign_btn" {{ 'disabled style=background-color:#303c49;' if device.alias in psbt["devices_signed"] else '' }}>
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'devices_signed'
```

**Comment by bitcoinlizard** [comment]
The appimage works fine on the same system so this is related to a missing dependency or something wrong in the build process.  Aside from this single issue everything else seems to work.  I'm able to add a node on another machine, the certificates work, I'm able to add devices and create a wallet and the webcam is working.  I'm just not able to sign a transaction.

**Comment by bitcoinlizard** [comment]
Closing this issue as I have confirmed that it is resolved by this pull request:
https://github.com/cryptoadvance/specter-desktop/pull/1232
