### ISSUE TITLE
Specter app failing after upgrade myNode to 0.2.32

### ISSUE THREAD

**Issue by danilotg** [cryptoadvance/specter-desktop#1166]
Restart and Reinstall from myNode dashboard didn't fix the issue:

```
-- Logs begin at Mon 2021-05-17 09:19:14 CDT, end at Mon 2021-05-17 09:31:02 CDT. --
May 17 09:30:37 myNode systemd[1]: specter.service: Failed with result 'exit-code'.
May 17 09:30:37 myNode systemd[1]: specter.service: Main process exited, code=exited, status=1/FAILURE
May 17 09:30:37 myNode specter[8526]: [Errno 111] Connection refused
May 17 09:30:37 myNode specter[8526]: Initializing HWI...
May 17 09:30:37 myNode specter[8526]: cryptoadvance.specter.specter_error.SpecterError: Unable to parse user JSON.
May 17 09:30:37 myNode specter[8526]:     raise SpecterError("Unable to parse user JSON.")
May 17 09:30:37 myNode specter[8526]:   File "/opt/mynode/specter/env/lib/python3.7/site-packages/cryptoadvance/specter/user.py", line 78, in from_json
May 17 09:30:37 myNode specter[8526]:     self.users = [User.from_json(u, self.specter) for u in users]
May 17 09:30:37 myNode specter[8526]:   File "/opt/mynode/specter/env/lib/python3.7/site-packages/cryptoadvance/specter/user_manager.py", line 41, in 
May 17 09:30:37 myNode specter[8526]:     self.users = [User.from_json(u, self.specter) for u in users]
May 17 09:30:37 myNode specter[8526]:   File "/opt/mynode/specter/env/lib/python3.7/site-packages/cryptoadvance/specter/user_manager.py", line 41, in load_users
May 17 09:30:37 myNode specter[8526]:     self.load_users()
May 17 09:30:37 myNode specter[8526]:   File "/opt/mynode/specter/env/lib/python3.7/site-packages/cryptoadvance/specter/user_manager.py", line 46, in update
May 17 09:30:37 myNode specter[8526]:     self.update()
May 17 09:30:37 myNode specter[8526]:   File "/opt/mynode/specter/env/lib/python3.7/site-packages/cryptoadvance/specter/user_manager.py", line 20, in __init__
May 17 09:30:37 myNode specter[8526]:     self.user_manager = UserManager(self)
May 17 09:30:37 myNode specter[8526]:   File "/opt/mynode/specter/env/lib/python3.7/site-packages/cryptoadvance/specter/specter.py", line 117, in __init__
May 17 09:30:37 myNode specter[8526]:     config=app.config["DEFAULT_SPECTER_CONFIG"],
May 17 09:30:37 myNode specter[8526]:   File "/opt/mynode/specter/env/lib/python3.7/site-packages/cryptoadvance/specter/server.py", line 87, in init_app
May 17 09:30:37 myNode specter[8526]:     init_app(app, hwibridge=hwibridge)
May 17 09:30:37 myNode specter[8526]:   File "/opt/mynode/specter/env/lib/python3.7/site-packages/cryptoadvance/specter/cli/cli_server.py", line 138, in server
May 17 09:30:37 myNode specter[8526]:     return callback(*args, **kwargs)
May 17 09:30:37 myNode specter[8526]:   File "/opt/mynode/specter/env/lib/python3.7/site-packages/click/core.py", line 610, in invoke
May 17 09:30:37 myNode specter[8526]:     return ctx.invoke(self.callback, **ctx.params)
May 17 09:30:37 myNode specter[8526]:   File "/opt/mynode/specter/env/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
May 17 09:30:37 myNode specter[8526]:     return _process_result(sub_ctx.command.invoke(sub_ctx))
May 17 09:30:37 myNode specter[8526]:   File "/opt/mynode/specter/env/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
May 17 09:30:37 myNode specter[8526]:     rv = self.invoke(ctx)
May 17 09:30:37 myNode specter[8526]:   File "/opt/mynode/specter/env/lib/python3.7/site-packages/click/core.py", line 782, in main
May 17 09:30:37 myNode specter[8526]:     return self.main(*args, **kwargs)
May 17 09:30:37 myNode specter[8526]:   File "/opt/mynode/specter/env/lib/python3.7/site-packages/click/core.py", line 829, in __call__
May 17 09:30:37 myNode specter[8526]:     entry_point()
May 17 09:30:37 myNode specter[8526]:   File "/opt/mynode/specter/env/lib/python3.7/site-packages/cryptoadvance/specter/__main__.py", line 19, in 
May 17 09:30:37 myNode specter[8526]:     exec(code, run_globals)
May 17 09:30:37 myNode specter[8526]:   File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
May 17 09:30:37 myNode specter[8526]:     "__main__", mod_spec)
May 17 09:30:37 myNode specter[8526]:   File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
May 17 09:30:37 myNode specter[8526]: Traceback (most recent call last):
May 17 09:30:37 myNode specter[8526]: During handling of the above exception, another exception occurred:
May 17 09:30:37 myNode specter[8526]: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
May 17 09:30:37 myNode specter[8526]:     raise JSONDecodeError("Expecting value", s, err.value) from None
May 17 09:30:37 myNode specter[8526]:   File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
May 17 09:30:37 myNode specter[8526]:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
May 17 09:30:37 myNode specter[8526]:   File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
May 17 09:30:37 myNode specter[8526]:     return _default_decoder.decode(s)
May 17 09:30:37 myNode specter[8526]:   File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
May 17 09:30:37 myNode specter[8526]:     parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
May 17 09:30:37 myNode specter[8526]:   File "/usr/local/lib/python3.7/json/__init__.py", line 296, in load
May 17 09:30:37 myNode specter[8526]:     content = json.load(f)
May 17 09:30:37 myNode specter[8526]:   File "/opt/mynode/specter/env/lib/python3.7/site-packages/cryptoadvance/specter/persistence.py", line 29, in read_json_file
May 17 09:30:37 myNode specter[8526]:     raise e
May 17 09:30:37 myNode specter[8526]:   File "/opt/mynode/specter/env/lib/python3.7/site-packages/cryptoadvance/specter/persistence.py", line 34, in read_json_file
May 17 09:30:37 myNode specter[8526]:     self.data = read_json_file(self.data_file)
May 17 09:30:37 myNode specter[8526]:   File "/opt/mynode/specter/env/lib/python3.7/site-packages/cryptoadvance/specter/managers/genericdata_manager.py", line 27, in load
May 17 09:30:37 myNode specter[8526]:     self.load()
May 17 09:30:37 myNode specter[8526]:   File "/opt/mynode/specter/env/lib/python3.7/site-packages/cryptoadvance/specter/managers/genericdata_manager.py", line 18, in __init__
May 17 09:30:37 myNode specter[8526]:     super().__init__(data_folder)
May 17 09:30:37 myNode specter[8526]:   File "/opt/mynode/specter/env/lib/python3.7/site-packages/cryptoadvance/specter/managers/config_manager.py", line 31, in __init__
May 17 09:30:37 myNode specter[8526]:     self._config_manager = ConfigManager(self.data_folder)
May 17 09:30:37 myNode specter[8526]:   File "/opt/mynode/specter/env/lib/python3.7/site-packages/cryptoadvance/specter/specter.py", line 752, in config_manager
May 17 09:30:37 myNode specter[8526]:     return self.config_manager.data
May 17 09:30:37 myNode specter[8526]:   File "/opt/mynode/specter/env/lib/python3.7/site-packages/cryptoadvance/specter/specter.py", line 265, in config
May 17 09:30:37 myNode specter[8526]:     self.uid = specter.config["uid"]
May 17 09:30:37 myNode specter[8526]:   File "/opt/mynode/specter/env/lib/python3.7/site-packages/cryptoadvance/specter/user.py", line 44, in __init__
May 17 09:30:37 myNode specter[8526]:     is_admin=True,
May 17 09:30:37 myNode specter[8526]:   File "/opt/mynode/specter/env/lib/python3.7/site-packages/cryptoadvance/specter/user.py", line 75, in from_json
May 17 09:30:37 myNode specter[8526]: Traceback (most recent call last):
```

**Comment by k9ert** [comment]
Sorry to hear that. This looks like some data-corruption issue. It should imho not break the startup, though. Which version of specter is that?

It should be possible to solve that via investigating the specter-folder in the mynode-machine. You're using multiple-users on that machine?

**Comment by k9ert** [comment]
Closing due to inactivity. Please reopen if you have more information.

**Comment by Minituff** [comment]
I'm getting this same error when looking at the docker logs on Umbrel Version 0.4.2
