### ISSUE TITLE
Error while loading wallet: dictionary changed size during iteration

### ISSUE THREAD

**Issue by alexbowe** [cryptoadvance/specter-desktop#1172]
After the most recent myNode update (myNode 0.2.33 - but it started happening on 0.2.32 - and Specter v1.3.1), Specter keeps saying `Updating Wallets data...` and has a spinning refresh icon.

After a while it has a popup with this Error:

```
Traceback (most recent call last):
  File "/opt/mynode/specter/env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/mynode/specter/env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/mynode/specter/env/lib/python3.7/site-packages/flask_login/utils.py", line 269, in decorated_view
    return func(*args, **kwargs)
  File "/opt/mynode/specter/env/lib/python3.7/site-packages/cryptoadvance/specter/server_endpoints/wallets.py", line 1157, in txlist
    current_blockheight=app.specter.info["blocks"],
  File "/opt/mynode/specter/env/lib/python3.7/site-packages/cryptoadvance/specter/wallet.py", line 650, in txlist
    self.fetch_transactions()
  File "/opt/mynode/specter/env/lib/python3.7/site-packages/cryptoadvance/specter/wallet.py", line 236, in fetch_transactions
    self._addresses.max_index(change=False),
  File "/opt/mynode/specter/env/lib/python3.7/site-packages/cryptoadvance/specter/addresslist.py", line 184, in max_index
    *[addr.index for addr in self.values() if addr.change == change],
  File "/opt/mynode/specter/env/lib/python3.7/site-packages/cryptoadvance/specter/addresslist.py", line 184, in <listcomp>
    *[addr.index for addr in self.values() if addr.change == change],
RuntimeError: dictionary changed size during iteration
```

This keeps popping up after waiting a while.

When I restart Specter or myNode it has the same spinning icon next to all my wallets, and I can't click on any of them (there's no response). Here is a cropped screenshot of this:

![image](https://user-images.githubusercontent.com/208211/118858077-98e55d00-b88d-11eb-8391-0501ad8e8317.png)

I can delete my wallets folder and try again, but the same thing eventually happens after scanning the transactions (or just UTXOs). I also tried syncing one wallet at a time (in case there was a race condition) to no avail.

Please help, as Specter is unusable in this state.

**Comment by ben-kaufman** [comment]
Hi, sorry for the late response, does this still happen in the latest version?
