### ISSUE TITLE
Uncaught exception when selecting a 'non'-HW device

### ISSUE THREAD

**Issue by Clamenda** [cryptoadvance/specter-desktop#1206]
When selecting a device which does _not_ represent a hardware-wallet I get the following uncaught exception:

[2021-05-31 13:04:11,142] ERROR in controller: Uncaught exception: 'NoneType' object has no attribute 'group'
[2021-05-31 13:04:11,143] ERROR in controller: Traceback (most recent call last):
  File "flask\app.py", line 1950, in full_dispatch_request
  File "flask\app.py", line 1936, in dispatch_request
  File "flask_login\utils.py", line 272, in decorated_view
  File "cryptoadvance\specter\server_endpoints\devices.py", line 452, in device
  File "cryptoadvance\specter\server_endpoints\devices.py", line 447, in sort_accounts
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by ben-kaufman** [comment]
Hi, please try upgrading to v1.4.2 and retry

**Comment by Clamenda** [comment]
Yes, v.1.4.2 fixes this issue, thanks.
