### ISSUE TITLE
Server error! Exception: 'NoneType' object has no attribute 'group'   Back to the main page

### ISSUE THREAD

**Issue by Panzer7** [cryptoadvance/specter-desktop#1208]
Error when checking one device

Details:
Traceback (most recent call last):
  File "flask\app.py", line 1950, in full_dispatch_request
  File "flask\app.py", line 1936, in dispatch_request
  File "flask_login\utils.py", line 269, in decorated_view
  File "cryptoadvance\specter\server_endpoints\devices.py", line 452, in device
  File "cryptoadvance\specter\server_endpoints\devices.py", line 447, in sort_accounts
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by ben-kaufman** [comment]
Hi, please try upgrading to v1.4.2 and retry

**Comment by ben-kaufman** [comment]
Closing, please reopen if still relevant with latest version
