### ISSUE TITLE
Specter server does not start due to "NameError: name 'protocol' is not defined"

### ISSUE THREAD

**Issue by DerM007** [cryptoadvance/specter-desktop#1210]
Trying to run Specter but server does not start. Seems to occur in v1.4.0 trough v1.4.2 but I did not try older versions so don't know about them.

### How to reproduce
`python3 -m cryptoadvance.specter server --daemon --host 0.0.0.0`
gives a NameError.

```
Initializing HWI...
[Errno 111] Connection refused
 INFO in server: Configuration: cryptoadvance.specter.config.ProductionConfig
 INFO in server: Initializing LoginManager
 INFO in server: Initializing Specter
 INFO in wallet_manager: Done updating wallet manager
 DEBUG in log: GETCONF __owningcontrollerprocess (runtime: 0.0006)
 INFO in checker: Checker health Checking every 600 seconds now
 INFO in checker: Checker health started with period 600
 INFO in checker: Checker price Checking every 600 seconds now
 INFO in server: Login disabled
 INFO in server: Initializing Controller ...
 INFO in wallet_manager: Done updating wallet manager
 INFO in checker: Checker executed within 0.036 seconds. This message won't show again until stopped and started.
Starting server in background...
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pi/.local/lib/python3.7/site-packages/cryptoadvance/specter/__main__.py", line 19, in <module>
    entry_point()
  File "/home/pi/.local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/pi/.local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pi/.local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pi/.local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/cryptoadvance/specter/cli/cli_server.py", line 259, in server
    print(" * Running on %s://%s:%d/" % (protocol, host, port))
NameError: name 'protocol' is not defined
INFO in version: version checked. upgrade: False
```

### Possible fix
Using
`nano "/home/pi/.local/lib/python3.7/site-packages/cryptoadvance/specter/cli/cli_server.py"`
I changed line 259 from
` print(" * Running on %s://%s:%d/" % (protocol, host, port))`
to 
` print(" * Running on %s://%s:%d/" % ("http", host, app.config["PORT"]))`
and saved (overwrite) the file.

A new attempt to run is successful.
```
Starting server in background...
 * Running on http://0.0.0.0:25441/
```
Browsing to http://0.0.0.0:25441 shows the Welcome page.

PS: First issue on Github, any feedback would be appreciated.
Edit: typo

**Comment by kdmukai** [comment]
@DerM007 the daemon can be run with `--ssl` so a more complete patch is:
```
        protocol = "http"
        if "ssl_context" in kwargs:
            protocol = "https"
        print(" * Running on %s://%s:%d/" % (protocol, host, app.config["PORT"]))
```

You can edit `cli_server.py` [right from the github UI](https://github.com/cryptoadvance/specter-desktop/blob/master/src/cryptoadvance/specter/cli/cli_server.py). Just click the pencil icon.

Go ahead and make the above change and submit it as a pull request so you can officially be considered a contributor on the project! When you create the pull request include "`fixes #1210`" in the description so github will auto-link it to this issue.
