### ISSUE TITLE
Server error: can't set attribute

### ISSUE THREAD

**Issue by raymonddurk** [cryptoadvance/specter-desktop#1221]
I was creating a multisig that I know has a few UTXOs and when I went to scan the blockchain it gave this

Traceback (most recent call last):
  File "flask\app.py", line 1950, in full_dispatch_request
  File "flask\app.py", line 1936, in dispatch_request
  File "flask_login\utils.py", line 269, in decorated_view
  File "cryptoadvance\specter\server_endpoints\wallets.py", line 959, in settings
AttributeError: can't set attribute

Specter 1.4.2

**Comment by kdmukai** [comment]
That looks like a bug. Trying to set an attribute that is currently a read-only property.

line 959: `app.specter.utxorescanwallet = wallet.alias`

```
    @property
    def utxorescanwallet(self):
        return self.node.utxorescanwallet
```
see: https://github.com/cryptoadvance/specter-desktop/blob/d8094a6261006ea792d8858dbc691da5b7eee7ad/src/cryptoadvance/specter/specter.py#L185

**Comment by raymonddurk** [comment]
Let me know if you need any additional information on the bug
