### ISSUE TITLE
"Invalid hash of the non witness utxo" - When creating Coldcard PSBT transaction

### ISSUE THREAD

**Issue by ArdRay** [cryptoadvance/specter-desktop#1230]
Hey folks,

I am receiving the following error when I am attempting to create a PSBT transaction based on Coldcard hardware wallet. I am running the latest 1.4.3 version, on MacOS 11.4.

<img width="729" alt="server_error" src="https://user-images.githubusercontent.com/4355130/121822227-3de13300-cc9e-11eb-998a-0381740db9ef.png">

Details:

```
Traceback (most recent call last):
  File "flask/app.py", line 1950, in full_dispatch_request
  File "flask/app.py", line 1936, in dispatch_request
  File "flask_login/utils.py", line 269, in decorated_view
  File "cryptoadvance/specter/server_endpoints/wallets.py", line 690, in send_new
  File "flask/templating.py", line 140, in render_template
  File "flask/templating.py", line 120, in _render
  File "jinja2/environment.py", line 1090, in render
  File "jinja2/environment.py", line 832, in handle_exception
  File "jinja2/_compat.py", line 28, in reraise
  File "/var/folders/fq/rfybkrcs4qs7xllgrh75lv1w0000gn/T/_MEIBW9Ohs/templates/wallet/send/sign/wallet_send_sign_psbt.jinja", line 2, in top-level template code
    {% set tab = 'send' %}
  File "/var/folders/fq/rfybkrcs4qs7xllgrh75lv1w0000gn/T/_MEIBW9Ohs/templates/wallet/components/wallet_tab.jinja", line 1, in top-level template code
    {% extends "base.jinja" %}
  File "/var/folders/fq/rfybkrcs4qs7xllgrh75lv1w0000gn/T/_MEIBW9Ohs/templates/base.jinja", line 62, in top-level template code
    {% block main %}
  File "/var/folders/fq/rfybkrcs4qs7xllgrh75lv1w0000gn/T/_MEIBW9Ohs/templates/wallet/components/wallet_tab.jinja", line 12, in block "main"
    {% block content %}
  File "/var/folders/fq/rfybkrcs4qs7xllgrh75lv1w0000gn/T/_MEIBW9Ohs/templates/wallet/send/sign/wallet_send_sign_psbt.jinja", line 10, in block "content"
    {{ sign_tx_method(wallet, device, psbt, specter.info.chain) }}
  File "jinja2/runtime.py", line 679, in _invoke
  File "/var/folders/fq/rfybkrcs4qs7xllgrh75lv1w0000gn/T/_MEIBW9Ohs/templates/includes/overlay/sign_tx_method.jinja", line 10, in template
    {% set device_psbts = device.create_psbts(psbt['base64'], wallet) %}
  File "cryptoadvance/specter/devices/coldcard.py", line 28, in create_psbts
  File "cryptoadvance/specter/wallet.py", line 1541, in fill_psbt
  File "embit/psbt.py", line 501, in from_string
  File "embit/psbt.py", line 485, in from_base64
  File "embit/base.py", line 26, in parse
  File "embit/psbt.py", line 542, in read_from
  File "embit/psbt.py", line 99, in read_from
  File "embit/psbt.py", line 163, in read_value
embit.psbt.PSBTError: Invalid hash of the non witness utxo
```

I have downgraded to 1.4.0 and it is working fine.

**Comment by dxugy** [comment]
Is there any way to downgrade to 1.4.0 via Umbrel?

**Comment by k9ert** [comment]
Seems that this is a bug in the embit-version. It seem to only occur if you spend more than one input. That's also another workaround: only spend one input at a time or downgrade to 1.4.0. It seems that this has been caused by an embit-upgrade which happened from 1.4.2 to 1.4.3. So downgrading to 1.4.2 should also work.

**Comment by stepansnigirev** [comment]
It should be fixed in the latest release. Please check with the newest Specter version

**Comment by ArdRay** [comment]
Verified that the latest version (1.4.5) fixes the problem, thanks all who worked on it.
