### ISSUE TITLE
Load Backup error

### ISSUE THREAD

**Issue by Zimbakin** [cryptoadvance/specter-desktop#1340]
- Mac Big Sur OS 11.5.1
- Specter 1.5.1
- Loading a backup created from Specter 1.4.0 into 1.5.1 not working

```
Exception: 'name'

Back to the main page

Details:
Traceback (most recent call last):
  File "cryptoadvance/specter/server_endpoints/settings.py", line 103, in general
KeyError: 'alias'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "flask/app.py", line 1950, in full_dispatch_request
  File "flask/app.py", line 1936, in dispatch_request
  File "flask_login/utils.py", line 269, in decorated_view
  File "cryptoadvance/specter/server_endpoints/settings.py", line 113, in general
KeyError: 'name'

```

**Comment by k9ert** [comment]
I just tested this with a more or less simplistic wallet and it worked fine. To me, the stacktraces look like the json-files are broken. Please have a look in the wallets-folder. You should find something like this:
```
{"name": "syxfvcd", "alias": "syxfvcd", "description": "Single (Segwit)", "address_type": "bech32", "address": "bcrt1qsqnuk9hulcfta7kj7687favjv66d5e9yy0lr7t", "address_index": 1, "change_address": "bcrt1qt28v03278lmmxllys89acddp2p5y4zds94944n", "change_index": 0, "keypool": 21, "change_keypool": 20, "recv_descriptor": "wpkh([1ef4e492/84h/1h/0h]tpubDC5EUwdy9WWpzqMWKNhVmXdMgMbi4ywxkdysRdNr1MdM4SCfVLbNtsFvzY6WKSuzsaVAitj6FmP6TugPuNT6yKZDLsHrSwMd816TnqX7kuc/0/*)#xp8lv5nr", "change_descriptor": "wpkh([1ef4e492/84h/1h/0h]tpubDC5EUwdy9WWpzqMWKNhVmXdMgMbi4ywxkdysRdNr1MdM4SCfVLbNtsFvzY6WKSuzsaVAitj6FmP6TugPuNT6yKZDLsHrSwMd816TnqX7kuc/1/*)#h4z73prm", "keys": [{"original": "vpub5Y35MNUT8sUR2SnRCU9A9S6z1JDACMTuNnM8WHXvuS7hCwuVuoRAWJGpi66Yo8evGPiecN26oLqx19xf57mqVQjiYb9hbb4QzbNmFfsS9ko", "fingerprint": "1ef4e492", "derivation": "m/84h/1h/0h", "type": "wpkh", "purpose": "#0 Single Sig (Segwit)", "xpub": "tpubDC5EUwdy9WWpzqMWKNhVmXdMgMbi4ywxkdysRdNr1MdM4SCfVLbNtsFvzY6WKSuzsaVAitj6FmP6TugPuNT6yKZDLsHrSwMd816TnqX7kuc"}], "devices": ["mytrezor"], "sigs_required": 1, "blockheight": 0, "labels": {}}
```
Look at the very first two keys:`"name": "syxfvcd", "alias": "syxfvcd",` 
There should be a name and an alias key in all json-files inside the wallets-directory. Can you please check?!

**Comment by k9ert** [comment]
I'm closing this for now. Please don't hesitate to reopen if you need more guidance here.
