### ISSUE TITLE
Flaky tests due to a timeout

### ISSUE THREAD

**Issue by k9ert** [cryptoadvance/specter-desktop#1381]
e.g. here: https://cirrus-ci.com/task/5177460590379008?logs=cypress#L2436
happening with `  1) Spending to a Confidential address from nested` (in this case?!)

```
[   INFO] in       _internal: 127.0.0.1 - - [01/Sep/2021 14:05:46] "GET /wallets/wallet/elm_multi_nested_wallet/history/ HTTP/1.1" 200 -
[   INFO] in       _internal: 127.0.0.1 - - [01/Sep/2021 14:05:47] "POST /wallets/wallet/elm_multi_nested_wallet/txlist HTTP/1.1" 200 -
[   INFO] in       _internal: 127.0.0.1 - - [01/Sep/2021 14:05:47] "POST /wallets/wallet/elm_multi_nested_wallet/txlist HTTP/1.1" 200 -
[   INFO] in       _internal: 127.0.0.1 - - [01/Sep/2021 14:05:47] "POST /wallets/wallet/elm_multi_nested_wallet/txlist HTTP/1.1" 200 -
[   INFO] in       _internal: 127.0.0.1 - - [01/Sep/2021 14:05:47] "POST /wallets/wallet/elm_multi_nested_wallet/txlist HTTP/1.1" 200 -
[   INFO] in       _internal: 127.0.0.1 - - [01/Sep/2021 14:05:47] "POST /wallets/wallet/elm_multi_nested_wallet/txlist HTTP/1.1" 200 -
[   INFO] in       _internal: 127.0.0.1 - - [01/Sep/2021 14:05:47] "GET /wallets/wallet/elm_multi_nested_wallet/send HTTP/1.1" 302 -
[   INFO] in       _internal: 127.0.0.1 - - [01/Sep/2021 14:05:48] "GET /wallets/wallet/elm_multi_nested_wallet/send/pending/ HTTP/1.1" 200 -
[   INFO] in       _internal: 127.0.0.1 - - [01/Sep/2021 14:05:48] "GET /static/styles.css HTTP/1.1" 304 -
02    2) Spending to a Unconfidential address from nested
  3 passing (4m)
  2 failing
  1) Operating with an elements multisig wallet
       Spending to a Confidential address from nested:
     CypressError: Timed out retrying after 4050ms: `cy.click()` failed because this element:
`<a href="/wallets/wallet/elm_multi_nested_wallet/send" class="btn radio   checked" id="btn_send">Send</a>`
is being covered by another element:
`<div class="page_overlay" id="page_overlay" style="display: flex;">...</div>`
Fix this problem, or use {force: true} to disable error checking.
https://on.cypress.io/element-cannot-be-interacted-with
      at $Cy.ensureDescendents (http://localhost:25444/__cypress/runner/cypress_runner.js:141821:26)
      at ensureDescendents (http://localhost:25444/__cypress/runner/cypress_runner.js:130140:8)
      at ensureDescendentsAndScroll (http://localhost:25444/__cypress/runner/cypress_runner.js:130147:14)
      at ensureElIsNotCovered (http://localhost:25444/__cypress/runner/cypress_runner.js:130281:5)
      at runAllChecks (http://localhost:25444/__cypress/runner/cypress_runner.js:130468:52)
      at retryActionability (http://localhost:25444/__cypress/runner/cypress_runner.js:130491:16)
      at tryCatcher (http://localhost:25444/__cypress/runner/cypress_runner.js:10747:23)
      at Function.Promise.attempt.Promise.try (http://localhost:25444/__cypress/runner/cypress_runner.js:8021:29)
      at tryFn (http://localhost:25444/__cypress/runner/cypress_runner.js:146270:21)
      at whenStable (http://localhost:25444/__cypress/runner/cypress_runner.js:146308:12)
      at http://localhost:25444/__cypress/runner/cypress_runner.js:145803:16
      at tryCatcher (http://localhost:25444/__cypress/runner/cypress_runner.js:10747:23)
      at Promise._settlePromiseFromHandler (http://localhost:25444/__cypress/runner/cypress_runner.js:8682:31)
      at Promise._settlePromise (http://localhost:25444/__cypress/runner/cypress_runner.js:8739:18)
      at Promise._settlePromise0 (http://localhost:25444/__cypress/runner/cypress_runner.js:8784:10)
      at Promise._settlePromises (http://localhost:25444/__cypress/runner/cypress_runner.js:8864:18)
  From Your Spec Code:
      at Context.eval (http://localhost:25444/__cypress/tests?p=cypress/integration/spec_elm_multi_segwit_wallet.js:222:7)
  2) Operating with an elements multisig wallet
       Spending to a Unconfidential address from nested:
     AssertionError: Timed out retrying after 4000ms: Expected to find element: `#address_0`, but never found it.
      at Context.eval (http://localhost:25444/__cypress/tests?p=cypress/support/index.js:247:6)
  (Results)
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        5                                                                                │
  │ Passing:      3                                                                                │
  │ Failing:      2                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  2                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     4 minutes, 10 seconds                                                            │
  │ Spec Ran:     spec_elm_multi_segwit_wallet.js                                                  │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
  (Screenshots)
  -  /tmp/cirrus-ci-build/cypress/screenshots/spec_elm_multi_segwit_wallet.js/Operati    (1920x1080)
     ng with an elements multisig wallet -- Spending to a Confidential address from n               
     ested (failed).png                                                                             
  -  /tmp/cirrus-ci-build/cypress/screenshots/spec_elm_multi_segwit_wallet.js/Operati    (1920x1080)
     ng with an elements multisig wallet -- Spending to a Unconfidential address from               
      nested (failed).png                                                                           
  (Video)
  -  Started processing:  Compressing to 32 CRF                                                     
[WARNING] in             rpc: /root/.bitcoin not found
[WARNING] in            node: No rpc was found for <Node name=Bitcoin Core fullpath=/root/.specter-cypress/nodes/default.json>
[  DEBUG] in            node: Updating <Node name=Bitcoin Core fullpath=/root/.specter-cypress/nodes/default.json>.rpc None with None (setter)
[WARNING] in            node: connection of <Node name=Bitcoin Core fullpath=/root/.specter-cypress/nodes/default.json> is None in check_info
[   INFO] in  wallet_manager: Specter seems to be disconnected from Bitcoin Core. Skipping wallets update.
1    Compression progress:  6%
3    Compression progress:  14%
[WARNING] in             rpc: /root/.bitcoin not found
[WARNING] in            node: No rpc was found for <Node name=Bitcoin Core fullpath=/root/.specter-cypress/nodes/default.json>
[  DEBUG] in            node: Updating <Node name=Bitcoin Core fullpath=/root/.specter-cypress/nodes/default.json>.rpc None with None (setter)
[WARNING] in            node: connection of <Node name=Bitcoin Core fullpath=/root/.specter-cypress/nodes/default.json> is None in check_info
[   INFO] in  wallet_manager: Specter seems to be disconnected from Bitcoin Core. Skipping wallets update.
24    Compression progress:  21%
3    Compression progress:  29%
```
The corresponding screenshot:
![image](https://user-images.githubusercontent.com/117085/131813410-d4522fd6-f31a-436d-b518-f349ab18ae22.png)

**Comment by k9ert** [comment]
Another occasion:
https://cirrus-ci.com/task/5294582201057280?logs=cypress#L2904
```
[   INFO] in       _internal: 127.0.0.1 - - [01/Sep/2021 11:30:40] "POST /wallets/wallets_overview/txlist HTTP/1.1" 200 -
    2) Spending to a Confidential address from nested
2[   INFO] in       _internal: 127.0.0.1 - - [01/Sep/2021 11:30:46] "GET / HTTP/1.1" 302 -
[   INFO] in       _internal: 127.0.0.1 - - [01/Sep/2021 11:30:47] "GET /wallets/wallets_overview/ HTTP/1.1" 200 -
[   INFO] in       _internal: 127.0.0.1 - - [01/Sep/2021 11:30:47] "POST /wallets/wallets_overview/txlist HTTP/1.1" 200 -
[   INFO] in       _internal: 127.0.0.1 - - [01/Sep/2021 11:30:47] "POST /wallets/wallets_overview/txlist HTTP/1.1" 200 -
[   INFO] in       _internal: 127.0.0.1 - - [01/Sep/2021 11:30:48] "POST /wallets/wallets_overview/txlist HTTP/1.1" 200 -
4    3) Spending to a Unconfidential address from nested
  2 passing (4m)
  3 failing
  1) Operating with an elements multisig wallet
       Creates an two elements multisig hot wallets (segwit/nested) both 2/3:
      Timed out retrying after 4000ms
      + expected - actual
      at Context.eval (http://localhost:25444/__cypress/tests?p=cypress/support/index.js:240:23)
  2) Operating with an elements multisig wallet
       Spending to a Confidential address from nested:
     AssertionError: Timed out retrying after 4000ms: Expected to find content: 'Elm Multi Nested Wallet' but never did.
      at Context.eval (http://localhost:25444/__cypress/tests?p=cypress/integration/spec_elm_multi_segwit_wallet.js:219:8)
  3) Operating with an elements multisig wallet
       Spending to a Unconfidential address from nested:
     AssertionError: Timed out retrying after 4000ms: Expected to find content: 'Elm Multi Nested Wallet' but never did.
      at Context.eval (http://localhost:25444/__cypress/tests?p=cypress/integration/spec_elm_multi_segwit_wallet.js:252:8)
  (Results)
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        5                                                                                │
  │ Passing:      2                                                                                │
  │ Failing:      3                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  3                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     4 minutes, 13 seconds                                                            │
  │ Spec Ran:     spec_elm_multi_segwit_wallet.js                                                  │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
  (Screenshots)
  -  /tmp/cirrus-ci-build/cypress/screenshots/spec_elm_multi_segwit_wallet.js/Operati    (1920x1080)
     ng with an elements multisig wallet -- Creates an two elements multisig hot wall               
     ets (segwitnested) both 23 (failed).png                                                        
  -  /tmp/cirrus-ci-build/cypress/screenshots/spec_elm_multi_segwit_wallet.js/Operati    (1920x1080)
     ng with an elements multisig wallet -- Spending to a Confidential address from n               
     ested (failed).png                                                                             
  -  /tmp/cirrus-ci-build/cypress/screenshots/spec_elm_multi_segwit_wallet.js/Operati    (1920x1080)
     ng with an elements multisig wallet -- Spending to a Unconfidential address from               
      nested (failed).png                                                                           
  (Video)
  -  Started processing:  Compressing to 32 CRF                                                     
[WARNING] in             rpc: /root/.bitcoin not found
[WARNING] in            node: No rpc was found for <Node name=Bitcoin Core fullpath=/root/.specter-cypress/nodes/default.json>
[  DEBUG] in            node: Updating <Node name=Bitcoin Core fullpath=/root/.specter-cypress/nodes/default.json>.rpc None with None (setter)
[WARNING] in            node: connection of <Node name=Bitcoin Core fullpath=/root/.specter-cypress/nodes/default.json> is None in check_info
[   INFO] in  wallet_manager: Specter seems to be disconnected from Bitcoin Core. Skipping wallets update.
3    Compression progress:  7%
5    Compression progress:  14%
4[WARNING] in             rpc: /root/.bitcoin not found
[WARNING] in            node: No rpc was found for <Node name=Bitcoin Core fullpath=/root/.specter-cypress/nodes/default.json>
[  DEBUG] in            node: Updating <Node name=Bitcoin Core fullpath=/root/.specter-cypress/nodes/default.json>.rpc None with None (setter)
[WARNING] in            node: connection of <Node name=Bitcoin Core fullpath=/root/.specter-cypress/nodes/default.json> is None in check_info
[   INFO] in  wallet_manager: Specter seems to be disconnected from Bitcoin Core. Skipping wallets update.
6    Compression progress:  21%
```

**Comment by k9ert** [comment]
I've reran the tests in #1380 10 times and got a 6:4 ratio:
    Failed https://cirrus-ci.com/task/5177460590379008?logs=cypress#L2444
    suceeded https://cirrus-ci.com/task/6133533262479360
    suceeded https://cirrus-ci.com/task/5458141962829824
    Failed https://cirrus-ci.com/task/6299833616039936
    Success https://cirrus-ci.com/task/5669080758747136
    Success https://cirrus-ci.com/task/5396309667479552
    Failed https://cirrus-ci.com/task/5563920497770496
    Failed https://cirrus-ci.com/task/4922277885116416
    Success https://cirrus-ci.com/task/6412279752163328
    Success https://cirrus-ci.com/task/5621394475057152

**Comment by k9ert** [comment]
I think we've solved it with increasing the resources on the cirrus-build:
https://github.com/cryptoadvance/specter-desktop/pull/1405
