### ISSUE TITLE
socket error when adding wallet and locally hosted bitcoin core

### ISSUE THREAD

**Issue by jblachly** [cryptoadvance/specter-desktop#1483]
This is the same as #1473, but that user did not provide much detail; additionally, I am expanding the scope of the problem report and changing title.

Specter Version: v1.7.1
bitcoind: v22.0.0 

When adding either a watch-only xpub/zpub based wallet, or importing from hardware device, and when using a LAN (not same host) bitcoin core node (reached via mDNS at `bitcoind.local` -- note that the connection does work fine), after adding the wallet, I am met with the error screen:

```
Server error!
Exception: must be real number, not SpecterError


Back to the main page

Details:
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 445, in _make_request
  File "<string>", line 3, in raise_from
  File "urllib3/connectionpool.py", line 440, in _make_request
  File "http/client.py", line 1371, in getresponse
  File "http/client.py", line 319, in begin
  File "http/client.py", line 280, in _read_status
  File "socket.py", line 704, in readinto
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 439, in send
  File "urllib3/connectionpool.py", line 755, in urlopen
  File "urllib3/util/retry.py", line 532, in increment
  File "urllib3/packages/six.py", line 770, in reraise
  File "urllib3/connectionpool.py", line 699, in urlopen
  File "urllib3/connectionpool.py", line 447, in _make_request
  File "urllib3/connectionpool.py", line 336, in _raise_timeout
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='bitcoind.local', port=8332): Read timed out. (read timeout=1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cryptoadvance/specter/rpc.py", line 349, in multi
  File "requests/sessions.py", line 590, in post
  File "requests/sessions.py", line 542, in request
  File "requests/sessions.py", line 655, in send
  File "requests/adapters.py", line 529, in send
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='bitcoind.local', port=8332): Read timed out. (read timeout=1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cryptoadvance/specter/server_endpoints/wallets.py", line 340, in new_wallet
  File "cryptoadvance/specter/rpc.py", line 411, in fn
  File "cryptoadvance/specter/rpc.py", line 366, in multi
cryptoadvance.specter.specter_error.SpecterError: Timeout after 1 secs while BitcoinRPC call(wallet/specter/lnx          ). Check the logs for more details.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "flask/app.py", line 1950, in full_dispatch_request
  File "flask/app.py", line 1936, in dispatch_request
  File "flask_login/utils.py", line 269, in decorated_view
  File "cryptoadvance/specter/server_endpoints/wallets.py", line 346, in new_wallet
TypeError: must be real number, not SpecterError
```

However, do note that after proceeding past this (Via the "Back to the main page" button) , everything seems to be working fine, and the node is scanning the blocks for the newly added wallet.

Something important to test, but that I need to wait to do until all these are done scanning, is to add another wallet but do NOT check the option to check for transactions/UTXOs to see if the connection error still manifests.

I wonder if part of the code is assuming I am running a node on localhost?

**Comment by jblachly** [comment]
Yes, I can confirm the error does NOT happen (and instead, you are presented with the option to download a PDF backup of the wallet) if you do not scan for transaction history at time wallet is added.

**Comment by kdmukai** [comment]
Changing the timeout doesn't help. That rpc call just doesn't seem to return.

`None` means wait forever until the rpc call returns:
```
wallet.rpc.rescanblockchain(startblock, timeout=None)
```

Trying it now and it's just waiting and waiting (hopefully `requests` has some final timeout where it'll eventually give up?).

I'll see if I can add something like a `no_wait` option on that call.
