### ISSUE TITLE
Unable to delete wallet on Spectre Desktop

### ISSUE THREAD

**Issue by swedishfrenchpress** [cryptoadvance/specter-desktop#1504]
When trying to delete a wallet on Spectre desktop I am getting the following error.

[Errno 30] Read-only file system: 'wallet.dat'

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.8/site-packages/flask_login/utils.py", line 269, in decorated_view
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/cryptoadvance/specter/server_endpoints/wallets.py", line 815, in settings
    app.specter.wallet_manager.delete_wallet(
  File "/usr/local/lib/python3.8/site-packages/cryptoadvance/specter/managers/wallet_manager.py", line 341, in delete_wallet
    shutil.rmtree(path)
  File "/usr/local/lib/python3.8/shutil.py", line 718, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/local/lib/python3.8/shutil.py", line 675, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/local/lib/python3.8/shutil.py", line 673, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
OSError: [Errno 30] Read-only file system: 'wallet.dat'

**Comment by k9ert** [comment]
This is an Operating-level issue. You probably have bigger problems with your Computer. "Read-only-filesystem" says it all. A reboot did not help, right?!

**Comment by swedishfrenchpress** [comment]
I’ve done a sudo reboot many times on my Pi Node that is hosting specter.
Is the specter app installed on my node via Citadel not allowing me as a
user the permission to delete a wallet?

**Comment by k9ert** [comment]
Do you use a umbrel or raspiblitz or mynode or something custom? This is more a question for these kinds of software rather then specter. As said: This is an Operating-level-issue and i don't think that "citadel" (what is that, i don't know "citadel") is able to give granular permissions like that.
Check your boot-logs when you booting up the machine (`dmesg`). Maybe you'll find a root-cause there why you get a read-only filesystem.

**Comment by AaronDewes** [comment]
> what is that, i don't know "citadel"

It's my FOSS fork of Umbrel, GitHub.com/runcitadel. It seems like a bug there, I'll fix it soon.

**Comment by swedishfrenchpress** [comment]
This has been resolved by @AaronDewes.
