### ISSUE TITLE
Importing Multisignature transaction from Electrum Fails in Specter

### ISSUE THREAD

**Issue by relativisticelectron** [cryptoadvance/specter-desktop#1544]
Using a 2/2 testnet multisig electrum wallet: I created a PSBT with 
a) electrum 4.1.5 (partially signed)
b) specter   (unsigned)

Importing the electrum PSBT fails ([error message.txt](https://github.com/cryptoadvance/specter-desktop/files/7964754/error.message.txt)), while (re) importing the specter PSBT succeeds. 

After decoding the PSBTs I find:
- the specter PSBT has `"inputs": [    {      "witness_utxo"`, which is missing in the electrum PSBT

Is this a bug in specter or is the electrum PSBT missing a critical piece?  

This issue is a possible duplicate of: https://github.com/cryptoadvance/specter-desktop/issues/104

**Comment by pleblira** [comment]
I think I got a similar error here while importing a partially signed transaction from Electrum - 3o2 signature already signed by one wallet.

`Traceback (most recent call last):
  File "flask/app.py", line 1950, in full_dispatch_request
  File "flask/app.py", line 1936, in dispatch_request
  File "flask_login/utils.py", line 269, in decorated_view
  File "cryptoadvance/specter/server_endpoints/wallets.py", line 686, in send_pending
  File "flask/templating.py", line 137, in render_template
  File "flask/templating.py", line 120, in _render
  File "jinja2/environment.py", line 1090, in render
  File "jinja2/environment.py", line 832, in handle_exception
  File "jinja2/_compat.py", line 28, in reraise
  File "/var/folders/cl/nxrkb1hx6yj99pgk8c3flyf40000gn/T/_MEIcLmxcD/templates/wallet/send/pending/wallet_sendpending.jinja", line 2, in top-level template code
    {% set tab = 'send' %}
  File "/var/folders/cl/nxrkb1hx6yj99pgk8c3flyf40000gn/T/_MEIcLmxcD/templates/wallet/components/wallet_tab.jinja", line 1, in top-level template code
    {% extends "base.jinja" %}
  File "/var/folders/cl/nxrkb1hx6yj99pgk8c3flyf40000gn/T/_MEIcLmxcD/templates/base.jinja", line 98, in top-level template code
    {% block main %}
  File "/var/folders/cl/nxrkb1hx6yj99pgk8c3flyf40000gn/T/_MEIcLmxcD/templates/wallet/components/wallet_tab.jinja", line 12, in block "main"
    {% block content %}
  File "/var/folders/cl/nxrkb1hx6yj99pgk8c3flyf40000gn/T/_MEIcLmxcD/templates/wallet/send/pending/wallet_sendpending.jinja", line 9, in block "content"
    {{ pending_psbt_table(pending_psbts, wallet_alias, wallet, specter) }}
  File "jinja2/runtime.py", line 679, in _invoke
  File "/var/folders/cl/nxrkb1hx6yj99pgk8c3flyf40000gn/T/_MEIcLmxcD/templates/wallet/send/pending/components/pending_psbt_table.jinja", line 22, in template
    pending_psbt_item(
  File "jinja2/runtime.py", line 679, in _invoke
  File "/var/folders/cl/nxrkb1hx6yj99pgk8c3flyf40000gn/T/_MEIcLmxcD/templates/wallet/send/pending/components/pending_psbt_item.jinja", line 41, in template
    <input type="hidden" name="pending_psbt" value='{{ pending_psbt|tojson|safe }}'>
  File "flask/json/__init__.py", line 376, in tojson_filter
  File "flask/json/__init__.py", line 290, in htmlsafe_dumps
  File "flask/json/__init__.py", line 211, in dumps
  File "json/__init__.py", line 234, in dumps
  File "json/encoder.py", line 199, in encode
  File "json/encoder.py", line 257, in iterencode
  File "flask/json/__init__.py", line 100, in default
  File "json/encoder.py", line 179, in default
TypeError: Object of type SpecterTx is not JSON serializable
`

**Comment by relativisticelectron** [comment]
Do I understand https://bips.dev/174/  correctly, that PSBT_IN_WITNESS_UTXO  should be present, and Electrum doesn't follow BIP174?

**Comment by relativisticelectron** [comment]
Somehow the error occurs here:  https://github.com/cryptoadvance/specter-desktop/blob/eaeac1f20482dbb25ef6867a1a5414df9fae766a/src/cryptoadvance/specter/persistence.py#L77    and might be related to the recv_descriptor somehow breaking the json format....  investigating.

**Comment by relativisticelectron** [comment]
Ok. I made the changes on my branch https://github.com/relativisticelectron/specter-desktop/blob/9d3a39461360e2238c654cd9a353cdeb99e44a64/src/cryptoadvance/specter/util/psbt.py#L201  and the elctrum psbt import works fine.

**Comment by relativisticelectron** [comment]
Created PR

**Comment by moneymanolis** [comment]
> I am however confused. If https://github.com/relativisticelectron/specter-desktop/blob/9d3a39461360e2238c654cd9a353cdeb99e44a64/src/cryptoadvance/specter/util/psbt.py#L201 really was an error it should cause problems all over the place..... or not? How could this NOT cause problems in other situations?

Very good point and thanks for the fix. Should be relevant to other PSBT settings as well that use the `Non-Witness UTXO` field.
