### ISSUE TITLE
Feature missing: Import of raw transaction not supported

### ISSUE THREAD

**Issue by relativisticelectron** [cryptoadvance/specter-desktop#1577]
It seems that import of fully signed raw (hex) transactions is not supported.

Steps to reproduce:
- Create a fully signed tx with another wallet software (do not broadcast)
- In specter go to Send --> Import --> Paste the hex of the raw tx in the field

```
[2022-02-11 20:58:58,637] ERROR in specter_error: Unexpected error:
[2022-02-11 20:58:58,638] ERROR in specter_error: ----START-TRACEBACK-----------------------------------------------------------------
[2022-02-11 20:58:58,638] ERROR in specter_error: Incorrect padding
Traceback (most recent call last):
  File "/home/<user>/programs/anaconda3/lib/python3.9/site-packages/cryptoadvance/specter/server_endpoints/wallets.py", line 683, in import_psbt
    psbt = wallet.importpsbt(b64psbt)
  File "/home/<user>/programs/anaconda3/lib/python3.9/site-packages/cryptoadvance/specter/wallet.py", line 2008, in importpsbt
    psbt = self.PSBTCls(
  File "/home/<user>/programs/anaconda3/lib/python3.9/site-packages/cryptoadvance/specter/util/psbt.py", line 242, in __init__
    psbt = self.PSBTCls.from_string(psbt)
  File "/home/<user>/programs/anaconda3/lib/python3.9/site-packages/embit/psbt.py", line 578, in from_string
    return cls.from_base64(s, compress=compress)
  File "/home/<user>/programs/anaconda3/lib/python3.9/site-packages/embit/psbt.py", line 561, in from_base64
    raw = a2b_base64(b64)
binascii.Error: Incorrect padding
[2022-02-11 20:58:58,639] ERROR in specter_error: ----END---TRACEBACK-----------------------------------------------------------------
```

I could not find a decoderawtransaction analog  in https://github.com/diybitcoinhardware/embit.  But it seems the functionality is in https://github.com/cryptoadvance/specter-desktop/blob/6ab2bafbdb2a6b0d49061ed4e8c3f3fffa5fd725/src/cryptoadvance/specter/util/tx.py#L44

One should be able to reconstruct the full psbt using decoderawtransaction...

**Comment by moneymanolis** [comment]
According to @stepansnigirev, you could do `converttopsbt` and `fillpsbt` from Bitcoin Core to do that. This functionality could perhaps also be used for the reverse (PBST to raw transaction) and then enable `testmempoolaccept` that @relativisticelectron was mentioning (https://github.com/cryptoadvance/specter-desktop/issues/1572#issuecomment-1040077499).

**Comment by stepansnigirev** [comment]
> According to @stepansnigirev, you could do `converttopsbt` and `fillpsbt` from Bitcoin Core to do that.

I think we should do it in Specter when we get a raw hex transaction in the import psbt field

**Comment by moneymanolis** [comment]
@relativisticelectron do you want to give it a shot? I can only get to it at a later stage.

**Comment by relativisticelectron** [comment]
Yes, I can give it a shot.

**Comment by relativisticelectron** [comment]
> According to @stepansnigirev, you could do `converttopsbt` and `fillpsbt` from Bitcoin Core to do that.

`converttopsbt`  gives the error  `Inputs must not have scriptSigs and scriptWitnesses (code -22)`


> I think we should do it in Specter when we get a raw hex transaction in the import psbt field

Do you mean, without calling rpc?

**Comment by relativisticelectron** [comment]
> Inputs must not have scriptSigs and scriptWitnesses (code -22)

ok, I can simply call converttopsbt  hex  true, and it works.

**Comment by relativisticelectron** [comment]
Signatures added https://github.com/relativisticelectron/specter-desktop/tree/import_raw using the hwi lib.

**Comment by relativisticelectron** [comment]
Working! https://github.com/relativisticelectron/specter-desktop/tree/import_raw

**Comment by relativisticelectron** [comment]
Created a draft PR  (working for witness inputs)
