### ISSUE TITLE
Unclear Network Error Message when trying to use Jade with Testnet/Regtest

### ISSUE THREAD

**Issue by wielandgmeiner** [cryptoadvance/specter-desktop#1584]
When trying to use Jade HWW with Specter on Testnet (Regtest), after going throug the initialization steps in the blockstream green app, when trying to add it as a new device to specter, I get the following errors:
```
File "cryptoadvance/specter/devices/hwi/jade.py", line 69, in func
  File "cryptoadvance/specter/devices/hwi/jade.py", line 175, in get_pubkey_at_path
  File "cryptoadvance/specter/devices/hwi/jadepy/jade.py", line 268, in get_xpub
  File "cryptoadvance/specter/devices/hwi/jadepy/jade.py", line 154, in _jadeRpc
  File "cryptoadvance/specter/devices/hwi/jadepy/jade.py", line 138, in _get_result_or_raise_error
cryptoadvance.specter.devices.hwi.jadepy.jade_error.JadeError: JadeError: -32003 - Network type inconsistent with prior usage (Data: None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cryptoadvance/specter/util/json_rpc.py", line 35, in jsonrpc
  File "cryptoadvance/specter/helpers.py", line 81, in wrapper_fn
  File "cryptoadvance/specter/hwi_rpc.py", line 255, in extract_xpub
  File "hwilib/hwwclient.py", line 69, in get_master_fingerprint
  File "cryptoadvance/specter/devices/hwi/jade.py", line 82, in func
hwilib.errors.DeviceConnectionError: Network/chain selection error
SPECTERD: INFO in _internal: 127.0.0.1 - - [10/Feb/2022 16:02:44] "POST /hwi/api/ HTTP/1.1" 200 -
```

**Comment by k9ert** [comment]
This is a limitation of jade: If you want to switch from testnet to mainnet or vide versa, you need to reset the whole device.
This should get a better error-message, though. 
Thanks for reporting!

**Comment by wfjvdham** [comment]
I think this one can be closed because it has a custom error message now: https://github.com/cryptoadvance/specter-desktop/blob/a0523732aa4f7255a835a34f56d6c9afb859b72d/src/cryptoadvance/specter/devices/hwi/jade.py#L81-L82
