### ISSUE TITLE
Specter Desktop encounter an error: specterd exited with code 1.

### ISSUE THREAD

**Issue by n-e-t-d-i-v-e-r** [cryptoadvance/specter-desktop#1630]
System: MacOS 10.14.6, Mojave
Specter 1.8.1

hi there

tried to start up specter desktop on my macOS but i’ll get following error:

`2022-03-15T15:53:11.591Z [info] : Framework Ready! Starting tray Icon ...
2022-03-15T15:53:11.659Z [info] : Framework Ready! Initializing Main-Window, populating Menu ...
2022-03-15T15:53:11.740Z [info] : Creating specterd-binaries folder
2022-03-15T15:53:11.741Z [info] : Updating /Users/eBusiness_RI/.specter/app_settings.json : {"mode":"specterd","specterURL":"http://localhost:25441","tor":false,"proxyURL":"socks5://127.0.0.1:9050","specterdVersion":"v1.8.1","specterdHash":"5a22b6df72e1d5c3c3d29ece21467c0c4d5a2aa696d7ed4b07b9aa7c4268e72b","specterdCLIArgs":"","versionInitialized":false}
2022-03-15T15:53:11.811Z [info] : Using version 
2022-03-15T15:53:11.811Z [info] : https://github.com/cryptoadvance/specter-desktop/releases/download/v1.8.1/specterd-v1.8.1-osx.zip
2022-03-15T15:53:13.289Z [info] : content-type:
2022-03-15T15:53:13.289Z [info] : content-length:
2022-03-15T15:53:33.286Z [info] : Starting specterd /Users/eBusiness_RI/.specter/specterd-binaries/specterd server,--no-filelog
2022-03-15T15:53:35.729Z [info] : stderr-Traceback (most recent call last):
  File "specterd.py", line 1, in <module>

2022-03-15T15:53:35.730Z [info] : stderr-  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "cryptoadvance/specter/cli/__init__.py", line 4, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "cryptoadvance/specter/cli/cli_server.py", line 11, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "stem/__init__.py", line 1032, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "stem/util/connection.py", line 69, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "stem/util/system.py", line 68, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "ctypes/__init__.py", line 8, in <module>
ImportError: dlopen(/var/folders/w1/g0vp8vpn4vjg2y773nqj0ytr0000gp/T/_MEIiRi0hw/lib-dynload/_ctypes.cpython-39-darwin.so, 2): Symbol not found: _ffi_closure_alloc
  Referenced from: /var/folders/w1/g0vp8vpn4vjg2y773nqj0ytr0000gp/T/_MEIiRi0hw/lib-dynload/_ctypes.cpython-39-darwin.so (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libffi.dylib
 in /var/folders/w1/g0vp8vpn4vjg2y773nqj0ytr0000gp/T/_MEIiRi0hw/lib-dynload/_ctypes.cpython-39-darwin.so
[92389] Failed to execute script 'specterd' due to unhandled exception!

2022-03-15T15:53:35.929Z [error] : specterd exited with code 1
2022-03-15T15:53:35.930Z [info] : child process exited with code 1
2022-03-15T15:57:07.044Z [info] : Framework Ready! Starting tray Icon ...
2022-03-15T15:57:07.073Z [info] : Framework Ready! Initializing Main-Window, populating Menu ...
2022-03-15T15:57:08.047Z [info] : Starting specterd /Users/eBusiness_RI/.specter/specterd-binaries/specterd server,--no-filelog
2022-03-15T15:57:10.377Z [info] : stderr-Traceback (most recent call last):
  File "specterd.py", line 1, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "cryptoadvance/specter/cli/__init__.py", line 4, in <module>

2022-03-15T15:57:10.377Z [info] : stderr-  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "cryptoadvance/specter/cli/cli_server.py", line 11, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "stem/__init__.py", line 1032, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "stem/util/connection.py", line 69, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "stem/util/system.py", line 68, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "ctypes/__init__.py", line 8, in <module>
ImportError: dlopen(/var/folders/w1/g0vp8vpn4vjg2y773nqj0ytr0000gp/T/_MEI5SHYr1/lib-dynload/_ctypes.cpython-39-darwin.so, 2): Symbol not found: _ffi_closure_alloc
  Referenced from: /var/folders/w1/g0vp8vpn4vjg2y773nqj0ytr0000gp/T/_MEI5SHYr1/lib-dynload/_ctypes.cpython-39-darwin.so (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libffi.dylib
 in /var/folders/w1/g0vp8vpn4vjg2y773nqj0ytr0000gp/T/_MEI5SHYr1/lib-dynload/_ctypes.cpython-39-darwin.so
[92481] Failed to execute script 'specterd' due to unhandled exception!

2022-03-15T15:57:10.562Z [error] : specterd exited with code 1
2022-03-15T15:57:10.563Z [info] : child process exited with code 1
2022-03-16T08:01:25.970Z [info] : Framework Ready! Starting tray Icon ...
2022-03-16T08:01:26.013Z [info] : Framework Ready! Initializing Main-Window, populating Menu ...
2022-03-16T08:01:27.435Z [info] : Starting specterd /Users/eBusiness_RI/.specter/specterd-binaries/specterd server,--no-filelog
2022-03-16T08:01:30.249Z [info] : stderr-Traceback (most recent call last):
  File "specterd.py", line 1, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module

2022-03-16T08:01:30.250Z [info] : stderr-  File "cryptoadvance/specter/cli/__init__.py", line 4, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "cryptoadvance/specter/cli/cli_server.py", line 11, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "stem/__init__.py", line 1032, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "stem/util/connection.py", line 69, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "stem/util/system.py", line 68, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "ctypes/__init__.py", line 8, in <module>
ImportError: dlopen(/var/folders/w1/g0vp8vpn4vjg2y773nqj0ytr0000gp/T/_MEIXqFl1d/lib-dynload/_ctypes.cpython-39-darwin.so, 2): Symbol not found: _ffi_closure_alloc
  Referenced from: /var/folders/w1/g0vp8vpn4vjg2y773nqj0ytr0000gp/T/_MEIXqFl1d/lib-dynload/_ctypes.cpython-39-darwin.so (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libffi.dylib
 in /var/folders/w1/g0vp8vpn4vjg2y773nqj0ytr0000gp/T/_MEIXqFl1d/lib-dynload/_ctypes.cpython-39-darwin.so
[8928] Failed to execute script 'specterd' due to unhandled exception!

2022-03-16T08:01:30.505Z [error] : specterd exited with code 1
2022-03-16T08:01:30.506Z [info] : child process exited with code 1
2022-03-16T14:54:07.457Z [info] : Framework Ready! Starting tray Icon ...
2022-03-16T14:54:07.498Z [info] : Framework Ready! Initializing Main-Window, populating Menu ...
2022-03-16T14:54:08.854Z [info] : Starting specterd /Users/eBusiness_RI/.specter/specterd-binaries/specterd server,--no-filelog
2022-03-16T14:54:11.920Z [info] : stderr-Traceback (most recent call last):
  File "specterd.py", line 1, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module

2022-03-16T14:54:11.920Z [info] : stderr-  File "cryptoadvance/specter/cli/__init__.py", line 4, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "cryptoadvance/specter/cli/cli_server.py", line 11, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "stem/__init__.py", line 1032, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "stem/util/connection.py", line 69, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "stem/util/system.py", line 68, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "ctypes/__init__.py", line 8, in <module>
ImportError: dlopen(/var/folders/w1/g0vp8vpn4vjg2y773nqj0ytr0000gp/T/_MEIBVi61k/lib-dynload/_ctypes.cpython-39-darwin.so, 2): Symbol not found: _ffi_closure_alloc
  Referenced from: /var/folders/w1/g0vp8vpn4vjg2y773nqj0ytr0000gp/T/_MEIBVi61k/lib-dynload/_ctypes.cpython-39-darwin.so (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libffi.dylib
 in /var/folders/w1/g0vp8vpn4vjg2y773nqj0ytr0000gp/T/_MEIBVi61k/lib-dynload/_ctypes.cpython-39-darwin.so
[17079] Failed to execute script 'specterd' due to unhandled exception!

2022-03-16T14:54:12.164Z [error] : specterd exited with code 1
2022-03-16T14:54:12.165Z [info] : child process exited with code 1
`
Any idea what’s going wrong? Maybe the actual version of specter isn’t compatible with old MacOS Mojave?

**Comment by moneymanolis** [comment]
From the release notes:
Note on macOS: The current build supports only macOS Catalina (10.15) or higher. If you'd like to run Specter on an older macOS version, you can [install Specter from Pip](https://github.com/cryptoadvance/specter-desktop#installing-specter-from-pip).
