### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Shampow8** [cryptoadvance/specter-desktop#1680]
Traceback (most recent call last):
File "/home/specter/.env/lib/python3.7/site-packages/flask/app.py", liine 2447, in wsgi_app response = self.full_dispatch_request()
File = "/home/specter/.env/lib/python3.7/site-packages/flash/app.py", line 1953, in full full_dispatch_requestreturn self.finalize_request(rv)
File "/home/specter/.env/libpython3.7/size-packages/flash/app.py", line 1968, in finalize_request
response = self.make_response(rv)
File "/home/specter/.env/lib/python3.7/site-packages/flask/app.py", line 2131, in make_response
" {rv.class.__name}."format(rv=rv_
TypeError: The view function did not return a valid response. The return type must be a string, dict, tup

**Comment by k9ert** [comment]
There is not enough context within that error-message. It looks incomplete to me. Apart from that: which version, which deployment, which OS and what did you do when this came up and did you change anything recently?

**Comment by Shampow8** [comment]
@k9ert
[2022-04-30 03:10:44,611] INFO in version: version checked. upgrade: False
[2022-04-30 03:19:11,145] INFO in wallet: Didn't get transactions on change address 3Ap3q9ajpZ9TJTvdC2UAZ3VjryXFH7qrmE. Refilling keypool.
[2022-04-30 03:29:11,755] INFO in wallet: Didn't get transactions on change address 3Ap3q9ajpZ9TJTvdC2UAZ3VjryXFH7qrmE. Refilling keypool.
[2022-04-30 03:39:12,688] INFO in wallet: Didn't get transactions on change address 3Ap3q9ajpZ9TJTvdC2UAZ3VjryXFH7qrmE. Refilling keypool.
[2022-04-30 03:49:13,049] INFO in wallet: Didn't get transactions on change address 3Ap3q9ajpZ9TJTvdC2UAZ3VjryXFH7qrmE. Refilling keypool.
[2022-04-30 03:59:13,692] INFO in wallet: Didn't get transactions on change address 3Ap3q9ajpZ9TJTvdC2UAZ3VjryXFH7qrmE. Refilling keypool.
[2022-04-30 04:09:14,578] INFO in wallet: Didn't get transactions on change address 3Ap3q9ajpZ9TJTvdC2UAZ3VjryXFH7qrmE. Refilling keypool.
[2022-04-30 04:12:44,556] ERROR in version: SOCKSHTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /pypi/cryptoadvance.specter/json (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f7c489b38>: Failed to establish a new connection: 0x06: TTL expired'))
Traceback (most recent call last):
  File "/home/specter/.env/lib/python3.7/site-packages/socks.py", line 809, in connect
    negotiate(self, dest_addr, dest_port)
  File "/home/specter/.env/lib/python3.7/site-packages/socks.py", line 444, in _negotiate_SOCKS5
    self, CONNECT, dest_addr)
  File "/home/specter/.env/lib/python3.7/site-packages/socks.py", line 533, in _SOCKS5_request
    raise SOCKS5Error("{:#04x}: {}".format(status, error))
socks.SOCKS5Error: 0x06: TTL expired

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/specter/.env/lib/python3.7/site-packages/urllib3/contrib/socks.py", line 105, in _new_conn
    **extra_kw
  File "/home/specter/.env/lib/python3.7/site-packages/socks.py", line 209, in create_connection
    raise err
  File "/home/specter/.env/lib/python3.7/site-packages/socks.py", line 199, in create_connection
    sock.connect((remote_host, remote_port))
  File "/home/specter/.env/lib/python3.7/site-packages/socks.py", line 47, in wrapper
    return function(*args, **kwargs)
  File "/home/specter/.env/lib/python3.7/site-packages/socks.py", line 814, in connect
    raise GeneralProxyError("Socket error", error)
socks.GeneralProxyError: Socket error: 0x06: TTL expired

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/specter/.env/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/home/specter/.env/lib/python3.7/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/home/specter/.env/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/home/specter/.env/lib/python3.7/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/home/specter/.env/lib/python3.7/site-packages/urllib3/contrib/socks.py", line 128, in _new_conn
    self, "Failed to establish a new connection: %s" % error
urllib3.exceptions.NewConnectionError: <urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f7c489b38>: Failed to establish a new connection: 0x06: TTL expired
@k9ert 
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/specter/.env/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/specter/.env/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/specter/.env/lib/python3.7/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: SOCKSHTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /pypi/cryptoadvance.specter/json (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f7c489b38>: Failed to establish a new connection: 0x06: TTL expired'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/specter/.env/lib/python3.7/site-packages/cryptoadvance/specter/util/version.py", line 96, in _get_pip_version
    requests_session.get(f"https://pypi.org/pypi/{self.name}/json")
  File "/home/specter/.env/lib/python3.7/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/home/specter/.env/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/specter/.env/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/specter/.env/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: SOCKSHTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /pypi/cryptoadvance.specter/json (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f7c489b38>: Failed to establish a new connection: 0x06: TTL expired'))

**Comment by Shampow8** [comment]
The error occurred on version 1.9.2 first and then it also occurred on 1.9.4
What do you mean by deployment?
I'm running Raspiblitz version 1.7.1
I was trying to send a transaction.
The only thing I did recently was upgrade from Specter version 1.9.2 to 1.9.4

**Comment by k9ert** [comment]
The huge stacktrace is quite misleading. It's not the reason for the problem of not being able to send a transaction but it gives us a hint (`requests.exceptions.ConnectionError: SOCKSHTTPSConnectionPool(host='pypi.org', port=443)`): The raspi is not able to connect to pypi. Is the internet-connection working properly on your raspi?

The first message (`Didn't get transactions on change address`) gives a better reason. So it seems specter is failing on this line:
```
value_on_address = self.rpc.getreceivedbyaddress(self.change_address, 0)
```
This points towards a rpc-issue with you core-node. Is your core-node working properly?

In order to get better error-messages, i've created:
https://github.com/cryptoadvance/specter-desktop/pull/1691/files

I'd suggest to check your raspi for healthyness and then try again: Does this error persist?
