### ISSUE TITLE
Bug: `./utils/test-cypress.sh open` fails to initialize `tor-system`

### ISSUE THREAD

**Issue by relativisticelectron** [cryptoadvance/specter-desktop#1762]
**Describe the bug**
When I run `./utils/test-cypress.sh open`, I get the error message below.   `./utils/test-cypress.sh run` works fine though.

**Workaround**
I found that the following produces the same error, but at least shows the cypress test:
```
./utils/test-cypress.sh snapshot spec_wallet_send.js
./utils/test-cypress.sh open spec_wallet_send.js
```

**Screenshots**
```
[2022-06-15 07:50:02,913] INFO in server: Login disabled
[2022-06-15 07:50:02,913] INFO in server: Initializing Controller ...
[2022-06-15 07:50:02,958] INFO in server: Initializing REST ...
[2022-06-15 07:50:02,973] WARNING in specter: Failed to connect to Tor control port. Error: [Errno 111] Connection refused
[2022-06-15 07:50:02,973] ERROR in cli_server: Could not initialize tor-system
Traceback (most recent call last):
  File "/home/<user>/programs/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/<user>/programs/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/<user>/programs/specter-desktop/.env/lib/python3.9/site-packages/cryptoadvance/specter/__main__.py", line 7, in <module>
    entry_point()
  File "/home/<user>/programs/specter-desktop/.env/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/<user>/programs/specter-desktop/.env/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/<user>/programs/specter-desktop/.env/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/<user>/programs/specter-desktop/.env/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/<user>/programs/specter-desktop/.env/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/<user>/programs/specter-desktop/.env/lib/python3.9/site-packages/cryptoadvance/specter/cli/cli_server.py", line 202, in server
    run(debug=debug)
  File "/home/<user>/programs/specter-desktop/.env/lib/python3.9/site-packages/cryptoadvance/specter/cli/cli_server.py", line 189, in run
    app.run(debug=debug, **kwargs)
  File "/home/<user>/programs/specter-desktop/.env/lib/python3.9/site-packages/flask/app.py", line 920, in run
    run_simple(t.cast(str, host), port, self, **options)
  File "/home/<user>/programs/specter-desktop/.env/lib/python3.9/site-packages/werkzeug/serving.py", line 982, in run_simple
    s.bind(server_address)
OSError: [Errno 98] Address already in use

```

**Desktop (please complete the following information):**
 - Where is your specter running: local linux 
 - If you're running a binary, which OS: Kubuntu 22.04 LTS x86_64 
 - Specter Version: master

**Comment by k9ert** [comment]
I can reproduce the issue but simply ignored it because opening any test still worked for me. Looking at the code revealed the reaosn: specter is started twice in in sub_run. I've created a PR.

**Comment by relativisticelectron** [comment]
> I can reproduce the issue but simply ignored it because opening any test still worked for me. Looking at the code revealed the reason: specter is started twice in in sub_run. I've created a PR.

Great. Thanks!
