### ISSUE TITLE
cryptography.exceptions.InvalidSignature: Signature did not match digest. after Login

### ISSUE THREAD

**Issue by k9ert** [cryptoadvance/specter-desktop#1845]
**Describe the bug**
Via the chat ... after Login this error-message is shown:

```
Traceback (most recent call last):
  File "/home/specter/.env/lib/python3.9/site-packages/cryptography/fernet.py", line 119, in _verify_signature
    h.verify(data[-32:])
  File "/home/specter/.env/lib/python3.9/site-packages/cryptography/hazmat/primitives/hmac.py", line 74, in verify
    ctx.verify(signature)
  File "/home/specter/.env/lib/python3.9/site-packages/cryptography/hazmat/backends/openssl/hmac.py", line 75, in verify
    raise InvalidSignature("Signature did not match digest.")
cryptography.exceptions.InvalidSignature: Signature did not match digest.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/specter/.env/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/specter/.env/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/specter/.env/lib/python3.9/site-packages/cryptoadvance/specter/server_endpoints/auth.py", line 72, in login
    app.login("admin", request.form["password"])
  File "/home/specter/.env/lib/python3.9/site-packages/cryptoadvance/specter/server.py", line 142, in login
    user.decrypt_user_secret(password)
  File "/home/specter/.env/lib/python3.9/site-packages/cryptoadvance/specter/user.py", line 177, in decrypt_user_secret
    self.plaintext_user_secret = f.decrypt(token)
  File "/home/specter/.env/lib/python3.9/site-packages/cryptography/fernet.py", line 80, in decrypt
    return self._decrypt_data(data, timestamp, time_info)
  File "/home/specter/.env/lib/python3.9/site-packages/cryptography/fernet.py", line 137, in _decrypt_data
    self._verify_signature(data)
  File "/home/specter/.env/lib/python3.9/site-packages/cryptography/fernet.py", line 121, in _verify_signature
    raise InvalidToken
cryptography.fernet.InvalidToken
```
After clicking "to mainpage", specter seem to be fully funtioning, though.

![image](https://user-images.githubusercontent.com/117085/185586502-e951e07d-0cb7-4f62-90f7-631bcb823cfe.png)

**Desktop (please complete the following information):**
 - Where is your node running: raspiblitz
 - Where is your specter running: Raspiblitz (1.8)
 - Specter Version [e.g. 1.9.4]:  v1.10.5

**Comment by k9ert** [comment]
I think this has been resolved by recreating the `.specter`-folder. At least it's difficult to track down without being able to reproduce. Please reopen if necessary.
