### ISSUE TITLE
electron-builer:jammy not working for releasing

### ISSUE THREAD

**Issue by k9ert** [cryptoadvance/specter-desktop#1879]
In #1688 images got updated to python3.10. However, builds are failing in more or less genuine way when releasing with that image.
In [this build](https://gitlab.com/k9ert/specter-desktop/-/jobs/3005075527), there is an issue with a hash:
```
41204 INFO: Building PKG because PKG-00.toc is non existent
41204 INFO: Building PKG (CArchive) specterd.pkg
69055 INFO: Building PKG (CArchive) specterd.pkg completed successfully.
69176 INFO: Bootloader /builds/k9ert/specter-desktop/.buildenv/lib/python3.10/site-packages/PyInstaller/bootloader/Linux-64bit-intel/run
69176 INFO: checking EXE
69176 INFO: Building EXE because EXE-00.toc is non existent
69176 INFO: Building EXE from EXE-00.toc
69176 INFO: Copying bootloader EXE to /builds/k9ert/specter-desktop/pyinstaller/dist/specterd
69176 INFO: Appending PKG archive to custom ELF section in EXE
73007 INFO: Building EXE from EXE-00.toc completed successfully.
    --> Making us ready for building electron-app
npm WARN prepare removing existing node_modules/ before installation
> core-js@3.8.3 postinstall /builds/k9ert/specter-desktop/pyinstaller/electron/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"
> electron@13.6.9 postinstall /builds/k9ert/specter-desktop/pyinstaller/electron/node_modules/electron
> node install.js
Error: Generated checksum for "electron-v13.6.9-linux-x64.zip" did not match expected checksum.
    at Hash.<anonymous> (/builds/k9ert/specter-desktop/pyinstaller/electron/node_modules/sumchecker/index.js:133:20)
    at Hash.emit (events.js:400:28)
    at emitReadable_ (internal/streams/readable.js:555:12)
    at onEofChunk (internal/streams/readable.js:533:5)
    at readableAddChunk (internal/streams/readable.js:247:5)
    at Hash.Readable.push (internal/streams/readable.js:206:10)
    at Hash.Transform.push (internal/streams/transform.js:166:32)
    at done (internal/streams/transform.js:234:17)
    at internal/streams/transform.js:148:7
    at Hash._flush (internal/crypto/hash.js:71:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@13.6.9 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@13.6.9 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-09-09T11_57_18_747Z-debug.log
Uploading artifacts for failed job 00:01
Uploading artifacts...
WARNING: release/Specter-Setup-v1.13.0-pre3.exe: no matching files 
WARNING: release/specterd-v1.13.0-pre3-x86_64-linux-gnu.zip: no matching files 
WARNING: release/specter_desktop-v1.13.0-pre3-x86_64-linux-gnu.tar.gz: no matching files 
WARNING: release/SHA256SUMS-linux: no matching files 
WARNING: release/SHA256SUMS-linux.asc: no matching files 
WARNING: release/SHA256SUMS-win: no matching files 
WARNING: release/SHA256SUMS-win.asc: no matching files 
ERROR: No files to upload                          
Cleaning up file based variables 00:01
ERROR: Job failed: exit code 1
```

**Comment by k9ert** [comment]
On the other hand, i was not able to reproduce these issues locally and there are also runs where the jobs succeed:
https://gitlab.com/k9ert/specter-desktop/-/jobs/3005818522

**Comment by k9ert** [comment]
Seems like that was due to an ustable agent. Closing.
