### ISSUE TITLE
Bug: Generating an extension fails

### ISSUE THREAD

**Issue by relativisticelectron** [cryptoadvance/specter-desktop#1891]
**Describe the bug**
`python3 -m cryptoadvance.specter ext gen` leads to:
```
Should the extension work in isolated client mode (y/n)?: n
    --> Created requirements.txt
    --> Created .gitignore
Traceback (most recent call last):
  File "/home/<user>/programs/anaconda3/envs/specter/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/<user>/programs/anaconda3/envs/specter/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/<user>/programs/anaconda3/envs/specter/lib/python3.8/site-packages/cryptoadvance/specter/__main__.py", line 7, in <module>
    entry_point()
  File "/home/<user>/programs/anaconda3/envs/specter/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/<user>/programs/anaconda3/envs/specter/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/<user>/programs/anaconda3/envs/specter/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/<user>/programs/anaconda3/envs/specter/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/<user>/programs/anaconda3/envs/specter/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/<user>/programs/anaconda3/envs/specter/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/<user>/programs/anaconda3/envs/specter/lib/python3.8/site-packages/cryptoadvance/specter/cli/cli_ext.py", line 141, in gen
    extgen.generate()
  File "/home/<user>/programs/anaconda3/envs/specter/lib/python3.8/site-packages/cryptoadvance/specter/services/extension_gen.py", line 90, in generate
    self.generate_basics()
  File "/home/<user>/programs/anaconda3/envs/specter/lib/python3.8/site-packages/cryptoadvance/specter/services/extension_gen.py", line 97, in generate_basics
    self.render(f"{package_path}/service.py")
  File "/home/<user>/programs/anaconda3/envs/specter/lib/python3.8/site-packages/cryptoadvance/specter/services/extension_gen.py", line 173, in render
    rendered_text = template.render(ext=self, **kargv)
  File "/home/<user>/programs/anaconda3/envs/specter/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/<user>/programs/anaconda3/envs/specter/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "https://raw.githubusercontent.com/cryptoadvance/specterext-dummy/master/src/dummyorg/specterext/dummy/service.py", line 20, in top-level template code
jinja2.exceptions.TemplateRuntimeError: No filter named 'snakecase' found.

```

**Desktop (please complete the following information):**
 - local , on master
 - Ubuntu 22.04, python 3.8

**Comment by relativisticelectron** [comment]
This will be fixed by https://github.com/cryptoadvance/specter-desktop/pull/1887
