### ISSUE TITLE
After migration from mac Specter desktop to linux Specter desktop via Specter backup no utxos/txns found

### ISSUE THREAD

**Issue by ashjkl159** [cryptoadvance/specter-desktop#1947]
**Describe the bug**
After migration from mac Specter desktop to ubuntu Specter desktop, exporting Specter backup from mac and importing Specter backup in ubuntu and after rescanning the blockchain, no utxos/txns found

**To Reproduce**
1. in old mac setup, mac Specter desktop, go to settings and click "Download Specter backup(zip file)
2. in new linux setup, unzip zip file above and go to settings, click "Choose backup folder (unzipped)"
3. all devices and wallets are correctly imported
4. rescanning of the blockchain

**Expected behavior**
Wallets should show correct balances after rescannig, but it shows no balance at all

Errors from logs:
stderr-SPECTERD: ERROR in specter_error: Request error for method getreceivedbyaddress: Address not found in wallet
Traceback (most recent call last):
  File "cryptoadvance/specter/wallet.py", line 844, in getdata
  File "cryptoadvance/specter/rpc.py", line 450, in fn
cryptoadvance.specter.rpc.RpcError: Request error for method getreceivedbyaddress: Address not found in wallet

**Desktop (please complete the following information):**
 - Where is your node running: local / internal in both - old mac - BitcoinCore and new linux setup - bitcoind
 - Where is your specter running: local / internal in both - old mac and new linux setup
 - If you're running a binary, which OS: old setup MacOs, new setup Linux ubuntu 22.04 LTS
 - Specter Version old mac setup 1.10.2 , new linux setup 1.13.1

**Comment by ashjkl159** [comment]
do not worry i just re-created wallets manually from imported devices and after that scanning blockchain found txns/utxos
