### ISSUE TITLE
Ledger - HWI-Bridge call returned with an error: Internal error: open failed

### ISSUE THREAD

**Issue by stefanwouldgo** [cryptoadvance/specter-desktop#203]
When signing a multisig tx with Specter 0.5.2:

`[2020-07-10 10:28:19,276] INFO in _internal: 127.0.0.1 - - [10/Jul/2020 10:28:19] "POST /hwi/api/ HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/home/stefan/.local/lib/python3.8/site-packages/cryptoadvance/specter/json_rpc.py", line 36, in jsonrpc
    response["result"] = method(**request["params"]) # dict -> **kwargs
  File "/home/stefan/.local/lib/python3.8/site-packages/cryptoadvance/specter/hwi_rpc.py", line 108, in sign_tx
    client = self._get_client(device_type=device_type, fingerprint=fingerprint, path=path, passphrase=passphrase, chain=chain)
  File "/home/stefan/.local/lib/python3.8/site-packages/cryptoadvance/specter/hwi_rpc.py", line 139, in _get_client
    client = hwi_commands.get_client(device_type, path, passphrase)
  File "/home/stefan/.local/lib/python3.8/site-packages/hwilib/commands.py", line 34, in get_client
    client = client_constructor(device_path, password, expert)
  File "/home/stefan/.local/lib/python3.8/site-packages/hwilib/devices/ledger.py", line 104, in __init__
    device.open_path(path.encode())
  File "hid.pyx", line 72, in hid.device.open_path
OSError: open failed
`
This is on Ledger Nano S secure element 1.6, microcontroller 1.12, bitcoin app 1.4.2

**Comment by stepansnigirev** [comment]
I made a PR that will hopefully fix this issue - #205 
Could you check if the issue remains with this PR?

**Comment by stepansnigirev** [comment]
I will reopen until @stefanwouldgo could confirm that the issue is solved.

**Comment by stefanwouldgo** [comment]
Just tried Specter 0.5.3. Unfortunately, the issue isn't quite solved. The error described above doesn't appear anymore, but I still cannot sign the tx. In fact, the behavior now is even stranger. First, ledger got into look showing me the same tx to approve again and again. After some time, I got a few errors:
`[2020-07-11 18:28:34,253] INFO in _internal: 127.0.0.1 - - [11/Jul/2020 18:28:34] "POST /hwi/api/ HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/home/stefan/.local/lib/python3.8/site-packages/hwilib/devices/ledger.py", line 75, in func
    return f(*args, **kwargs)
  File "/home/stefan/.local/lib/python3.8/site-packages/hwilib/devices/ledger.py", line 293, in sign_tx
    self.app.finalizeInput(b"DUMMY", -1, -1, change_path, tx_bytes)
  File "/home/stefan/.local/lib/python3.8/site-packages/hwilib/devices/btchip/btchip.py", line 284, in finalizeInput
    response = self.dongle.exchange(bytearray(apdu))
  File "/home/stefan/.local/lib/python3.8/site-packages/hwilib/devices/btchip/btchipComm.py", line 127, in exchange
    raise BTChipException("Invalid status %04x" % sw, sw)
hwilib.devices.btchip.btchipException.BTChipException: Exception : Invalid status 6d00

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stefan/.local/lib/python3.8/site-packages/cryptoadvance/specter/json_rpc.py", line 36, in jsonrpc
    response["result"] = method(**request["params"]) # dict -> **kwargs
  File "/home/stefan/.local/lib/python3.8/site-packages/cryptoadvance/specter/helpers.py", line 21, in wrapper_fn
    return fn(*args, **kwargs)
  File "/home/stefan/.local/lib/python3.8/site-packages/cryptoadvance/specter/hwi_rpc.py", line 130, in sign_tx
    raise e
  File "/home/stefan/.local/lib/python3.8/site-packages/cryptoadvance/specter/hwi_rpc.py", line 119, in sign_tx
    status = hwi_commands.signtx(client, psbt)
  File "/home/stefan/.local/lib/python3.8/site-packages/hwilib/commands.py", line 85, in signtx
    return client.sign_tx(tx)
  File "/home/stefan/.local/lib/python3.8/site-packages/hwilib/devices/ledger.py", line 80, in func
    raise BadArgumentError('Bad argument')
hwilib.errors.BadArgumentError: Bad argument
`
All the time, specter doesn't recognize anything being signed now. 

After restarting specter, everything seems to work OK when signing, that is the Ledger shows me the tx, I approve, and the dialog closes on the screen as well as on the Ledger. However, specter still doesn't recognize anything being signed now (still 1/2 signatures aquired), but no error messages as well.

**Comment by stefanwouldgo** [comment]
Tried it again with a fresh and completely unsigned tx. This time, a new problem arose. When I clicked sign for the first time, the device had gone asleep. Unfortunately, specter didn't notice it immediately ("Your Ledger is now ready"), but later when trying to sign it returned `'Device is asleep'`. Command line said the following:
`[2020-07-11 18:47:58,497] INFO in _internal: 127.0.0.1 - - [11/Jul/2020 18:47:58] "POST /hwi/api/ HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/home/stefan/.local/lib/python3.8/site-packages/hwilib/devices/ledger.py", line 75, in func
    return f(*args, **kwargs)
  File "/home/stefan/.local/lib/python3.8/site-packages/hwilib/devices/ledger.py", line 175, in sign_tx
    master_fpr = hash160(compress_public_key(self.app.getWalletPublicKey('')["publicKey"]))[:4]
  File "/home/stefan/.local/lib/python3.8/site-packages/hwilib/devices/btchip/btchip.py", line 97, in getWalletPublicKey
    response = self.dongle.exchange(bytearray(apdu))
  File "/home/stefan/.local/lib/python3.8/site-packages/hwilib/devices/btchip/btchipComm.py", line 127, in exchange
    raise BTChipException("Invalid status %04x" % sw, sw)
hwilib.devices.btchip.btchipException.BTChipException: Exception : Invalid status 6faa

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stefan/.local/lib/python3.8/site-packages/cryptoadvance/specter/json_rpc.py", line 36, in jsonrpc
    response["result"] = method(**request["params"]) # dict -> **kwargs
  File "/home/stefan/.local/lib/python3.8/site-packages/cryptoadvance/specter/helpers.py", line 21, in wrapper_fn
    return fn(*args, **kwargs)
  File "/home/stefan/.local/lib/python3.8/site-packages/cryptoadvance/specter/hwi_rpc.py", line 130, in sign_tx
    raise e
  File "/home/stefan/.local/lib/python3.8/site-packages/cryptoadvance/specter/hwi_rpc.py", line 119, in sign_tx
    status = hwi_commands.signtx(client, psbt)
  File "/home/stefan/.local/lib/python3.8/site-packages/hwilib/commands.py", line 85, in signtx
    return client.sign_tx(tx)
  File "/home/stefan/.local/lib/python3.8/site-packages/hwilib/devices/ledger.py", line 84, in func
    raise DeviceConnectionError('Device is asleep')
hwilib.errors.DeviceConnectionError: Device is asleep
`
So far, that's OK, but then when I woke up the device and tried to sign again, I got the same 'hwi returned "device is asleep"' again and again. After some tries, the same behavior described above returned (signing loop on device, no errors and no signatures recognized by specter).

**Comment by stepansnigirev** [comment]
Let's try again, how about v0.5.4?)

**Comment by stefanwouldgo** [comment]
> Let's try again, what about v0.5.4?)

Not much better. No errors, no loops, but also no recognition of signatures:

`[2020-07-14 10:48:16,538] INFO in _internal: 127.0.0.1 - - [14/Jul/2020 10:48:16] "POST /hwi/api/ HTTP/1.1" 200 -
[2020-07-14 10:48:46,533] INFO in _internal: 127.0.0.1 - - [14/Jul/2020 10:48:46] "POST /hwi/api/ HTTP/1.1" 200 -
[2020-07-14 10:48:51,115] INFO in _internal: 127.0.0.1 - - [14/Jul/2020 10:48:51] "POST /wallets/multisig/combine/ HTTP/1.1" 200 -
`

Still 0 signatures aquired after accepting on the Ledger.

**Comment by stepansnigirev** [comment]
Can you open the developer console and check the output?
If you could post here or DM me the psbt transactions I could try to debug. 
Should look like this when you sign a transaction on ledger:

<img width="1207" alt="Screenshot 2020-07-14 at 12 10 29" src="https://user-images.githubusercontent.com/1706012/87413776-0a4be380-c5cb-11ea-87ec-46f3e45268f6.png">

**Comment by stepansnigirev** [comment]
I also see that Specter didn't recognize the signature even though it's there. But when I signed with the second device it actually offered me to broadcast the transaction. Could you try to pretend that the signature was recognized and sign with the second device as well?

**Comment by stefanwouldgo** [comment]
> I also see that Specter didn't recognize the signature even though it's there. But when I signed with the second device it actually offered me to broadcast the transaction. Could you try to pretend that the signature was recognized and sign with the second device as well?

I tried, but it didn't change anything. The counter remained at 0, though the Coldcard signature was displayed as OK. And whether I tried to sign with the Ledger before or after the Coldcard, I was never offered to broadcast anything.

**Comment by stepansnigirev** [comment]
Hm, very strange... Does the fingerprint of Ledger match the key? Could it be that you are using ledger with wrong key?

In ~/.specter/devices folder there should be one json file with ledger, there should be information about the fingerprint. Is it the same as the one shown when Ledger is detected? Is there also non-empty derivation path?

It looks like psbt goes to Ledger and Ledger returns it without changes - so it just doesn't sign anything. Might be because something is wrong with the derivation information.

**Comment by stefanwouldgo** [comment]
Indeed, the fingerprints are different! I'm sorry, it was all my fault. I had used a different PIN on the Ledger than I remembered. With the other one it works flawlessly. Maybe this is an opportunity to present a helpful error message, but it was really just dumb user error. Sorry again!

**Comment by stepansnigirev** [comment]
Good point - we should check the fingerprint if we have information about it and warn the user if something is wrong.
I opened an issue #226
