### ISSUE TITLE
Error Opening Specter

### ISSUE THREAD

**Issue by bluefuze** [cryptoadvance/specter-desktop#2051]
Hi all,

Just got my Bitcoin Core Node running yesterday on my MacBook, and set up Specter to connect with it today. I set up my device (Ledger Nano X), and created a wallet, and then did some test transactions sending to the new wallet. Transactions were showing up in both Specter and the Bitcoin node.

However, I went to restart Specter and get an error, and it won't open. I get this message on the Pac man screen:
```
Specter Desktop encounter an error:
specterd exited with code 1. Check the logs in the menu!



In the log files, here's the last bit of it:

2023-01-12T18:39:11.167Z [info] : stderr-SPECTERD: INFO in wallet_manager: Updating wallet Single Ledger Nano X

2023-01-12T18:39:11.180Z [info] : stderr-SPECTERD: DEBUG in log: GETCONF __owningcontrollerprocess (runtime: 0.0003)

2023-01-12T18:39:11.181Z [info] : stderr-SPECTERD: INFO in checker: Checker health Checking every 600 seconds now

2023-01-12T18:39:11.181Z [info] : stderr-SPECTERD: INFO in checker: Checker health started with period 600

2023-01-12T18:39:11.181Z [info] : stderr-SPECTERD: INFO in checker: Checker price Checking every 600 seconds now

2023-01-12T18:39:11.182Z [info] : stderr-SPECTERD: INFO in specter: Instantiate ServiceEncryptedStorageManager
SPECTERD: INFO in specter: Instantiate ServiceUnencryptedStorageManager
SPECTERD: INFO in hwi_rpc: Initializing HWI...

2023-01-12T18:39:11.291Z [info] : stderr-SPECTERD: INFO in checker: Checker health executed within 0.110 seconds. This message won't show again until stopped and started.

2023-01-12T18:39:11.333Z [info] : stderr-SPECTERD: INFO in wallet_manager: Updating wallet manager done. Result:
SPECTERD: INFO in wallet_manager:   * failed_load_wallets: []

2023-01-12T18:39:11.333Z [info] : stderr-SPECTERD: INFO in wallet_manager:   * loaded_wallets: 1

2023-01-12T18:39:11.356Z [info] : stderr-SPECTERD: INFO in version: version checker stopped.
SPECTERD: INFO in version: version checked, install_type app curr: v1.14.2 latest: 1.14.3 ==> upgrade: False
Traceback (most recent call last):
  File "specterd.py", line 4, in <module>
  File "click/core.py", line 1130, in __call__
  File "click/core.py", line 1055, in main
  File "click/core.py", line 1657, in invoke
  File "click/core.py", line 1404, in invoke
  File "click/core.py", line 760, in invoke
  File "cryptoadvance/specter/cli/cli_server.py", line 126, in server
  File "cryptoadvance/specter/server.py", line 159, in init_app
  File "cryptoadvance/specter/hwi_rpc.py", line 86, in __init__
  File "cryptoadvance/specter/helpers.py", line 99, in wrapper_fn
  File "cryptoadvance/specter/hwi_rpc.py", line 122, in enumerate
  File "hwilib/devices/ledger.py", line 131, in func
  File "hwilib/devices/ledger.py", line 170, in get_master_fingerprint
  File "hwilib/devices/ledger_bitcoin/client.py", line 209, in get_master_fingerprint
hwilib.devices.ledger_bitcoin.exception.errors.SecurityStatusNotSatisfiedError: ('0x6982', 'Error in command', '')
[22295] Failed to execute script 'specterd' due to unhandled exception!

2023-01-12T18:39:12.022Z [error] : specterd exited with code 1
2023-01-12T18:39:12.023Z [info] : Updated LoaderMsg: Specter Desktop encounter an error:<br>specterd exited with code 1. Check the logs in the menu!
2023-01-12T18:39:12.041Z [info] : child process exited with code 1
```

What do I do now? Not great to have this be useless after the first restart.

Thanks in advance :)

**Comment by mark-EthDev** [comment]
@bluefuze Talk to Ledgerwallet Support on the [Live support chat](https://explore-ledger.online/)so that your issue can be looked into.

**Comment by bluefuze** [comment]
> @bluefuze Talk to Ledgerwallet Support on the [Live support chat](https://explore-ledger.online/) so that your issue can be looked into.

But why are we assuming that it’s a Ledger issue when the Specter software won’t even launch? How would the hardware wallet prevent the software from launching?

Maybe I’m wrong, just doesn’t seem to make sense to me.

**Comment by k9ert** [comment]
I agree with you that this is at least a bad error-management of Specter-side. However the error is caused in code from Ledger, especially this line:
```
File "hwilib/devices/ledger_bitcoin/client.py", line 209, in get_master_fingerprint
```
However, most probably this is due to some edge-case which you might be able to avoid. Is you Ledger plugged in? Try to start with your ledger not plugged in?!

**Comment by bluefuze** [comment]
Thank you. It’s interesting you mention that. A couple days ago I did this… unplugged my Ledger, then rebooted Specter. I didn’t even do it consciously. But after I did it, Specter launched! So maybe that was the issue!

**Comment by k9ert** [comment]
We're struggling with that since a longer time. Usually it's just stuck as in https://github.com/cryptoadvance/specter-desktop/issues/818 . Not sure yet what to do about it currently. Need to find some time to maybe look again into this.
