### ISSUE TITLE
Bug: Invalid version: 'vx.y.z-get-replaced-by-release-script'

### ISSUE THREAD

**Issue by relativisticelectron** [cryptoadvance/specter-desktop#2069]
**Describe the bug**
Running `pip3 install  -e  .  ` with  `pip 22.3.1`   and  `python 3.10.4` I get:

```
pip3 install  -e  .                                                                                   
Obtaining file:///home/<user>/programs/specter-desktop
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      /home/<user>/programs/anaconda3/envs/python3.10.4/lib/python3.10/site-packages/setuptools/dist.py:543: UserWarning: The version specified ('vx.y.z-get-replaced-by-release-script') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
        warnings.warn(
      running egg_info
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/<user>/programs/specter-desktop/setup.py", line 39, in <module>
          setup(
        File "/home/<user>/programs/anaconda3/envs/python3.10.4/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/home/<user>/programs/anaconda3/envs/python3.10.4/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/<user>/programs/anaconda3/envs/python3.10.4/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/<user>/programs/anaconda3/envs/python3.10.4/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/<user>/programs/anaconda3/envs/python3.10.4/lib/python3.10/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/home/<user>/programs/anaconda3/envs/python3.10.4/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.ensure_finalized()
        File "/home/<user>/programs/anaconda3/envs/python3.10.4/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
          self.finalize_options()
        File "/home/<user>/programs/anaconda3/envs/python3.10.4/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 219, in finalize_options
          parsed_version = parse_version(self.egg_version)
        File "/home/<user>/programs/anaconda3/envs/python3.10.4/lib/python3.10/site-packages/pkg_resources/_vendor/packaging/version.py", line 266, in __init__
          raise InvalidVersion(f"Invalid version: '{version}'")
      pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: 'vx.y.z-get-replaced-by-release-script'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

**Desktop (please complete the following information):**
 - Where is your node running: local(external)]
 - Where is your specter running:  linux, current master

**Comment by k9ert** [comment]
Yes, the way we do that is not really state of the art. In order to fix that, we'd need to migrate to a better releasing process. I recently looked into https://github.com/pypa/setuptools_scm/ which would fix that.
A quickfix might be, to replace `vx.y.z-get-replaced-by-release-script` with `v0.0.0` (4 files) .
