### ISSUE TITLE
Cypress tests do have weird exceptions: Invalid URL 'http://:8332': No host supplied

### ISSUE THREAD

**Issue by k9ert** [cryptoadvance/specter-desktop#2159]
```
[  DEBUG] in            node: Node is not running, no RPC connection, check_info didn't succeed, setting RPC attribute to None ...
[  DEBUG] in            node: Updating <Node name= fullpath=>.rpc None with None (setter)
[  ERROR] in            node: Invalid URL 'http://:8332': No host supplied
Traceback (most recent call last):
  File "/tmp/cirrus-ci-build/src/cryptoadvance/specter/node.py", line 426, in _get_rpc
    res = rpc.getblockchaininfo()
  File "/tmp/cirrus-ci-build/src/cryptoadvance/specter/rpc.py", line 501, in fn
    r = self.multi([(method, *args)], **kwargs)[0]
  File "/tmp/cirrus-ci-build/src/cryptoadvance/specter/rpc.py", line 415, in multi
    r = self.session.post(
  File "/tmp/cirrus-ci-build/.env/lib/python3.10/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/tmp/cirrus-ci-build/.env/lib/python3.10/site-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/tmp/cirrus-ci-build/.env/lib/python3.10/site-packages/requests/sessions.py", line 456, in prepare_request
    p.prepare(
  File "/tmp/cirrus-ci-build/.env/lib/python3.10/site-packages/requests/models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "/tmp/cirrus-ci-build/.env/lib/python3.10/site-packages/requests/models.py", line 393, in prepare_url
    raise InvalidURL("Invalid URL %r: No host supplied" % url)
requests.exceptions.InvalidURL: Invalid URL 'http://:8332': No host supplied
[  DEBUG] in            node: connection <BitcoinRpc http://localhost:15443> failed test_connection in check_info:
[  DEBUG] in            node: Node is not running, no RPC connection, check_info didn't succeed, setting RPC attribute to None ...
```

e.g. here:
https://cirrus-ci.com/task/6325572637294592

I haven't seen them while executing the tests locally, though.

**Comment by al-munazzim** [comment]
## Issue Assessment

**Type**: CI/Testing Infrastructure Bug  
**Verdict**: FIX  
**Priority**: MEDIUM (affects CI reliability but not user functionality)

**Assessment**: Cypress tests failing in CI with malformed Bitcoin RPC URL error: "Invalid URL 'http://:8332': No host supplied". The URL is missing the hostname portion, resulting in an invalid format that Python's requests library rejects.

**Root cause**: Configuration issue where Bitcoin RPC host is empty/undefined but port (8332) is set, creating malformed URL .

**Likely causes**:
1. Environment variable  not set in CI environment
2. Default configuration falling back to empty string instead of 'localhost'  
3. Test setup not properly initializing node configuration
4. Race condition where node config loaded before host is set

**Fix**: 
1. Add validation in RPC URL construction to ensure host defaults to 'localhost' when empty
2. Update CI configuration to explicitly set 
3. Add defensive programming in  URL builder
4. Improve error messages for malformed RPC URLs

**Implementation**: Check  and  for URL construction logic, ensure proper defaults and validation.

**Notes**: Issue may be intermittent (reporter noted "haven't seen them while executing the tests locally") suggesting CI environment-specific configuration problem.
