### ISSUE TITLE
Cannot save authentication changes

### ISSUE THREAD

**Issue by k9ert** [cryptoadvance/specter-desktop#2192]
**Describe the bug**
```
Traceback (most recent call last):
  File "/home/kim/src/specter-desktop/.env/lib/python3.10/site-packages/cryptography/fernet.py", line 119, in _verify_signature
    h.verify(data[-32:])
  File "/home/kim/src/specter-desktop/.env/lib/python3.10/site-packages/cryptography/hazmat/primitives/hmac.py", line 74, in verify
    ctx.verify(signature)
  File "/home/kim/src/specter-desktop/.env/lib/python3.10/site-packages/cryptography/hazmat/backends/openssl/hmac.py", line 75, in verify
    raise InvalidSignature("Signature did not match digest.")
cryptography.exceptions.InvalidSignature: Signature did not match digest.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kim/src/specter-desktop/.env/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kim/src/specter-desktop/.env/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kim/src/specter-desktop/src/cryptoadvance/specter/server_endpoints/auth.py", line 38, in login
    return login_method_passwordonly()
  File "/home/kim/src/specter-desktop/src/cryptoadvance/specter/server_endpoints/auth.py", line 122, in login_method_passwordonly
    app.login("admin", request.form["password"])
  File "/home/kim/src/specter-desktop/src/cryptoadvance/specter/server.py", line 194, in login
    user.decrypt_user_secret(password)
  File "/home/kim/src/specter-desktop/src/cryptoadvance/specter/user.py", line 186, in decrypt_user_secret
    self.plaintext_user_secret = f.decrypt(token)
  File "/home/kim/src/specter-desktop/.env/lib/python3.10/site-packages/cryptography/fernet.py", line 80, in decrypt
    return self._decrypt_data(data, timestamp, time_info)
  File "/home/kim/src/specter-desktop/.env/lib/python3.10/site-packages/cryptography/fernet.py", line 137, in _decrypt_data
    self._verify_signature(data)
  File "/home/kim/src/specter-desktop/.env/lib/python3.10/site-packages/cryptography/fernet.py", line 121, in _verify_signature
    raise InvalidToken
cryptography.fernet.InvalidToken


Please let us know! Create an [issue](https://github.com/cryptoadvance/specter-desktop/issues) or ping us on [Telegram](https://t.me/spectersupport) to fix it.
```

**To Reproduce**
1. change auth to password auth
2. log out
3. login by typing the password and click on login

**Expected behavior**
NonO Error!

**Additional context**
Almost pre10

**Comment by moneymanolis** [comment]
The Save button below is broken for me. How did you manage to save at all?

<img width="738" alt="grafik" src="https://user-images.githubusercontent.com/70536101/218491048-66b669ad-ee59-4930-b7ef-7f3aa602766c.png">
