### ISSUE TITLE
Failed to load utxos (KeyError)

### ISSUE THREAD

**Issue by moneymanolis** [cryptoadvance/specter-desktop#2236]
After the re-import of wallets I get several `KeyErrors` in the form of:
```
Failed to load utxos, KeyError: '378b5dda3bf3b30b98aba4ce4d7c4f2673c949953b98de0473605859dbcae272'File "/Users/heinzi/coding/repos/specter-desktop/src/cryptoadvance/specter/wallet.py", line 859, in check_utxo
    tx: WalletAwareTxItem = txlist_dict[utxo_txid]
KeyError: '378b5dda3bf3b30b98aba4ce4d7c4f2673c949953b98de0473605859dbcae272'During handling of the above exception, another exception occurred:Traceback (most recent call last):
  File "/Users/heinzi/.pyenv/versions/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/Users/heinzi/coding/repos/specter-desktop/src/cryptoadvance/specter/util/flask.py", line 32, in run
    super().run()
  File "/Users/heinzi/.pyenv/versions/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/heinzi/coding/repos/specter-desktop/src/cryptoadvance/specter/managers/wallet_manager.py", line 261, in _update
    self.wallets[wallet_name].update()
  File "/Users/heinzi/coding/repos/specter-desktop/src/cryptoadvance/specter/wallet.py", line 649, in update
    self.getdata()
  File "/Users/heinzi/coding/repos/specter-desktop/src/cryptoadvance/specter/wallet.py", line 943, in getdata
    self.check_utxo()
  File "/Users/heinzi/coding/repos/specter-desktop/src/cryptoadvance/specter/wallet.py", line 878, in check_utxo
    raise SpecterError(f"Failed to load utxos, {type(e).__name__}: {e}")
cryptoadvance.specter.specter_error.SpecterError: Failed to load utxos, KeyError: '378b5dda3bf3b30b98aba4ce4d7c4f2673c949953b98de0473605859dbcae272'
```

We've narrowed the issue down to the `listtransactions` RPC call from Core (in `fetch_transactions()` in `wallet.py`) not returning all transactions. The working theory is that it is related to this issue in Core where `listtransactions` is not returning transactions that are self-sends: https://github.com/bitcoin/bitcoin/issues/26096

**Comment by moneymanolis** [comment]
### Updates

- `listsinceblock` does not return the transactions either.

- Here is the output from `listdescriptors`:

```
 "wallet_name": "specterb89971bf662437c6/core_ghost",
  "descriptors": [
    {
      "desc": "wpkh([8c24a510/84'/1'/0']tpubDC4DsqH5rqHqipMNqUbDFtQT3AkKkUrvLsN6miySvortU3s1LGaNVAb7wX2No2VsuxQV82T8s3HJLv3kdx1CPjsJ3onC1Zo5mWCQzRVaWVX/0/*)#ftwsjm3c",
      "timestamp": 1675439925,
      "active": true,
      "internal": false,
      "range": [
        0,
        1029
      ],
      "next": 30
    },
    {
      "desc": "wpkh([8c24a510/84'/1'/0']tpubDC4DsqH5rqHqipMNqUbDFtQT3AkKkUrvLsN6miySvortU3s1LGaNVAb7wX2No2VsuxQV82T8s3HJLv3kdx1CPjsJ3onC1Zo5mWCQzRVaWVX/1/*)#clt30wpq",
      "timestamp": 1675439925,
      "active": true,
      "internal": true,
      "range": [
        0,
        1020
      ],
      "next": 21
    }
  ]
}
```

This is the result from: 
`bitcoin-cli -rpcwallet="specterb89971bf662437c6/core_ghost" listunspent | jq 'map(select(.txid == "378b5dda3bf3b30b98aba4ce4d7c4f2673c949953b98de0473605859dbcae272"))'`

<img width="859" alt="grafik" src="https://user-images.githubusercontent.com/70536101/220183589-86a996fe-9a22-412f-9086-2f2a9aee35e3.png">

**Comment by moneymanolis** [comment]
After reimporting the wallet in Specter (using uiux-revamp "master"), the transactions showed up with `listtransactions` again. With bitcoind version 22.0 and 24.0.1. I could also not reproduce the issue with a new wallet.
Really not sure what is / was going on. I am closing this for now, we can reopen if it pops up again.

**Comment by mpolavieja** [comment]
Hello, I am getting this error after receiving L-BTC in my liquid wallet.  I have tried with Jade and Specter DIY, and I get the same problem in both.  Once I receive the L-BTC, the wallet fails to load and this message is shown:

Failed to load utxos, KeyError: 'a16653f3d53da5d5cee06da5e8f730e5020a1909d4629916f09645106f06a094' 

This is the log file:

`
023-05-12T20:10:21.343Z [info] : stderr-SPECTERD: INFO in config_manager: Config loaded from file C:\Users\manue\.specter\config.json

2023-05-12T20:10:21.576Z [info] : stderr-SPECTERD: INFO in wallet_manager: starting update of wallet_manager (threading: True , comment: via user)

2023-05-12T20:10:21.641Z [info] : stderr-SPECTERD: INFO in tx_fetcher: Those addresses got used recently: []

2023-05-12T20:10:21.645Z [info] : stderr-SPECTERD: INFO in tx_fetcher: Those addresses got used recently: []

2023-05-12T20:10:21.668Z [info] : stderr-SPECTERD: ERROR in wallet: 'a16653f3d53da5d5cee06da5e8f730e5020a1909d4629916f09645106f06a094'
Traceback (most recent call last):
  File "cryptoadvance\specter\wallet\wallet.py", line 754, in check_utxo
KeyError: 'a16653f3d53da5d5cee06da5e8f730e5020a1909d4629916f09645106f06a094'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cryptoadvance\specter\wallet\wallet.py", line 760, in check_utxo
KeyError: 'a16653f3d53da5d5cee06da5e8f730e5020a1909d4629916f09645106f06a094'

2023-05-12T20:10:21.669Z [info] : stderr-SPECTERD: INFO in wallet_manager: starting update of wallet_manager (threading: True , comment: via server_specter_error)
SPECTERD: INFO in controller: GET, /wallets/wallet/specterliquid2/history/ , 302, took,  333, ms

2023-05-12T20:10:21.672Z [info] : stderr-SPECTERD: INFO in tx_fetcher: Those addresses got used recently: []

2023-05-12T20:10:21.683Z [info] : stderr-SPECTERD: INFO in controller: GET, /welcome/about                          , 200, took,    8, ms

2023-05-12T20:10:21.689Z [info] : stderr-SPECTERD: ERROR in wallet: 'a16653f3d53da5d5cee06da5e8f730e5020a1909d4629916f09645106f06a094'
Traceback (most recent call last):
  File "cryptoadvance\specter\wallet\wallet.py", line 754, in check_utxo
KeyError: 'a16653f3d53da5d5cee06da5e8f730e5020a1909d4629916f09645106f06a094'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cryptoadvance\specter\wallet\wallet.py", line 760, in check_utxo
KeyError: 'a16653f3d53da5d5cee06da5e8f730e5020a1909d4629916f09645106f06a094'
SPECTERD: INFO in wallet_manager: Updating wallet manager done in    65ms. Result:
SPECTERD: INFO in wallet_manager:   * loaded_wallets: 2

2023-05-12T20:10:21.689Z [info] : stderr-SPECTERD: INFO in wallet_manager:   * failed_load_wallets: 0
Exception in thread Thread-1984 (_update):
Traceback (most recent call last):
  File "cryptoadvance\specter\wallet\wallet.py", line 754, in check_utxo

2023-05-12T20:10:21.690Z [info] : stderr-KeyError: 'a16653f3d53da5d5cee06da5e8f730e5020a1909d4629916f09645106f06a094'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cryptoadvance\specter\wallet\wallet.py", line 760, in check_utxo

2023-05-12T20:10:21.690Z [info] : stderr-KeyError: 'a16653f3d53da5d5cee06da5e8f730e5020a1909d4629916f09645106f06a094'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner

2023-05-12T20:10:21.690Z [info] : stderr-  File "cryptoadvance\specter\util\flask.py", line 32, in run

2023-05-12T20:10:21.690Z [info] : stderr-  File "threading.py", line 953, in run

2023-05-12T20:10:21.691Z [info] : stderr-  File "cryptoadvance\specter\managers\wallet_manager.py", line 243, in _update

2023-05-12T20:10:21.691Z [info] : stderr-  File "cryptoadvance\specter\wallet\wallet.py", line 492, in update

2023-05-12T20:10:21.691Z [info] : stderr-  File "cryptoadvance\specter\liquid\wallet.py", line 82, in getdata

2023-05-12T20:10:21.691Z [info] : stderr-  File "cryptoadvance\specter\wallet\wallet.py", line 796, in check_utxo

2023-05-12T20:10:21.691Z [info] : stderr-cryptoadvance.specter.specter_error.SpecterError: Failed to load utxos, KeyError: 'a16653f3d53da5d5cee06da5e8f730e5020a1909d4629916f09645106f06a094'

2023-05-12T20:10:24.784Z [info] : stderr-SPECTERD: INFO in controller: GET, /wallets/wallets_loading/               , 200, took,    1, ms

2023-05-12T20:10:24.831Z [info] : stderr-SPECTERD: INFO in controller: GET, /nodes/sync_status/                     , 200, took,   60, ms


`

**Comment by mpolavieja** [comment]
It has been solved by downgrading to version 1.14.5  I´ll close the issue for now

**Comment by Funman2** [comment]
I have the same issue with version 2.0.1 and higher, had to downgrade to 1.14.5 as well....

**Comment by Funman2** [comment]
Please reopen, since I gat the same Error in latest Version 2.0.2 pre!

**Comment by mpolavieja** [comment]
I didn't really close the issue, as I can't do it.  However I´ve been told in the telegram Specter community channel that Liquid is no longer supported on version 2 onwards, and that Liquid support it is not going to be mantained on older versions either.

**Comment by Funman2** [comment]
Oh i see, also I had the same issue with key error on main layer wallet, utxo error.
