### ISSUE TITLE
v2.0-pre27: Log says: No rescan of the blockchain with Spectrum.

### ISSUE THREAD

**Issue by moritzwietersheim** [cryptoadvance/specter-desktop#2248]
```
2023-02-23T16:06:38.355Z [info] : stderr-SPECTERD: INFO in spectrum: Script 3ddb49d is not synced None != 6692b22dc311ad45797e07cd638a7b5ec620f5f27c95a1c086bcbf0996d6b17f

2023-02-23T16:06:38.552Z [info] : stderr-SPECTERD: INFO in txlist: Cleared the Cache for /Users/moritzwietersheim/.specter/wallets/main/ms__kot_txs.csv (and rawdir)

2023-02-23T16:06:38.805Z [info] : stderr-SPECTERD: INFO in txlist: Cleared the Cache for /Users/moritzwietersheim/.specter/wallets/main/ms__kot_txs.csv (and rawdir)

2023-02-23T16:06:38.816Z [info] : stderr---- Logging error ---

2023-02-23T16:06:38.818Z [info] : stderr-Traceback (most recent call last):
  File "cryptoadvance/specter/util/wallet_importer.py", line 273, in rescan_as_needed
  File "cryptoadvance/specterext/spectrum/bridge_rpc.py", line 59, in rescanblockchain
cryptoadvance.specter.specter_error.SpecterError: No rescan of the blockchain with Spectrum.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging/__init__.py", line 1100, in emit
  File "logging/__init__.py", line 943, in format
  File "logging/__init__.py", line 678, in format
  File "logging/__init__.py", line 368, in getMessage
TypeError: not all arguments converted during string formatting
Call stack:
  File "threading.py", line 966, in _bootstrap
  File "threading.py", line 1009, in _bootstrap_inner
  File "threading.py", line 946, in run
  File "socketserver.py", line 683, in process_request_thread
  File "socketserver.py", line 360, in finish_request
  File "socketserver.py", line 747, in __init__
  File "werkzeug/serving.py", line 361, in handle
  File "http/server.py", line 425, in handle
  File "http/server.py", line 413, in handle_one_request
  File "werkzeug/serving.py", line 333, in run_wsgi
  File "werkzeug/serving.py", line 320, in execute
  File "flask/app.py", line 2095, in __call__
  File "werkzeug/middleware/proxy_fix.py", line 187, in __call__
  File "flask/app.py", line 2077, in wsgi_app
  File "flask/app.py", line 1523, in full_dispatch_request
  File "flask/app.py", line 1509, in dispatch_request
  File "flask_login/utils.py", line 290, in decorated_view
  File "cryptoadvance/specter/server_endpoints/settings.py", line 166, in general
  File "cryptoadvance/specter/util/wallet_importer.py", line 276, in rescan_as_needed
  File "logging/__init__.py", line 1512, in exception
  File "logging/__init__.py", line 1506, in error
  File "logging/__init__.py", line 1624, in _log
  File "logging/__init__.py", line 1634, in handle
  File "logging/__init__.py", line 1696, in callHandlers
  File "logging/__init__.py", line 968, in handle
  File "logging/__init__.py", line 1108, in emit
Message: "Exception while rescanning blockchain: SpecterError('No rescan of the blockchain with Spectrum.')"
Arguments: (SpecterError('No rescan of the blockchain with Spectrum.'),)

2023-02-23T16:06:38.818Z [info] : stderr-SPECTERD: INFO in txlist: Cleared the Cache for /Users/moritzwietersheim/.specter/wallets/main/ms__kot_txs.csv (and rawdir)

2023-02-23T16:06:38.821Z [info] : stderr-SPECTERD: INFO in settings: Importing wallet SingleSig - Know

2023-02-23T16:06:38.827Z [info] : stderr-SPECTERD: INFO in spectrum: Importing descriptor wpkh([1dd94378/84h/0h/0h]xpub6CskEbv5E9sRRYsUBArkaNXwGHeMrY1ZANrKKuU88r6SwUevW1i65SLJid63K33xhrZUDGNW5ppvvMQY7zKTiEpjTAe2JgzqkKE3s5BhvmB/0/*)#uqsgkrdu

2023-02-23T16:06:38.828Z [info] : stderr-SPECTERD: INFO in spectrum: Creating 300 scriptpubkeys for wallet <Wallet 2>

2023-02-23T16:06:38.981Z [info] : stderr-SPECTERD: INFO in spectrum: Importing descriptor wpkh([1dd94378/84h/0h/0h]xpub6CskEbv5E9sRRYsUBArkaNXwGHeMrY1ZANrKKuU88r6SwUevW1i65SLJid63K33xhrZUDGNW5ppvvMQY7zKTiEpjTAe2JgzqkKE3s5BhvmB/1/*)#d54ftkay

2023-02-23T16:06:38.986Z [info] : stderr-SPECTERD: INFO in spectrum: Creating 300 scriptpubkeys for wallet <Wallet 2>
```

**Comment by k9ert** [comment]
This is two-folded:
* The logging code threw an error which will be fixed [here](https://github.com/cryptoadvance/specter-desktop/pull/2254/files#diff-9b3093d00d56408e775512977ddc59c5ae73578d06b8629aaab19aa7ebe278ce)
* Spectrum is throwing an exception although it should silently pretend it has done what it has been asked for. Thiw will be fixed [here](https://github.com/cryptoadvance/specter-desktop/pull/2258/files#diff-b3be315b7312a8d3301bfd611395bf0ae43c49bef4cbe7460373f30b8404e5a6).

**Comment by k9ert** [comment]
should be fixed
