### ISSUE TITLE
Exception thrown deleting a non-connected node

### ISSUE THREAD

**Issue by k9ert** [cryptoadvance/specter-desktop#2285]
**Describe the bug**
```

Traceback (most recent call last):
  File "/home/kim/tmp/issue_tz/.env/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kim/tmp/issue_tz/.env/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kim/tmp/issue_tz/.env/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/kim/src/specter-desktop/src/cryptoadvance/specter/server_endpoints/nodes.py", line 203, in node_settings
    node_alias=app.specter.node.alias,
AttributeError: 'NonExistingNode' object has no attribute 'alias'
```

**To Reproduce**
1. have a non-connected bitcoin node
2. got to the config page of the node
3. delete it

**Expected behavior**
No exception should be thrown

**Desktop (please complete the following information):**
 - Where is your node running: dev instance
 - Specter Version `v2.0.0rc34`

**Comment by moneymanolis** [comment]
I can't reproduce this.
