### ISSUE TITLE
I can't create a wallet on 2.0.1

### ISSUE THREAD

**Issue by chocolatebarantlion** [cryptoadvance/specter-desktop#2329]
Hello,

I just updated Specter from 1.x . When I opened the app, it has lost the connection to my Bitcoin core, as well as my Ledger wallet, but not the keys of Ledger themselves.

I was able to connect Specter to my Bitcoin Core again no prob, but when I try to create a wallet, I get this message :

```
Exception
name 'RpcError' is not defined
[Back to the main page](http://localhost:25441/welcome/)
Details
version: v2.0.1
Traceback (most recent call last):
  File "cryptoadvance\specter\server_endpoints\wallets\wallets.py", line 139, in new_wallet_type
  File "cryptoadvance\specter\rpc.py", line 503, in fn
cryptoadvance.specter.rpc.RpcError: Request error for method listwallets(): Method not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "flask\app.py", line 1523, in full_dispatch_request
  File "flask\app.py", line 1509, in dispatch_request
  File "flask_login\utils.py", line 290, in decorated_view
  File "cryptoadvance\specter\server_endpoints\wallets\wallets.py", line 140, in new_wallet_type
NameError: name 'RpcError' is not defined
```

What should I do to solve the problem ?

**Comment by k9ert** [comment]
Would be great to get more information here. Maybe you can answer these questions:
``` 
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - Where is your node running: [e.g. raspiblitz, MyNode, umbrel, local(internal), local(external)]
 - Where is your specter running: [e.g. Raspiblitz, Node, umbrel, binary]
 - If you're running a binary, which OS: [e.g. Linux, MacOs, Windows]
 - Browser [e.g. chrome, safari]
 - Specter Version [e.g. 1.9.4]

**Additional context**
Add any other context about the problem here.
```

**Comment by Graciela985** [comment]
It's an issue with some wallets apparently.I had a similar issue. I contacted metamask/binance directly and they had it resolved for me. alarcongraciela985@gmail.com
Send them a mail. They'll help you out.
