### ISSUE TITLE
Add more keys on existing coldcard yields server error

### ISSUE THREAD

**Issue by stefanwouldgo** [cryptoadvance/specter-desktop#233]
`Server error!
Exception: 'mnemonic' is undefined

Details:
Traceback (most recent call last):
  File "/home/stefan/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/stefan/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/stefan/.local/lib/python3.8/site-packages/flask_login/utils.py", line 269, in decorated_view
    return func(*args, **kwargs)
  File "/home/stefan/.local/lib/python3.8/site-packages/cryptoadvance/specter/controller.py", line 914, in device
    return render_template("device/new_device.jinja",
  File "/home/stefan/.local/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/stefan/.local/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/stefan/.local/lib/python3.8/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/stefan/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/stefan/.local/lib/python3.8/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/stefan/.local/lib/python3.8/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/stefan/.local/lib/python3.8/site-packages/cryptoadvance/specter/templates/device/new_device.jinja", line 1, in 
    {% extends "base.jinja" %}
  File "/home/stefan/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "/home/stefan/.local/lib/python3.8/site-packages/cryptoadvance/specter/templates/device/new_device.jinja", line 14, in root
    
{{ device_name }}

  File "/home/stefan/.local/lib/python3.8/site-packages/cryptoadvance/specter/templates/base.jinja", line 71, in root
    document.addEventListener("notification", (e)=>{
  File "/home/stefan/.local/lib/python3.8/site-packages/cryptoadvance/specter/templates/device/new_device.jinja", line 62, in block_main
    Get over USB
  File "/home/stefan/.local/lib/python3.8/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'mnemonic' is undefined

Please let us know! Create an issue or ping us on Telegram to fix it.`

**Comment by stepansnigirev** [comment]
Thanks! It was fixed in https://github.com/cryptoadvance/specter-desktop/pull/221, and we plan for another minor release today :)

**Comment by stepansnigirev** [comment]
v0.5.5 is out that fixes this issue.
