### ISSUE TITLE
Specter does not start if Jade is plugged in and the serial port is still open

### ISSUE THREAD

**Issue by moneymanolis** [cryptoadvance/specter-desktop#2343]
Below is the stack trace. The error disappeared after running in the browser:
```
ports = await navigator.serial.getPorts()
await ports[0].close()
```

We'd need to implement a check for open ports and close them if there are any in Python. Sth. like this:

```
import serial.tools.list_ports as list_ports
ports = list(list_ports.comports())
if len(ports) > 0:
    port = ports[0].device
    ser = serial.Serial(port)
    ser.close()
```

Stack trace:

```
[2023-06-21 17:57:05,491] DEBUG in jade: Failed to connect to Jade simulator at tcp:127.0.0.1:2222
[2023-06-21 17:57:05,491] DEBUG in jade: [Errno 61] Connection refused
Traceback (most recent call last):
  File "/Users/manolis/.pyenv/versions/.specter/lib/python3.10/site-packages/serial/serialposix.py", line 322, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
OSError: [Errno 16] Resource busy: '/dev/cu.usbserial-024346F8'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/manolis/.pyenv/versions/3.10.0/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/manolis/.pyenv/versions/3.10.0/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/manolis/coding/repos/specter-desktop/src/cryptoadvance/specter/__main__.py", line 7, in <module>
    entry_point()
  File "/Users/manolis/.pyenv/versions/.specter/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/manolis/.pyenv/versions/.specter/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/manolis/.pyenv/versions/.specter/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/manolis/.pyenv/versions/.specter/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/manolis/.pyenv/versions/.specter/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/manolis/coding/repos/specter-desktop/src/cryptoadvance/specter/cli/cli_server.py", line 151, in server
    init_app(app, hwibridge=hwibridge)
  File "/Users/manolis/coding/repos/specter-desktop/src/cryptoadvance/specter/server.py", line 180, in init_app
    specter.hwi = HWIBridge()
  File "/Users/manolis/coding/repos/specter-desktop/src/cryptoadvance/specter/hwi_rpc.py", line 88, in __init__
    self.enumerate()
  File "/Users/manolis/coding/repos/specter-desktop/src/cryptoadvance/specter/helpers.py", line 99, in wrapper_fn
    return fn(*args, **kwargs)
  File "/Users/manolis/coding/repos/specter-desktop/src/cryptoadvance/specter/hwi_rpc.py", line 121, in enumerate
    client = devcls.get_client(dev["path"], passphrase)
  File "/Users/manolis/coding/repos/specter-desktop/src/cryptoadvance/specter/devices/jade.py", line 23, in get_client
    return JadeClient(*args, **kwargs)
  File "/Users/manolis/coding/repos/specter-desktop/src/cryptoadvance/specter/devices/hwi/jade.py", line 151, in __init__
    self.jade.connect()
  File "/Users/manolis/coding/repos/specter-desktop/src/cryptoadvance/specter/devices/hwi/jadepy/jade.py", line 123, in connect
    self.jade.connect()
  File "/Users/manolis/coding/repos/specter-desktop/src/cryptoadvance/specter/devices/hwi/jadepy/jade.py", line 568, in connect
    self.impl.connect()
  File "/Users/manolis/coding/repos/specter-desktop/src/cryptoadvance/specter/devices/hwi/jadepy/jade_serial.py", line 32, in connect
    self.ser = serial.Serial(
  File "/Users/manolis/.pyenv/versions/.specter/lib/python3.10/site-packages/serial/serialutil.py", line 244, in __init__
    self.open()
  File "/Users/manolis/.pyenv/versions/.specter/lib/python3.10/site-packages/serial/serialposix.py", line 325, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 16] could not open port /dev/cu.usbserial-024346F8: [Errno 16] Resource busy: '/dev/cu.usbserial-024346F8'


```

**Comment by k9ert** [comment]
Related but seem to look different in the logs: #818 ( tried to fix in #1748)

**Comment by moneymanolis** [comment]
I think this is issue is a special case of the "USB devices are plugged-in while starting-up Specter". It is not HWI related but is related to the serial connection used by the Jade (which none of the other devices are using btw AFAIK).

**Comment by stepansnigirev** [comment]
This is a problem of any connected device that goes into the locked mode (Jade, Ledger, maybe Trezor).
It is caused by this line:
https://github.com/cryptoadvance/specter-desktop/blob/master/src/cryptoadvance/specter/hwi_rpc.py#L88

The reason for this line was that if we didn't run `hwi.enumerate()` in the main thread HWI was failing to connect to the devices in the requests afterwards.
I don't know why exactly it happens, and if it was somehow fixed over the years. This hack was introduced in the very beginning when we just started implementing HWI - @kdmukai may remember.

It's worth trying to debug this issue in more detail now. Possible approaches:
- try removing this line, and then test if HWI still works with Jade and Ledger (pyserial device and usb_hid device)
- if not - figure out what exactly causing the issue. In particular, what part of `hwi.enumerate` is required in the main thread, maybe it's enough listing serial and usb devices without opening them. Then instead `hwi.enumerate()` we can do something simpler. We already have custom `enumerate` that tries to take that into account (see https://github.com/cryptoadvance/specter-desktop/blob/master/src/cryptoadvance/specter/hwi_rpc.py#L110), but seems that it doesn't work.
- spawn HWI in another process, but this requires a lot of work and overall pretty ugly.

**Comment by stepansnigirev** [comment]
@moneymanolis I tried without `enumerate` in `__init__`, seems to work fine on Linux.

Can you test on Mac and Win?

PR: https://github.com/cryptoadvance/specter-desktop/pull/2371

**Comment by moneymanolis** [comment]
The issue above still exists, if another app (e.g. a browser tab) is using Jade's serial port and one is trying to use the Jade in Specter.

This is the error in the UI:

<img width="764" alt="image" src="https://github.com/cryptoadvance/specter-desktop/assets/70536101/792afaa3-d1bc-4182-9647-caf1fa28184e">

**Comment by al-munazzim** [comment]
**Assessment:**

**Type:** Hardware Device Conflict Bug  
**Verdict:** FIX  
**Priority:** MEDIUM (crashes Specter startup but has workaround)

**Root Cause:**
Specter crashes during startup when attempting to enumerate Jade devices if another application (browser WebSerial, other wallet software) already has the serial port open. Python's `serial.Serial` fails with "Resource busy" exception.

**Technical Analysis:**
- **Error:** `OSError: [Errno 16] Resource busy: '/dev/cu.usbserial-024346F8'`
- **Location:** During HWI device enumeration in `hwi_rpc.py` startup
- **Impact:** Complete startup failure, not graceful degradation

**User's Solution Analysis:**
The JavaScript solution (`navigator.serial.getPorts()` + `ports[0].close()`) works for browser conflicts, but doesn't address conflicts with other desktop applications.

**Proposed Fix:**
1. **Defensive Programming:** Wrap serial port opening in try/catch during enumeration
2. **Graceful Degradation:** Log warning and skip busy devices instead of crashing
3. **Port Detection:** Add logic to detect which process is using the port (if possible)
4. **User Feedback:** Show clear error message about port conflicts with suggested resolution

**Implementation:**


**Priority:** MEDIUM because it has workarounds but creates poor UX with complete failure.

---

*This assessment is part of the ongoing issue triage effort. #SpecterMaintenance*
