### ISSUE TITLE
Can not load wallet after creating a transaction

### ISSUE THREAD

**Issue by delcaos** [cryptoadvance/specter-desktop#2369]
I have a 2-of-2 multisig wallet. I created a new transaction, signed it. Then I can no longer use or view the wallet, it gives: "Failed to load utxos, IndexError: list index out of range".

I have tried recreating the wallet and creating a transaction, and the same issue occurs. 

From the logs:
```
2023-08-23T04:20:30.681Z [info] : stderr-SPECTERD: INFO in tx_fetcher: Those addresses got used recently: []

2023-08-23T04:20:30.800Z [info] : stderr-SPECTERD: ERROR in wallet: list index out of range
Traceback (most recent call last):
  File "cryptoadvance/specter/wallet/wallet.py", line 776, in check_utxo
IndexError: list index out of range

2023-08-23T04:20:30.800Z [info] : stderr-SPECTERD: ERROR in wallet_manager: Failed to load utxos, IndexError: list index out of range
Traceback (most recent call last):
  File "cryptoadvance/specter/wallet/wallet.py", line 776, in check_utxo
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cryptoadvance/specter/managers/wallet_manager.py", line 226, in _update
  File "cryptoadvance/specter/wallet/wallet.py", line 643, in from_json
  File "cryptoadvance/specter/wallet/wallet.py", line 175, in __init__
  File "cryptoadvance/specter/wallet/wallet.py", line 492, in update
  File "cryptoadvance/specter/wallet/wallet.py", line 800, in getdata
  File "cryptoadvance/specter/wallet/wallet.py", line 796, in check_utxo
cryptoadvance.specter.specter_error.SpecterError: Failed to load utxos, IndexError: list index out of range
```

Using `Version 2.0.1 (2.0.1)` with a local bitcoin core `v24.0.1`

**Comment by moneymanolis** [comment]
Did you broadcast the transaction or only saved it for later broadcast? Seems related to https://github.com/cryptoadvance/specter-desktop/issues/2335

**Comment by delcaos** [comment]
It was a 2-of-2 multisig transaction, and I only applied the first signature. So the transaction was never eligible for broadcast

**Comment by k9ert** [comment]
This is most probably fixed since 2.1.0. Please reopen if that is not the case.
