### ISSUE TITLE
v2.0.2-pre6 - Could not add Jade as device

### ISSUE THREAD

**Issue by moritzwietersheim** [cryptoadvance/specter-desktop#2376]
**Describe the bug**
Could not add Jade as a device. See log below.

 - Where is your node running: Connected via public Electrum server (Blockstream).
 - Where is your specter running: MacBook Pro 14' 2021, M1 Pro, macOS 13.5.1
 - If you're running a binary, which OS: macOS 13.5.1
 - Browser: Chrome
 - Specter Version: v2.0.2-pre6

**Additional context**

---
Notification: 
![image](https://github.com/cryptoadvance/specter-desktop/assets/47259243/a4b79bff-e0ec-4337-908c-bba6a208b177)

--- 
Logs: 

2023-09-06T21:43:13.156Z [info] : stderr-SPECTERD: INFO in controller: GET, /nodes/sync_status/                     , 200, took,    0, ms

2023-09-06T21:43:14.494Z [info] : stderr-SPECTERD: INFO in controller: GET, /devices/new_device_type/               , 200, took,    8, ms

2023-09-06T21:43:14.556Z [info] : stderr-SPECTERD: INFO in controller: GET, /nodes/sync_status/                     , 200, took,    0, ms

2023-09-06T21:43:15.835Z [info] : stderr-SPECTERD: INFO in controller: GET, /devices/new_device_keys/jade/          , 200, took,   11, ms

2023-09-06T21:43:15.909Z [info] : stderr-SPECTERD: INFO in controller: GET, /nodes/sync_status/                     , 200, took,    0, ms

2023-09-06T21:43:35.690Z [info] : stderr-SPECTERD: INFO in controller: POST, /hwi/api/                               , 200, took, 17933, ms

2023-09-06T21:43:36.257Z [info] : stderr-SPECTERD: ERROR in json_rpc: Network/chain selection error
Traceback (most recent call last):
  File "cryptoadvance/specter/devices/hwi/jade.py", line 69, in func
  File "cryptoadvance/specter/devices/hwi/jade.py", line 175, in get_pubkey_at_path
  File "cryptoadvance/specter/devices/hwi/jadepy/jade.py", line 268, in get_xpub
  File "cryptoadvance/specter/devices/hwi/jadepy/jade.py", line 154, in _jadeRpc
  File "cryptoadvance/specter/devices/hwi/jadepy/jade.py", line 138, in _get_result_or_raise_error
cryptoadvance.specter.devices.hwi.jadepy.jade_error.JadeError: JadeError: -32003 - Network type inconsistent with prior usage (Data: None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cryptoadvance/specter/util/json_rpc.py", line 37, in jsonrpc
  File "cryptoadvance/specter/helpers.py", line 99, in wrapper_fn
  File "cryptoadvance/specter/hwi_rpc.py", line 263, in extract_xpub
  File "hwilib/hwwclient.py", line 69, in get_master_fingerprint
  File "cryptoadvance/specter/devices/hwi/jade.py", line 82, in func
hwilib.errors.DeviceConnectionError: Network/chain selection error

2023-09-06T21:43:36.259Z [info] : stderr-SPECTERD: INFO in controller: POST, /hwi/api/                               , 200, took,  556, ms

Log file:  [specterApp 230906.log](https://github.com/cryptoadvance/specter-desktop/files/12542809/specterApp.230906.log)

**Comment by k9ert** [comment]
This does not seem to be related to the removal of the hwi-enumerate. It rather looks like your jade is initialized with a testnet seed. You would probably need to factory-reset it if you want to use mainnet.

**Comment by k9ert** [comment]
Fixed by factory reset of the jade.
