### ISSUE TITLE
Server error when clicking "addresses"

### ISSUE THREAD

**Issue by Fonta1n3** [cryptoadvance/specter-desktop#238]
I am getting an error when clicking "addresses" (0.5.5 on macos) see the error log:
```
Traceback (most recent call last):
  File "/Users/peter/specter-desktop/src/cryptoadvance/specter/templates/wallet/history/addresses/wallet_addresses.jinja", line 79, in block_content
    }}
  File "/Users/peter/specter-desktop/.env/lib/python3.7/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
  File "/Users/peter/specter-desktop/src/cryptoadvance/specter/wallet.py", line 464, in active_addresses
    return list(dict.fromkeys(self.addresses + self.utxo_addresses))
  File "/Users/peter/specter-desktop/src/cryptoadvance/specter/wallet.py", line 402, in utxo_addresses
    key = lambda utxo: next(
  File "/Users/peter/specter-desktop/src/cryptoadvance/specter/wallet.py", line 403, in 
    tx for tx in self.transactions if tx["txid"] == utxo["txid"]
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/peter/specter-desktop/.env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/peter/specter-desktop/.env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/peter/specter-desktop/.env/lib/python3.7/site-packages/flask_login/utils.py", line 269, in decorated_view
    return func(*args, **kwargs)
  File "/Users/peter/specter-desktop/src/cryptoadvance/specter/controller.py", line 757, in wallet_addresses
    return render_template("wallet/history/addresses/wallet_addresses.jinja", wallet_alias=wallet_alias, wallet=wallet, alladdresses=alladdresses, viewtype=viewtype, specter=app.specter, rand=rand)
  File "/Users/peter/specter-desktop/.env/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/peter/specter-desktop/.env/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/peter/specter-desktop/.env/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/peter/specter-desktop/.env/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/peter/specter-desktop/.env/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/peter/specter-desktop/.env/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/peter/specter-desktop/src/cryptoadvance/specter/templates/wallet/history/addresses/wallet_addresses.jinja", line 2, in top-level template code
    {% set tab = 'wallet_addresses' %}
  File "/Users/peter/specter-desktop/.env/lib/python3.7/site-packages/jinja2/environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "/Users/peter/specter-desktop/src/cryptoadvance/specter/templates/wallet/history/addresses/wallet_addresses.jinja", line 18, in root
    width: auto;
  File "/Users/peter/specter-desktop/src/cryptoadvance/specter/templates/wallet/components/wallet_tab.jinja", line 14, in root
  File "/Users/peter/specter-desktop/src/cryptoadvance/specter/templates/base.jinja", line 71, in root
    document.addEventListener("notification", (e)=>{
  File "/Users/peter/specter-desktop/src/cryptoadvance/specter/templates/wallet/components/wallet_tab.jinja", line 47, in block_main
RuntimeError: generator raised StopIteration
```

**Comment by stepansnigirev** [comment]
@ben-kaufman I think you had ideas why it happened... Could you look into that?

**Comment by ben-kaufman** [comment]
Sure. I'll try to check it.

**Comment by ben-kaufman** [comment]
@Fonta1n3 , on which network did that happen to you (maninet/ testnet/ regtest), and is the node you are using pruned? Also, do you know about how many transactions you have in that wallet?

**Comment by Fonta1n3** [comment]
> @Fonta1n3 , on which network did that happen to you (maninet/ testnet/ regtest), and is the node you are using pruned? Also, do you know about how many transactions you have in that wallet?

Mainnet, worth mentioning i have all three networks running though.

Node is pruned. Less then 20 transactions.

**Comment by stepansnigirev** [comment]
What about the keypool size? I had similar issues when I imported 1000 keys...
You can check the keypool size in the wallet settings - how many addresses are watched

**Comment by Fonta1n3** [comment]
> What about the keypool size? I had similar issues when I imported 1000 keys...
> 
> You can check the keypool size in the wallet settings - how many addresses are watched

0, as its multisig keys can’t be added to the keypool.

**Comment by stepansnigirev** [comment]
sorry, I mean number of watched addresses.
<img width="874" alt="Screenshot 2020-07-16 at 16 29 33" src="https://user-images.githubusercontent.com/1706012/87683597-8e47cc00-c781-11ea-9d70-b4567da732e3.png">

**Comment by Fonta1n3** [comment]
> sorry, I mean number of watched addresses.
> 
> We should probably call it "address pool"
> 
> 
> 
> <img width="874" alt="Screenshot 2020-07-16 at 16 29 33" src="https://user-images.githubusercontent.com/1706012/87683597-8e47cc00-c781-11ea-9d70-b4567da732e3.png">
> 
> 

Ah, I’ll check in specter tomorrow and let you know.

**Comment by Fonta1n3** [comment]
<img width="933" alt="Screen Shot 2020-07-17 at 07 41 50" src="https://user-images.githubusercontent.com/30832395/87733029-15885480-c801-11ea-863f-0705bfcd7d08.png">

I am so used to thinking about things in terms of Fully Noded 😂, ignore my comments about 5,000 keys... I am using the same wallet on multiple nodes so got my wires crossed. FWIW I know the max address used is 14.

**Comment by ben-kaufman** [comment]
I think we found the source of the issue. Just to make sure, could you please try clicking on "Rebuild Cache" in the wallet settings screen (near the bottom) and see if it solves this crash and #239 ?

**Comment by Fonta1n3** [comment]
> I think we found the source of the issue. Just to make sure, could you please try clicking on "Rebuild Cache" in the wallet settings screen (near the bottom) and see if it solves this crash and #239 ?

Have tried multiple times and both issues persist, I also did a rescan just incase but it did not solve anything. 

Not sure if its relevant but I cloned the master branch and built from source (weird bc I am still getting the upgrade to 0.5.5 warning). Also I got these warnings when installing `requirements.txt`: 

```
ERROR: cryptoadvance-specter 0.1.0 has requirement Flask==1.1.1, but you'll have flask 1.1.2 which is incompatible.
ERROR: cryptoadvance-specter 0.1.0 has requirement hwi==1.1.0, but you'll have hwi 1.1.2 which is incompatible.
ERROR: cryptoadvance-specter 0.1.0 has requirement python-dotenv==0.10.3, but you'll have python-dotenv 0.13.0 which is incompatible.
ERROR: cryptoadvance-specter 0.1.0 has requirement requests==2.22.0, but you'll have requests 2.23.0 which is incompatible.
```

**Comment by stepansnigirev** [comment]
@k9ert should we move to `>=` in dependencies, why did we choose to use strict `==`?
