### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_rpc'

### ISSUE THREAD

**Issue by marssystems** [cryptoadvance/specter-desktop#2388]
version: v2.0.2
Traceback (most recent call last):
  File "flask\app.py", line 1523, in full_dispatch_request
  File "flask\app.py", line 1509, in dispatch_request
  File "flask_login\utils.py", line 290, in decorated_view
  File "cryptoadvance\specterext\spectrum\controller.py", line 174, in wallets_get
AttributeError: 'NoneType' object has no attribute 'get_rpc'

**Comment by k9ert** [comment]
Please check again with newest version 2.0.2. Sorry for the late reply.
