### ISSUE TITLE
Getting timeout error when creating hotwallet ... 

### ISSUE THREAD

**Issue by bmf7777** [cryptoadvance/specter-desktop#2411]
**Describe the bug**
when creating a hotwallet on my fullnode i get the error below ... directory is created with various files but the process doesn't successfully complete 

**To Reproduce**

**Expected behavior**

**Screenshots**
2024-01-22T20:05:47.215Z [info] : stderr-SPECTERD: ERROR in rpc: HTTPConnectionPool(host='192.168.3.7', port=8332): Read timed out. (read timeout=60.0)
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 466, in _make_request
  File "<string>", line 3, in raise_from
  File "urllib3/connectionpool.py", line 461, in _make_request
  File "http/client.py", line 1368, in getresponse
  File "http/client.py", line 317, in begin
  File "http/client.py", line 278, in _read_status
  File "socket.py", line 705, in readinto
TimeoutError: timed out

**Desktop (please complete the following information):**
 - Where is your node running: [e.g. raspiblitz, MyNode, umbrel, local(internal), local(external)] remove intel NUC with ubuntu 
 - Where is your specter running: [e.g. Raspiblitz, Node, umbrel, binary] binary 
 - If you're running a binary, which OS: [e.g. Linux, MacOs, Windows] MacOs
 - Browser [e.g. chrome, safari] firefox
 - Specter Version [e.g. 1.9.4] 2.0.2

**Additional context**

**Comment by k9ert** [comment]
@al-munazzim please create a PR for the timeout.
