### ISSUE TITLE
Server error: 'NoneType' object has no attribute 'stdout'

### ISSUE THREAD

**Issue by filipevalentim** [cryptoadvance/specter-desktop#2423]
version: v2.0.2
Traceback (most recent call last):
  File "socks.py", line 787, in connect
ConnectionRefusedError: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3\contrib\socks.py", line 96, in _new_conn
  File "socks.py", line 209, in create_connection
  File "socks.py", line 199, in create_connection
  File "socks.py", line 47, in wrapper
  File "socks.py", line 800, in connect
socks.ProxyConnectionError: Error connecting to SOCKS5 proxy localhost:9050: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 714, in urlopen
  File "urllib3\connectionpool.py", line 415, in _make_request
  File "urllib3\connection.py", line 244, in request
  File "http\client.py", line 1282, in request
  File "http\client.py", line 1328, in _send_request
  File "http\client.py", line 1277, in endheaders
  File "http\client.py", line 1037, in _send_output
  File "http\client.py", line 975, in send
  File "urllib3\connection.py", line 205, in connect
  File "urllib3\contrib\socks.py", line 127, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.contrib.socks.SOCKSConnection object at 0x000001FCAC546230>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 439, in send
  File "urllib3\connectionpool.py", line 798, in urlopen
  File "urllib3\util\retry.py", line 592, in increment
urllib3.exceptions.MaxRetryError: SOCKSHTTPConnectionPool(host='2gzyxa5ihm7nsggfxnu52rck2vv4rvmdlkiu3zzui5du4xyclen53wid.onion', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSConnection object at 0x000001FCAC546230>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cryptoadvance\specter\server_endpoints\settings.py", line 391, in tor
  File "requests\sessions.py", line 555, in get
  File "requests\sessions.py", line 542, in request
  File "requests\sessions.py", line 655, in send
  File "requests\adapters.py", line 516, in send
requests.exceptions.ConnectionError: SOCKSHTTPConnectionPool(host='2gzyxa5ihm7nsggfxnu52rck2vv4rvmdlkiu3zzui5du4xyclen53wid.onion', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSConnection object at 0x000001FCAC546230>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "flask\app.py", line 1523, in full_dispatch_request
  File "flask\app.py", line 1509, in dispatch_request
  File "flask_login\utils.py", line 290, in decorated_view
  File "cryptoadvance\specter\server_endpoints\settings.py", line 426, in tor
  File "cryptoadvance\specter\tor_daemon.py", line 51, in get_logs
AttributeError: 'NoneType' object has no attribute 'stdout'

**Comment by k9ert** [comment]
@al-munazzim please create a PR
