### ISSUE TITLE
Exception 'SpectrumNode' object has no attribute '_get_rpc'

### ISSUE THREAD

**Issue by revki** [cryptoadvance/specter-desktop#2436]
At login attempt I get above Server Error. Login not possible.

Details
version: v2.0.2
Traceback (most recent call last):
  File "flask/app.py", line 1523, in full_dispatch_request
  File "flask/app.py", line 1509, in dispatch_request
  File "cryptoadvance/specter/server_endpoints/auth.py", line 37, in login
  File "cryptoadvance/specter/server_endpoints/auth.py", line 84, in login_method_rpcpasswordaspin
AttributeError: 'SpectrumNode' object has no attribute '_get_rpc'

1. Start AppImage
2. Try to login
3. See error

I expect a normal login.

Node running on Raspiblitz. 
Spectrum addon activated in Specter
Debian
Chrome 
Specter 2.0.2

**Comment by al-munazzim** [comment]
**Triage Assessment**

**Status:** VALID-BUG — SpectrumNode missing `_get_rpc` method.

**Root cause:** The `login_method_rpcpasswordaspin` in `auth.py:84` calls `_get_rpc()` on the node object, but `SpectrumNode` (the Spectrum addon's node class) doesn't implement this method. This is likely a missing method/interface mismatch — `SpectrumNode` should either implement `_get_rpc()` or the login code should handle Spectrum nodes differently.

**Affected:** Any user running Spectrum addon (common on RaspiBlitz setups).

**Version:** v2.0.2 — this may already be fixed on master. Worth checking if `SpectrumNode` now has `_get_rpc()` or if the auth flow was updated.

**Severity:** Login blocker for Spectrum users — high impact.
