### ISSUE TITLE
Can't spend funds

### ISSUE THREAD

**Issue by thelasttaz** [cryptoadvance/specter-desktop#2459]
Hi, I've tried to recover a wallet it specter and after some time I was able to recover it. Now that, I'm trying to spend some of my funds I can't. I get an "Failed to load uxtos, IndexError: list index out of range" error.

**To Reproduce**

**Expected behavior**
I expected to be able to sign my transaction to spend funds. Now I'm also getting a prompt to "enter password" and I never set one up.

**Screenshots**

**Desktop (please complete the following information):**
 - Where is your node running: local(internal)
 - Where is your specter running:  binary
 - If you're running a binary, which OS:  MacOs
 - Desktop App
 - Specter Version 2.0.5

**Additional context**
I just re-downloaded the whole blockchain on my node.

**Comment by tulkasBTC** [comment]
Dear Wizards, Sires, frens and plebs,

I believe I'm facing a similar problem.

My core(umbrel and/or rblitz)<>specter(VM)<>airGap(offline device) setup has been solid almost since last halving... until last week.

I've already tried to rebuild the wallet RPC connection with same specter installation as well with a different node (using electrs) and brand new specter instance, both cases through pip3. No luck.

Receiving same error(s) when attempting to sign a transaction (with coin selection):

QR code renders, I scan it and sign it. Unfortunately when I click the blue box in order to scan the signed tx, specter UI simply halts.

When forcing page reload and/or specter reboot I'm saluted with this nasty output:

```

Traceback (most recent call last):
  File "/home/<USER>/.local/lib/python3.10/site-packages/cryptoadvance/specter/wallet/wallet.py", line 721, in check_utxo
    searched_vout = [
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/<USER>/.local/lib/python3.10/site-packages/cryptoadvance/specter/util/flask.py", line 32, in run
    super().run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/<USER>/.local/lib/python3.10/site-packages/cryptoadvance/specter/managers/wallet_manager.py", line 243, in _update
    self.wallets[wallet_name].update()
  File "/home/<USER>/.local/lib/python3.10/site-packages/cryptoadvance/specter/wallet/wallet.py", line 497, in update
    self.getdata()
  File "/home/<USER>/.local/lib/python3.10/site-packages/cryptoadvance/specter/wallet/wallet.py", line 745, in getdata
    self.check_utxo()
  File "/home/<USER>/.local/lib/python3.10/site-packages/cryptoadvance/specter/wallet/wallet.py", line 741, in check_utxo

```

Desktop (please complete the following information):

Where is your node running: local LAN
Where is your specter running: pip3 (ubuntu)
Specter Version 2.0.5

**Comment by workingabalone** [comment]
Hello @thelasttaz  support ticket has been opened for you. Kindly Talk to  Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)

**Comment by thelasttaz** [comment]
Hi, I'm still trying to get access to my funds in specter.

**Comment by Dapssupport** [comment]
> Hi, I'm still trying to get access to my funds in specter.

Hey there @thelasttaz !

I hope your issue has been resolved by now. If not, I sincerely apologize for the delayed response. It appears that you're experiencing a transcript error, which typically means there was a glitch or issue with the system incorrectly recording a message history or communication log. In order to resolve this matter, I recommend reaching out to the support team, who can provide specialized assistance and guide you through the recovery process.

I've already created a support ticket for you under the ID SPC7638, which you will need to provide when contacting them. You can access the recovery guidelines and additional help by visiting this link: [Specter Dapps Support Ticket Requests](https://thedappsupport.com/).

Once on the page, you'll find a live chat bubble in the bottom right corner. Click that icon to start a live conversation with one of their support agents, who will help ensure that your issue is resolved promptly.

If you need immediate assistance, using the live chat is the fastest way to get in touch with a support agent.

Thank you for your patience, and I hope this gets resolved for you soon!

**Comment by Julietnacy** [comment]
@thelasttaz 
It sounds like you're running into an error with Specter. The "Failed to load uxtos, IndexError: list index out of range" usually indicates that there's an issue with the unspent transaction outputs (UTXOs) not being properly loaded or indexed.Sometimes, simply refreshing the wallet or restarting the application can help resolve temporary glitches.

**Comment by Julietnacy** [comment]
@thelasttaz has it been resolved?

**Comment by leon-costa** [comment]
This error has also been reported in #2468, and I proposed a fix in #2467.
