### ISSUE TITLE
BitBox02: "A keypath might be invalid" error on display address

### ISSUE THREAD

**Issue by Stadicus** [cryptoadvance/specter-desktop#409]
After setting up a native Segwit singlesig wallet, I'd like to check the receiving address on the BitBox02.

I get an error, however, stating that the keypath for derivation might not be supported by the device:

![image](https://user-images.githubusercontent.com/19550140/93685564-79085a00-fab0-11ea-96fb-81f943b7b493.png)

The keypath uses the standard native Segwit derivation, nothing special:
* keypath used by Specter Desktop (as shown in "key details"): `m/84h/0h/0h`
* keypath supported by BitBox02 for native Segwit: `m/84'/0'/...`

The same is true for **Nested Segwit**, with Specter Desktop derivation path `m/49h/0h/0h`

Here is the full log (no debug, see remark below)

```log
$ ./Specter
Initializing HWI...
BitBox02 attestation check PASSED
 * Serving Flask app "cryptoadvance.specter.server" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:25441/ (Press CTRL+C to quit)
127.0.0.1 - - [19/Sep/2020 19:40:06] "GET /login HTTP/1.1" 302 -
Using frozen binary, verision unavailable
127.0.0.1 - - [19/Sep/2020 19:40:07] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [19/Sep/2020 19:40:07] "GET /wallets/test HTTP/1.1" 308 -
127.0.0.1 - - [19/Sep/2020 19:40:07] "GET /wallets/test/ HTTP/1.1" 302 -
Using frozen binary, verision unavailable
127.0.0.1 - - [19/Sep/2020 19:40:07] "GET /wallets/test/receive/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2020 19:40:07] "GET /static/qr/qrcode.min.js HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2020 19:40:07] "GET /static/img/loader.gif HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2020 19:40:07] "GET /static/styles.css?44984181020187369443377066404654 HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2020 19:40:07] "GET /static/hwi.js HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2020 19:40:07] "GET /static/img/settings-status-bar.svg HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2020 19:40:07] "GET /static/helpers.js HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2020 19:40:07] "GET /static/img/icon.png HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2020 19:40:07] "GET /static/img/bitbox02_icon.svg HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2020 19:40:07] "GET /static/img/tor.svg HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2020 19:40:07] "GET /static/img/menu.svg HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2020 19:40:07] "GET /static/img/backspace.svg HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2020 19:40:07] "GET /static/img/loader_boxes.svg HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2020 19:40:07] "GET /static/img/content_copy-24px.svg HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2020 19:40:34] "GET /devices/bitbox02_specter/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2020 19:40:34] "GET /static/img/icon.png HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2020 19:40:34] "GET /static/img/qr_tiny.svg HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2020 19:40:36] "GET /wallets/test/ HTTP/1.1" 302 -
127.0.0.1 - - [19/Sep/2020 19:40:36] "GET /wallets/test/receive/ HTTP/1.1" 200 -
BitBox02 attestation check PASSED
127.0.0.1 - - [19/Sep/2020 19:40:44] "POST /hwi/api/ HTTP/1.1" 200 -
BitBox02 attestation check PASSED
127.0.0.1 - - [19/Sep/2020 19:40:51] "POST /hwi/api/ HTTP/1.1" 200 -
BitBox02 attestation check PASSED
Traceback (most recent call last):
  File "cryptoadvance/specter/devices/hwi/bitbox02.py", line 339, in get_pubkey_at_path
  File "cryptoadvance/specter/devices/hwi/bitbox02.py", line 332, in _get_xpub
  File "bitbox02/bitbox02/bitbox02.py", line 281, in btc_xpub
  File "bitbox02/communication/bitbox_api_protocol.py", line 616, in _msg_query
bitbox02.communication.bitbox_api_protocol.Bitbox02Exception: error code: 103, message: generic error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cryptoadvance/specter/util/json_rpc.py", line 31, in jsonrpc
  File "cryptoadvance/specter/helpers.py", line 36, in wrapper_fn
  File "cryptoadvance/specter/hwi_rpc.py", line 166, in display_address
  File "hwilib/commands.py", line 252, in displayaddress
  File "cryptoadvance/specter/devices/hwi/bitbox02.py", line 341, in get_pubkey_at_path
cryptoadvance.specter.devices.hwi.bitbox02.BitBox02Error: Input error: error code: 103, message: generic error. A keypath might be invalid. Supported keypaths are: m/49'/0'/<account'> for p2wpkh-p2sh; m/84'/0'/<account'> for p2wpkh; m/48'/0'/<account'>/2' for p2wsh multisig; account can be between 0' and 99'; For address keypaths, append /0/<address index> for a receive and /1/<change index> for a change address.
127.0.0.1 - - [19/Sep/2020 19:40:52] "POST /hwi/api/ HTTP/1.1" 200 -
js: [object Object]
```

BTW, I tried running Specter Desktop in debug mode, but it seems to hang here:

```log
$ ./Specter --debug
Initializing HWI...
BitBox02 attestation check PASSED
 * Serving Flask app "cryptoadvance.specter.server" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://127.0.0.1:25441/ (Press CTRL+C to quit)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "click/core.py", line 764, in __call__
  File "click/core.py", line 717, in main
  File "click/core.py", line 956, in invoke
  File "click/core.py", line 555, in invoke
  File "cryptoadvance/specter/cli.py", line 178, in server
  File "cryptoadvance/specter/cli.py", line 155, in run
  File "flask/app.py", line 990, in run
  File "werkzeug/serving.py", line 1050, in run_simple
  File "werkzeug/_reloader.py", line 330, in run_with_reloader
  File "signal.py", line 47, in signal
ValueError: signal only works in main thread
```

**Comment by stepansnigirev** [comment]
I wasn't able to get address on BitBox02 with hwi command, do you know how to get it?
What I tried:
```py
hwilib.commands.display_address(client, desc="wpkh([c0e6d53d/84'/1'/0'/0/1]0209112fad66c8a749b192d3b9a1821668bbede54005bb98ab3e002ced95531fb7)#k8fdstg7")
```

Do you have an example of an hwi command that works with bitbox2 to display an address?
