### ISSUE TITLE
0.8.1 upper case address cause exception. 

### ISSUE THREAD

**Issue by warren-axiell** [cryptoadvance/specter-desktop#479]
I am getting exceptions "KeyError :  BC1....."   when trying to create a unsigned transaction.  If I lower case the address first it works fine. 

I am scanning from Samurai wallet.

**Comment by k9ert** [comment]
Copied from #499 which i'm now closing as a duplicate:


Samourai creates receiving-addresses QR-codes which are upper-case. Here is an example of a regtest-uppercase-address:

BCRT1QSQNUK9HULCFTA7KJ7687FAVJV66D5E9YY0LR7T

Sending to such an address will crash like this:
```
Traceback (most recent call last):
  File "/home/kim/src/specter-desktop/.env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kim/src/specter-desktop/.env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kim/src/specter-desktop/.env/lib/python3.8/site-packages/flask_login/utils.py", line 269, in decorated_view
    return func(*args, **kwargs)
  File "/home/kim/src/specter-desktop/src/cryptoadvance/specter/controller.py", line 1355, in wallet_sendnew
    return render_template(
  File "/home/kim/src/specter-desktop/.env/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/kim/src/specter-desktop/.env/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/kim/src/specter-desktop/.env/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/kim/src/specter-desktop/.env/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/kim/src/specter-desktop/.env/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/kim/src/specter-desktop/src/cryptoadvance/specter/templates/wallet/send/sign/wallet_send_sign_psbt.jinja", line 2, in top-level template code
    {% set tab = 'wallet_send' %}
  File "/home/kim/src/specter-desktop/src/cryptoadvance/specter/templates/wallet/components/wallet_tab.jinja", line 1, in top-level template code
    {% extends "base.jinja" %}
  File "/home/kim/src/specter-desktop/src/cryptoadvance/specter/templates/base.jinja", line 49, in top-level template code
    {% block main %}
  File "/home/kim/src/specter-desktop/src/cryptoadvance/specter/templates/wallet/components/wallet_tab.jinja", line 10, in block "main"
    {% block content %}
  File "/home/kim/src/specter-desktop/src/cryptoadvance/specter/templates/wallet/send/sign/wallet_send_sign_psbt.jinja", line 78, in block "content"
    {{ explorer_link('address', psbt['address'][i], wallet.get_address_name(psbt["address"][i], -1), specter.explorer) }}
  File "/home/kim/src/specter-desktop/src/cryptoadvance/specter/wallet.py", line 827, in get_address_name
    if self.getlabel(address) == address and addr_idx > -1:
  File "/home/kim/src/specter-desktop/src/cryptoadvance/specter/wallet.py", line 795, in getlabel
    return self.getlabels([address])[address]
KeyError: 'BCRT1QSQNUK9HULCFTA7KJ7687FAVJV66D5E9YY0LR7T'
```

The bad thing about this is that the psbt can't get deleted via http://localhost:25441/wallets/mywallet/send/pending/ as this will also result in this exception.
Here is a reasonable workaround to get the wallet working again:
```
# log into the computer where specter is running
export WRONG_ADDRESS="BCRT1QSQNUK9HULCFTA7KJ7687FAVJV66D5E9YY0LR7T"
export CORRECT_ADDRESS=$(echo "$WRONG_ADDRESS" | tr '[:upper:]' '[:lower:]')
# find the buggy wallet somewhere here:
cd ~/.specter/wallets/
# or, if you're a user called alice on the system:
cd ~/.specter/wallets_alice
# this is probably for mainnet, so:
cd main
sed -i "s/$WRONG_ADDRESS/$CORRECT_ADDRESS/g" thebuggywallet.json
```
After that, it should be solved. Better delete the transaction anc create it a new. 
```
$ echo "BCRT1QSQNUK9HULCFTA7KJ7687FAVJV66D5E9YY0LR7T" | tr '[:upper:]' '[:lower:]'
bcrt1qsqnuk9hulcfta7kj7687favjv66d5e9yy0lr7t
```
Then remove the uppercase address and insert the lowercase one.
