### ISSUE TITLE
Error when rescanning blockchain during New Wallet creation

### ISSUE THREAD

**Issue by KISBITCOIN** [cryptoadvance/specter-desktop#517]
I get this error message during new wallet creation after Specter has taken a bunch of time scanning blockchain for my TXN history. This is on desktop specter, on Mac OS Catalina, connecting to a remote instance of Bitcoin Core unprunned.

```
Exception: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

Details:
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 426, in _make_request
  File "", line 3, in raise_from
  File "urllib3/connectionpool.py", line 421, in _make_request
  File "http/client.py", line 1336, in getresponse
  File "http/client.py", line 306, in begin
  File "http/client.py", line 275, in _read_status
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 449, in send
  File "urllib3/connectionpool.py", line 727, in urlopen
  File "urllib3/util/retry.py", line 403, in increment
  File "urllib3/packages/six.py", line 734, in reraise
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 426, in _make_request
  File "", line 3, in raise_from
  File "urllib3/connectionpool.py", line 421, in _make_request
  File "http/client.py", line 1336, in getresponse
  File "http/client.py", line 306, in begin
  File "http/client.py", line 275, in _read_status
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "flask/app.py", line 1950, in full_dispatch_request
  File "flask/app.py", line 1936, in dispatch_request
  File "flask_login/utils.py", line 269, in decorated_view
  File "cryptoadvance/specter/controller.py", line 996, in new_wallet
  File "cryptoadvance/specter/wallet.py", line 729, in keypoolrefill
  File "cryptoadvance/specter/wallet.py", line 729, in 
  File "cryptoadvance/specter/wallet.py", line 637, in get_address
  File "cryptoadvance/specter/rpc.py", line 313, in fn
  File "cryptoadvance/specter/rpc.py", line 301, in multi
  File "requests/sessions.py", line 578, in post
  File "requests/sessions.py", line 530, in request
  File "requests/sessions.py", line 643, in send
  File "requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

```

**Comment by ben-kaufman** [comment]
Hi, is this still happening with version v0.10.2?

**Comment by ben-kaufman** [comment]
Closing for now due to inactivity. Please reopen if this is still active.
