### ISSUE TITLE
Server error: Exception: 'dict object' has no attribute 'size_on_disk'

### ISSUE THREAD

**Issue by bit-the-dust** [cryptoadvance/specter-desktop#538]
Core  v0.15.0.1 (64-bit) on Windows 7 is configured as below and running status is "Processing blocks on disk" (17 weeks behind)

# Prune blocks to 10,000 MB

prune=10000

server=1
rpcuser=specter
rpcpassword=xxxxxx

Testing the connection in Specter with these credentials I got this server error with stack trace.

Secondly there is no way to close this error without closing the application.

Traceback (most recent call last):
  File "flask\app.py", line 1950, in full_dispatch_request
  File "flask\app.py", line 1936, in dispatch_request
  File "flask_login\utils.py", line 269, in decorated_view
  File "cryptoadvance\specter\controller.py", line 602, in bitcoin_core_settings
  File "flask\templating.py", line 140, in render_template
  File "flask\templating.py", line 120, in _render
  File "jinja2\environment.py", line 1090, in render
  File "jinja2\environment.py", line 832, in handle_exception
  File "jinja2\_compat.py", line 28, in reraise
  File "C:\Users\User Name\AppData\Local\Programs\SpecterDesktop\templates\settings\bitcoin_core_settings.jinja", line 1, in top-level template code
    {% extends "base.jinja" %}
  File "C:\Users\User Name\AppData\Local\Programs\SpecterDesktop\templates\base.jinja", line 17, in top-level template code
    {% block sidebar %}
  File "C:\Users\User Name\AppData\Local\Programs\SpecterDesktop\templates\base.jinja", line 18, in block "sidebar"
    {% include "includes/sidebar/sidebar.jinja" %}
  File "C:\Users\User Name\AppData\Local\Programs\SpecterDesktop\templates\includes\sidebar\sidebar.jinja", line 30, in top-level template code
    {% include "includes/sidebar/components/bitcoin_core_info.jinja" %}
  File "C:\Users\User Name\AppData\Local\Programs\SpecterDesktop\templates\includes\sidebar\components\bitcoin_core_info.jinja", line 16, in top-level template code
     Size on disk: {{specter.info['size_on_disk']|bytessize }} 
  File "cryptoadvance\specter\controller.py", line 1777, in bytessize
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'size_on_disk'

**Comment by bit-the-dust** [comment]
After this error re-opening the app or the browser UI just shows the same error.

Before this error the main UI showed correctly in the app.

**Comment by stepansnigirev** [comment]
Core version 15???? We support 0.19+ and plan to drop support for 0.19 and do only 0.20+ soon.
Please upgrade your full node :)

**Comment by bit-the-dust** [comment]
That's fine, thanks Stephan :-) I thought that might be the problem. I didn't see the system requirements stated anywhere, sorry if I missed it. I'd be happy to close this case if we could make the requirements more obvious.

Thanks

**Comment by stepansnigirev** [comment]
Added min Core version here
https://github.com/cryptoadvance/specter-desktop/commit/a0d7013654e1023770c14686db59e54b5eb7e627
