### ISSUE TITLE
Server error when creating wallet

### ISSUE THREAD

**Issue by bektar** [cryptoadvance/specter-desktop#540]
I'm getting the following error (most of the time) when creating a new wallet:

```
Server error!

Exception: Could not find 'pubkeys' in address info: { "address": "bc1qpjxe0qghz4r4077l806yun7txqj0jkdpyzz0celdtk6crgpzhq0srhs5r2", "scriptPubKey": "00200c8d978117154757fbdf3bf44e4fcb3024f959a12084fc67ed5db581a022b81f", "ismine": false, "solvable": false, "iswatchonly": false, "isscript": true, "iswitness": true, "witness_version": 0, "witness_program": "0c8d978117154757fbdf3bf44e4fcb3024f959a12084fc67ed5db581a022b81f", "ischange": false, "labels": [] }

Details:
Traceback (most recent call last):
  File "flask/app.py", line 1950, in full_dispatch_request
  File "flask/app.py", line 1936, in dispatch_request
  File "flask_login/utils.py", line 269, in decorated_view
  File "cryptoadvance/specter/controller.py", line 1219, in wallet_receive
  File "flask/templating.py", line 140, in render_template
  File "flask/templating.py", line 120, in _render
  File "jinja2/environment.py", line 1090, in render
  File "jinja2/environment.py", line 832, in handle_exception
  File "jinja2/_compat.py", line 28, in reraise
  File "/Users/jakob/Desktop/Specter.app/Contents/MacOS/templates/wallet/receive/wallet_receive.jinja", line 2, in top-level template code
    {% set tab = 'wallet_receive' %}
  File "/Users/jakob/Desktop/Specter.app/Contents/MacOS/templates/wallet/components/wallet_tab.jinja", line 1, in top-level template code
    {% extends "base.jinja" %}
  File "/Users/jakob/Desktop/Specter.app/Contents/MacOS/templates/base.jinja", line 49, in top-level template code
    {% block main %}
  File "/Users/jakob/Desktop/Specter.app/Contents/MacOS/templates/wallet/components/wallet_tab.jinja", line 10, in block "main"
    {% block content %}
  File "/Users/jakob/Desktop/Specter.app/Contents/MacOS/templates/wallet/receive/wallet_receive.jinja", line 72, in block "content"
    Display address on device


  File "cryptoadvance/specter/wallet.py", line 660, in get_descriptor
  File "cryptoadvance/specter/helpers.py", line 248, in sort_descriptor
Exception: Could not find 'pubkeys' in address info:
{
  "address": "bc1qpjxe0qghz4r4077l806yun7txqj0jkdpyzz0celdtk6crgpzhq0srhs5r2",
  "scriptPubKey": "00200c8d978117154757fbdf3bf44e4fcb3024f959a12084fc67ed5db581a022b81f",
  "ismine": false,
  "solvable": false,
  "iswatchonly": false,
  "isscript": true,
  "iswitness": true,
  "witness_version": 0,
  "witness_program": "0c8d978117154757fbdf3bf44e4fcb3024f959a12084fc67ed5db581a022b81f",
  "ischange": false,
  "labels": []
}
```

This is using v0.8.2-pre1 on macOS 10.17.7. I say most of the time since about one in four tries seem to work (after deleting ~/.specter/wallets)

**Comment by ben-kaufman** [comment]
Hi, this is a known bug that was introduced on `v0.8.2-pre1` and already fixed. So for now, it is recommended not to use `v0.8.2-pre1` since it is a pre-release with known issues. It is recommended to still use `v0.8.1` for now.

**Comment by bektar** [comment]
Oh, good thing it's fixed! Didn't see it when looking through the issues. I'll look harder next time.
