### ISSUE TITLE
AppImage crash when starting when ~/.specter directory is missing

### ISSUE THREAD

**Issue by dmp1ce** [cryptoadvance/specter-desktop#568]
Before running `specterd`, if the AppImage is application is run then I get the following error.
```
$ ./dist/Specter-0.8.2-pre3.AppImage 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module '/home/david/.specter/app_settings.json'
Require stack:
- /tmp/.mount_SpecteZaUHar/resources/app.asar/helpers.js
- /tmp/.mount_SpecteZaUHar/resources/app.asar/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:961:15)
    at Function.o._resolveFilename (electron/js2c/browser_init.js:257:919)
    at Module._load (internal/modules/cjs/loader.js:844:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at getAppSettings (/tmp/.mount_SpecteZaUHar/resources/app.asar/helpers.js:33:23)
    at Object.<anonymous> (/tmp/.mount_SpecteZaUHar/resources/app.asar/main.js:13:19)
    at Module._compile (internal/modules/cjs/loader.js:1145:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1166:10)
```

`specterd` creates the `~./specter` directory which avoids this error.

I had to first apply a few changes from the #567 PR in order to be able to build on Arch Linux.

I would expect that the AppImage could work without needing to run `specterd` first or manually create the `~/.specter` files. I built with `./build-unix.sh v0.8.2-pre3 make-hash`.

**Comment by ben-kaufman** [comment]
Thanks for reporting. Fixed with #560
