### ISSUE TITLE
Import using multiline seed list on v0.8.1

### ISSUE THREAD

**Issue by shawnyeager** [cryptoadvance/specter-desktop#570]
I'm seeing this after attempting to import a wallet using one seed word per line:

```
Traceback (most recent call last):
  File "/home/bitcoin/.specter/.env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bitcoin/.specter/.env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/bitcoin/.specter/.env/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/bitcoin/.specter/.env/lib/python3.7/site-packages/cryptoadvance/specter/controller.py", line 767, in new_wallet
    wallet_data = json.loads(request.form["wallet_data"].replace("'", "h"))
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
<img width="819" alt="Screen Shot 2020-11-01 at 1 07 21 PM" src="https://user-images.githubusercontent.com/980297/97811908-32775500-1c43-11eb-9f52-3128b4c900aa.png">

**Comment by shawnyeager** [comment]
Actually, I just tried it using a single line with spaces, and see the same error. 24-word seed phrase.

**Comment by ben-kaufman** [comment]
Hi, you are trying to import in the new wallet screen I believe right?

The issue then is that this is not the right place for importing a hot wallet. The way you should do that is to click on the Add New Device button in the left sidebar, select Bitcoin Core hot wallet, and there select the import tab and enter the seed.
After you added it as a device you can just use that to create a wallet in the Add wallet screen by creating a single sig wallet from it (or using it in a multisig setup).

Maybe it would be nice to also allow seed import from the import wallet screen though, or at least we should probably clarify it better...

**Comment by shawnyeager** [comment]
I was. Thanks, @ben-kaufman. I hadn't picked up that device precedes wallet. It makes sense in hindsight, but perhaps UI/flow could clarify.

**Comment by k9ert** [comment]
Hot Wallets are deprecated and caused more trouble than solved problems for people. So closing this.
