### ISSUE TITLE
Server error!

### ISSUE THREAD

**Issue by gongyj0948** [cryptoadvance/specter-desktop#590]
I was trying to connect Specter Desktop with mynode server. 

# Whitelist Specter domain name ( https://mynode.local:25441/ ) here.

it returns this:

**Server error!**

Exception: 405 Method Not Allowed: The method is not allowed for the requested URL.

Traceback (most recent call last):
  File "/opt/mynode/specter/env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/mynode/specter/env/lib/python3.7/site-packages/flask/app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "/opt/mynode/specter/env/lib/python3.7/site-packages/flask/app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "/opt/mynode/specter/env/lib/python3.7/site-packages/flask/ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "/opt/mynode/specter/env/lib/python3.7/site-packages/werkzeug/routing.py", line 1940, in match
    raise MethodNotAllowed(valid_methods=list(have_match_for))
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.

**Comment by stepansnigirev** [comment]
Sorry for the long time to response...
Can you specify what exactly you do?
What did you put in the HWI url?
maybe a screenshot of this page?

**Comment by gongyj0948** [comment]
Sorry, it has been so long, I forgot the problem. But I switched to Umbrel and it's working fine.

**Comment by stepansnigirev** [comment]
Sorry... we were a bit overwhelmed with issues recently :(
