### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by statusquont** [cryptoadvance/specter-desktop#608]
While a newly added Coldcard wallet was scanning it was roughly ~60% complete when:

```
Server error!
Exception: HTTPConnectionPool(host='192.168.1.46', port=8332): Max retries exceeded with url: /wallet/specterff56ef0cd7fd8102%5Ccoldcard (Caused by NewConnectionError(': Failed to establish a new connection: [WinError 10051] A socket operation was attempted to an unreachable network'))


Back to the main page

Details:
Traceback (most recent call last):
  File "urllib3\connection.py", line 160, in _new_conn
  File "urllib3\util\connection.py", line 84, in create_connection
  File "urllib3\util\connection.py", line 74, in create_connection
OSError: [WinError 10051] A socket operation was attempted to an unreachable network

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 677, in urlopen
  File "urllib3\connectionpool.py", line 392, in _make_request
  File "http\client.py", line 1277, in request
  File "http\client.py", line 1323, in _send_request
  File "http\client.py", line 1272, in endheaders
  File "http\client.py", line 1032, in _send_output
  File "http\client.py", line 972, in send
  File "urllib3\connection.py", line 187, in connect
  File "urllib3\connection.py", line 172, in _new_conn
urllib3.exceptions.NewConnectionError: : Failed to establish a new connection: [WinError 10051] A socket operation was attempted to an unreachable network

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 449, in send
  File "urllib3\connectionpool.py", line 727, in urlopen
  File "urllib3\util\retry.py", line 439, in increment
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='192.168.1.46', port=8332): Max retries exceeded with url: /wallet/specterff56ef0cd7fd8102%5Ccoldcard (Caused by NewConnectionError(': Failed to establish a new connection: [WinError 10051] A socket operation was attempted to an unreachable network'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "flask\app.py", line 1950, in full_dispatch_request
  File "flask\app.py", line 1936, in dispatch_request
  File "flask_login\utils.py", line 269, in decorated_view
  File "cryptoadvance\specter\controller.py", line 1534, in wallet_settings
  File "flask\templating.py", line 140, in render_template
  File "flask\templating.py", line 120, in _render
  File "jinja2\environment.py", line 1090, in render
  File "jinja2\environment.py", line 832, in handle_exception
  File "jinja2\_compat.py", line 28, in reraise
  File "C:\Users\HUMANB~1\AppData\Local\Temp\_MEI44882\templates\wallet\settings\wallet_settings.jinja", line 2, in top-level template code
    {% set tab = 'wallet_settings' %}
  File "C:\Users\HUMANB~1\AppData\Local\Temp\_MEI44882\templates\wallet\components\wallet_tab.jinja", line 1, in top-level template code
    {% extends "base.jinja" %}
  File "C:\Users\HUMANB~1\AppData\Local\Temp\_MEI44882\templates\base.jinja", line 50, in top-level template code
    {% block main %}
  File "C:\Users\HUMANB~1\AppData\Local\Temp\_MEI44882\templates\wallet\components\wallet_tab.jinja", line 10, in block "main"
    {% block content %}
  File "C:\Users\HUMANB~1\AppData\Local\Temp\_MEI44882\templates\wallet\settings\wallet_settings.jinja", line 197, in block "content"
    {% include "wallet/settings/components/export_wallet_account_map.jinja" %}
  File "C:\Users\HUMANB~1\AppData\Local\Temp\_MEI44882\templates\wallet\settings\components\export_wallet_account_map.jinja", line 5, in top-level template code
    
  File "jinja2\environment.py", line 471, in getattr
  File "cryptoadvance\specter\wallet.py", line 613, in account_map
  File "cryptoadvance\specter\wallet.py", line 585, in blockheight
  File "cryptoadvance\specter\rpc.py", line 308, in fn
  File "cryptoadvance\specter\rpc.py", line 296, in multi
  File "requests\sessions.py", line 578, in post
  File "requests\sessions.py", line 530, in request
  File "requests\sessions.py", line 643, in send
  File "requests\adapters.py", line 516, in send
requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.1.46', port=8332): Max retries exceeded with url: /wallet/specterff56ef0cd7fd8102%5Ccoldcard (Caused by NewConnectionError(': Failed to establish a new connection: [WinError 10051] A socket operation was attempted to an unreachable network'))
```

**Comment by ben-kaufman** [comment]
Hi, did that happen only one or every time you try to rescan/ do something else?

**Comment by statusquont** [comment]
So far, only once. I'll update this issue if I see it again.

**Comment by stepansnigirev** [comment]
When wallets are rescanning RPC becomes pretty slow. So it's easy to hit the rpc request limit especially if other software is also talking to Bitcoin Core.
Hopefully will be fixed in the next release when we reduce RPC load.

**Comment by stepansnigirev** [comment]
https://github.com/cryptoadvance/specter-desktop/pull/631 and https://github.com/cryptoadvance/specter-desktop/pull/588 removed a lot of load from RPC, so now it should be much better.
I will close this issue, please reopen if it happens again.
