### ISSUE TITLE
UTXO tab in v0.10.0 under raspiblitz 1.6.1

### ISSUE THREAD

**Issue by shawnyeager** [cryptoadvance/specter-desktop#669]
I've just upgraded, and now when I attempt to list my utxos, I see an error page with the following:

```
Server error!
Exception: no filter named 'altunit'
```
```
Traceback (most recent call last):
  File "/home/bitcoin/.specter/.env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bitcoin/.specter/.env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/bitcoin/.specter/.env/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/bitcoin/.specter/.env/lib/python3.7/site-packages/cryptoadvance/specter/controller.py", line 1143, in wallet_tx_utxo
    is_testnet(app.specter.chain),
  File "/home/bitcoin/.specter/.env/lib/python3.7/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/bitcoin/.specter/.env/lib/python3.7/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/bitcoin/.specter/.env/lib/python3.7/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/bitcoin/.specter/.env/lib/python3.7/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/bitcoin/.specter/.env/lib/python3.7/site-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/home/bitcoin/.specter/.env/lib/python3.7/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/bitcoin/.specter/.env/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/bitcoin/.specter/.env/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/bitcoin/.specter/.env/lib/python3.7/site-packages/cryptoadvance/specter/templates/wallet/history/utxo/wallet_utxo.jinja", line 99, in template
     ({{ balance | altunit }})
jinja2.exceptions.TemplateAssertionError: no filter named 'altunit'
```

**Comment by stepansnigirev** [comment]
Did you restart Specter after upgrading?

**Comment by shawnyeager** [comment]
I had not. That seems to have fixed everything. Sorry if I missed that instruction somewhere. Thanks.
