### ISSUE TITLE
/settings/general errors in v0.10.0 under raspiblitz v1.6.1

### ISSUE THREAD

**Issue by shawnyeager** [cryptoadvance/specter-desktop#671]
Accessing Settings —> General using the gear button displays:

```
Server error!
Exception: Could not build url for endpoint 'backup_file'. Did you mean 'wallet' instead?
```
```
Traceback (most recent call last):
  File "/home/bitcoin/.specter/.env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bitcoin/.specter/.env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/bitcoin/.specter/.env/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/bitcoin/.specter/.env/lib/python3.7/site-packages/cryptoadvance/specter/controller.py", line 488, in general_settings
    if "blockheight" in wallet
  File "/home/bitcoin/.specter/.env/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/bitcoin/.specter/.env/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/bitcoin/.specter/.env/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/bitcoin/.specter/.env/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/bitcoin/.specter/.env/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/bitcoin/.specter/.env/lib/python3.7/site-packages/cryptoadvance/specter/templates/settings/general_settings.jinja", line 1, in top-level template code
    {% extends "base.jinja" %}
  File "/home/bitcoin/.specter/.env/lib/python3.7/site-packages/cryptoadvance/specter/templates/base.jinja", line 50, in top-level template code
    {% with messages = get_flashed_messages(with_categories=True) %}
  File "/home/bitcoin/.specter/.env/lib/python3.7/site-packages/cryptoadvance/specter/templates/settings/general_settings.jinja", line 22, in block "main"
```
Then this button (which doesn't work):
```
Download Specter backup files
```
Then this:
```
File "/home/bitcoin/.specter/.env/lib/python3.7/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/bitcoin/.specter/.env/lib/python3.7/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/bitcoin/.specter/.env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/bitcoin/.specter/.env/lib/python3.7/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/home/bitcoin/.specter/.env/lib/python3.7/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'backup_file'. Did you mean 'wallet' instead?
```

**Comment by stepansnigirev** [comment]
Please restart Specter

**Comment by shawnyeager** [comment]
Done. Problem resolved. Thanks.
