### ISSUE TITLE
Exception: 'str' object has no attribute 'getreceivedbyaddress'

### ISSUE THREAD

**Issue by pxsocs** [cryptoadvance/specter-desktop#690]
After upgrading to the recent version, the following messages keep coming back. Restarting the server solves the issue but it returns after a few page calls. 

`Exception: 'str' object has no attribute 'getreceivedbyaddress'`

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/<removed>/Library/Python/3.7/lib/python/site-packages/cryptoadvance/specter/controller.py", line 1261, in wallet_receive
    wallet.check_unused()
  File "/Users/<removed>/Library/Python/3.7/lib/python/site-packages/cryptoadvance/specter/wallet.py", line 164, in check_unused
    while self.rpc.getreceivedbyaddress(addr, 0) != 0:
AttributeError: 'str' object has no attribute 'getreceivedbyaddress'
```

__Edit__
This may have something to do with having two sessions running in two different computers. Since closing the other session, it seems to be stable.

**Comment by stepansnigirev** [comment]
By two different sessions you mean that you have Specter running on the node and opened two apps connected to a remote Specter? Or did you use a browser?

**Comment by pxsocs** [comment]
Actually, one Browser and one app making a request to get transactions using the following authorization code. This is still failing after a couple of requests and returning the error above. 

```python
    session = requests.Session()
    # First post login info into session to authenticate
    data = {
        'username': username,
        'password': password
    }
    if password:
        try:
            session.post(url+'/login', data=data)
        except Exception:
            return("ConnectionError")
```

**Comment by pxsocs** [comment]
This issue has not happened again so closing it
