### ISSUE TITLE
running specter as a daemon seems to have broken in 0.10.3 and 0.10.4

### ISSUE THREAD

**Issue by riannom** [cryptoadvance/specter-desktop#757]
running specter as a daemon seems to have broken in 0.10.3 and 0.10.4.  it works fine when i downgrade back to 0.10.2.  tested this on two installations.

python3 -m cryptoadvance.specter server --daemon
Initializing HWI...
[2020-12-06 11:13:26,484] INFO in cli_server: Logging is hopefully configured
[2020-12-06 11:13:26,489] INFO in server: Initializing LoginManager
[2020-12-06 11:13:26,489] INFO in server: Initializing Specter
[2020-12-06 11:13:26,491] INFO in checker: Checker health Checking every 600 seconds now
[2020-12-06 11:13:26,491] INFO in checker: Checker health started with period 600
[2020-12-06 11:13:26,492] INFO in checker: Checker price Checking every 600 seconds now
[2020-12-06 11:13:26,493] INFO in checker: Checker health Checking every 20 seconds now
[2020-12-06 11:13:26,494] INFO in checker: Checker executed within 0.002 seconds. This message won't show again until stopped and started.
[2020-12-06 11:13:26,498] INFO in server: Login disabled
[2020-12-06 11:13:26,499] INFO in server: Initializing Controller ...
Starting server in background...
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pi/.local/lib/python3.7/site-packages/cryptoadvance/specter/__main__.py", line 19, in <module>
    entry_point()
  File "/home/pi/.local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/pi/.local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pi/.local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pi/.local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/cryptoadvance/specter/cli/cli_server.py", line 224, in server
    print(" * Hopefully running on %s://%s:%d/" % (protocol, host, port))
TypeError: %d format: a number is required, not NoneType

**Comment by stepansnigirev** [comment]
I'd recommend setting up specter as a systemd service, see docs [here](https://github.com/cryptoadvance/specter-desktop/blob/master/docs/daemon.md).
Daemon mode is a bit buggy and we are thinking about removing it at some point.

**Comment by riannom** [comment]
Thank you for the quick response!  will do exactly that, thanks!
