### ISSUE TITLE
Server error! Exception: Request error: Can't read block from disk

### ISSUE THREAD

**Issue by ChikinCurry** [cryptoadvance/specter-desktop#770]
Getting this error when clicking on the Wallet Overview section.

Details:

Traceback (most recent call last):
  File "flask/app.py", line 1950, in full_dispatch_request
  File "flask/app.py", line 1936, in dispatch_request
  File "flask_login/utils.py", line 272, in decorated_view
  File "cryptoadvance/specter/controller.py", line 1055, in wallets_overview
  File "flask/templating.py", line 140, in render_template
  File "flask/templating.py", line 120, in _render
  File "jinja2/environment.py", line 1090, in render
  File "jinja2/environment.py", line 832, in handle_exception
  File "jinja2/_compat.py", line 28, in reraise
  File "/var/folders/0_/mkc_pv0j58s06m4bt32pq3qw0000gn/T/_MEIaZq6kN/templates/wallet/wallets_overview.jinja", line 1, in top-level template code
    {% extends "base.jinja" %}
  File "/var/folders/0_/mkc_pv0j58s06m4bt32pq3qw0000gn/T/_MEIaZq6kN/templates/base.jinja", line 62, in top-level template code
    {% block main %}
  File "/var/folders/0_/mkc_pv0j58s06m4bt32pq3qw0000gn/T/_MEIaZq6kN/templates/wallet/wallets_overview.jinja", line 41, in block "main"
    {% set transactions = specter.wallet_manager.full_txlist(idx, validate_merkle_proofs) %}
  File "cryptoadvance/specter/wallet_manager.py", line 288, in full_txlist
  File "cryptoadvance/specter/wallet_manager.py", line 288, in 
  File "cryptoadvance/specter/wallet.py", line 521, in txlist
  File "cryptoadvance/specter/rpc.py", line 313, in fn
cryptoadvance.specter.rpc.RpcError: Request error: Can't read block from disk

**Comment by k9ert** [comment]
This looks like an data-corruption-issue on the Bitcoin-Core side. Can you check whether your Bitcoin-Core is healthy?

**Comment by ChikinCurry** [comment]
How do I verify that it's healthy? I'm using a pruned node & the Bitcoin Core client seems to be running fine.

**Comment by ChikinCurry** [comment]
For some reason now I'm getting the same error immediately after logging onto Specter. My Bitcoin-Core client is able to sync up and update. Not sure how to troubleshoot here.

**Comment by k9ert** [comment]
This clearly points to an issue on the Core-side. At least, please rule out that you have an issue there by using the btc-cli (wallets) for your specific wallet.

**Comment by ChikinCurry** [comment]
Yeah, I'm not sure what happened exactly but it's finally resolved now.  I tried a -reindex at first which didn't work (still got the same error in Specter). But completely resyncing my Core from scratch did the trick here.
