### ISSUE TITLE
"Server error!" When trying to import coordinator setup from Blue wallet animated QR

### ISSUE THREAD

**Issue by Transisto** [cryptoadvance/specter-desktop#793]
![image](https://user-images.githubusercontent.com/388716/102844997-95cb6b00-43da-11eb-8b66-9fbb99475745.png)

Details:
Traceback (most recent call last):
  File "/opt/mynode/specter/env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/mynode/specter/env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/mynode/specter/env/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/opt/mynode/specter/env/lib/python3.7/site-packages/cryptoadvance/specter/server_endpoints/wallets.py", line 88, in new_wallet
    wallet_data = json.loads(request.form["wallet_data"].replace("'", "h"))
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Transisto** [comment]
![image](https://user-images.githubusercontent.com/388716/102845142-e216ab00-43da-11eb-9ec6-15056a6bdad1.png)

**Comment by k9ert** [comment]
I don't think that this is supported. Ben is writing in the chat (Dec 20, 16:58)

> They don’t support export to specter, only import from it...
