### ISSUE TITLE
Server Error on Wallet Settings page when key used in multisig was deleted

### ISSUE THREAD

**Issue by rahlmer1** [cryptoadvance/specter-desktop#822]
Exception: list index out of range

I tried deleting wallet.dat and restarting the node but the error persists.

Traceback (most recent call last):
  File "/opt/mynode/specter/env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/mynode/specter/env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/mynode/specter/env/lib/python3.7/site-packages/flask_login/utils.py", line 269, in decorated_view
    return func(*args, **kwargs)
  File "/opt/mynode/specter/env/lib/python3.7/site-packages/cryptoadvance/specter/server_endpoints/wallets.py", line 884, in settings
    error=error,
  File "/opt/mynode/specter/env/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/opt/mynode/specter/env/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/opt/mynode/specter/env/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/opt/mynode/specter/env/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/opt/mynode/specter/env/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/opt/mynode/specter/env/lib/python3.7/site-packages/cryptoadvance/specter/templates/wallet/settings/wallet_settings.jinja", line 2, in top-level template code
    {% set tab = 'settings' %}
  File "/opt/mynode/specter/env/lib/python3.7/site-packages/cryptoadvance/specter/templates/wallet/components/wallet_tab.jinja", line 1, in top-level template code
    {% extends "base.jinja" %}
  File "/opt/mynode/specter/env/lib/python3.7/site-packages/cryptoadvance/specter/templates/base.jinja", line 60, in top-level template code
    {% block main %}
  File "/opt/mynode/specter/env/lib/python3.7/site-packages/cryptoadvance/specter/templates/wallet/components/wallet_tab.jinja", line 10, in block "main"
    {% block content %}
  File "/opt/mynode/specter/env/lib/python3.7/site-packages/cryptoadvance/specter/templates/wallet/settings/wallet_settings.jinja", line 144, in block "content"
    {% include "wallet/settings/components/export_wallet_account_map.jinja" %}
  File "/opt/mynode/specter/env/lib/python3.7/site-packages/cryptoadvance/specter/templates/wallet/settings/components/export_wallet_account_map.jinja", line 30, in top-level template code
    document.getElementById('electrum_export').href = 'data:text/plain,' + encodeURIComponent('{{ wallet.get_electrum_file()|tojson }}');
  File "/opt/mynode/specter/env/lib/python3.7/site-packages/cryptoadvance/specter/wallet.py", line 845, in get_electrum_file
    key = [key for key in device.keys if key in self.keys][0]
IndexError: list index out of range

**Comment by ben-kaufman** [comment]
Hi, did you delete a device file manually from the Specter data folder?

Which Specter version are you using?

**Comment by rahlmer1** [comment]
I’m using 10.4.

I removed a key from one of the devices in my multisig.  I should have deleted the wallet first but I didn’t.  Now I’m not able to get into the settings tab to delete it.

**Comment by ben-kaufman** [comment]
Ok thanks. I understand the issue now, will fix it.
