### ISSUE TITLE
Add an xpub from bisq is crash the server

### ISSUE THREAD

**Issue by zsoltmoravcsik** [cryptoadvance/specter-desktop#841]
I added my bisq wallet to the device and I want to add that to the wallet as well, then I got a server 500 error with Work queue depth exceeded message. This is the trace:
```
Traceback (most recent call last):
  File "/home/specter/.env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/specter/.env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/specter/.env/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/specter/.env/lib/python3.7/site-packages/cryptoadvance/specter/server_endpoints/wallets.py", line 520, in receive
    wallet.check_unused()
  File "/home/specter/.env/lib/python3.7/site-packages/cryptoadvance/specter/wallet.py", line 164, in check_unused
    while self.rpc.getreceivedbyaddress(addr, 0) != 0:
  File "/home/specter/.env/lib/python3.7/site-packages/cryptoadvance/specter/rpc.py", line 311, in fn
    r = self.multi([(method, *args)], **kwargs)[0]
  File "/home/specter/.env/lib/python3.7/site-packages/cryptoadvance/specter/rpc.py", line 304, in multi
    "Server responded with error code %d: %s" % (r.status_code, r.text), r
cryptoadvance.specter.rpc.RpcError: Server responded with error code 500: Work queue depth exceeded
```

**Comment by ben-kaufman** [comment]
Hi, does that happen every time you try to do that? Which Specter version?

**Comment by zsoltmoravcsik** [comment]
Yes, I try to re-do 4 more times, and also removed and reinstall the
spectre on my node, but after a random time, the wallet just simply
disappear.

**Comment by zsoltmoravcsik** [comment]
Version: Specter Version: 0.10.4

**Comment by ben-kaufman** [comment]
Does it still happen with v1.0.0?

**Comment by ben-kaufman** [comment]
Closing, please reopen if still relevant with latest version
