### ISSUE TITLE
Server error while importing a PSBT from Electrum

### ISSUE THREAD

**Issue by sohomang** [cryptoadvance/specter-desktop#868]
Using the latest stable versions of Electrum, Specter-Desktop and bitcoind.
Importing a PBST generated on Electrum ends up with this error: 

`Server error! `
`Exception: 'dict object' has no attribute 'witness_utxo'`

```
Traceback (most recent call last):
  File "flask/app.py", line 1950, in full_dispatch_request
  File "flask/app.py", line 1936, in dispatch_request
  File "flask_login/utils.py", line 269, in decorated_view
  File "cryptoadvance/specter/server_endpoints/wallets.py", line 639, in send_new
  File "flask/templating.py", line 140, in render_template
  File "flask/templating.py", line 120, in _render
  File "jinja2/environment.py", line 1090, in render
  File "jinja2/environment.py", line 832, in handle_exception
  File "jinja2/_compat.py", line 28, in reraise
  File "/var/folders/lh/45rl475j0r95mdzshckmts0m0000gn/T/_MEIoi5cOO/templates/wallet/send/sign/wallet_send_sign_psbt.jinja", line 2, in top-level template code
    {% set tab = 'send' %}
  File "/var/folders/lh/45rl475j0r95mdzshckmts0m0000gn/T/_MEIoi5cOO/templates/wallet/components/wallet_tab.jinja", line 1, in top-level template code
    {% extends "base.jinja" %}
  File "/var/folders/lh/45rl475j0r95mdzshckmts0m0000gn/T/_MEIoi5cOO/templates/base.jinja", line 60, in top-level template code
    {% block main %}
  File "/var/folders/lh/45rl475j0r95mdzshckmts0m0000gn/T/_MEIoi5cOO/templates/wallet/components/wallet_tab.jinja", line 12, in block "main"
    {% block content %}
  File "/var/folders/lh/45rl475j0r95mdzshckmts0m0000gn/T/_MEIoi5cOO/templates/wallet/send/sign/wallet_send_sign_psbt.jinja", line 137, in block "content"
    Amount: {{ psbt['inputs'][loop.index0]['witness_utxo']['amount'] }} BTC {% if specter.price_check %} ({{ psbt['inputs'][loop.index0]['witness_utxo']['amount'] | altunit }}){% endif %}
  File "jinja2/environment.py", line 452, in getitem
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'witness_utxo'

```

**Comment by ben-kaufman** [comment]
Closing, please reopen if still relevant with latest version
