### ISSUE TITLE
Adding coldcard device parses the fingerprint incorrectly

### ISSUE THREAD

**Issue by paddyquinn** [cryptoadvance/specter-desktop#90]
I am trying to set up a single key native segwit wallet using an airgapped coldcard. I was able to add the coldcard device without issue but when I go to create the wallet using the key from the coldcard device I run into the error in the title. The error corresponds to [this](https://github.com/bitcoin/bitcoin/blob/58ba7c314d552cea8cb024960a8504577aee586f/src/rpc/protocol.h#L41) bitcoin core rpc error. I am running v0.19.1 of bitcoin core. I have pasted the relevant logs below.

### specter logs:
```
trying 1 different configs
Detected 1 bitcoin daemons
INFO:werkzeug:127.0.0.1 - - [17/Mar/2020 17:22:00] "GET /new_wallet/ HTTP/1.1" 200 -
trying 1 different configs
Detected 1 bitcoin daemons
INFO:werkzeug:127.0.0.1 - - [17/Mar/2020 17:22:02] "GET /new_wallet/simple/ HTTP/1.1" 200 -
trying 1 different configs
Detected 1 bitcoin daemons
INFO:werkzeug:127.0.0.1 - - [17/Mar/2020 17:22:06] "POST /new_wallet/simple/ HTTP/1.1" 200 -
trying 1 different configs
Detected 1 bitcoin daemons
INFO:werkzeug:127.0.0.1 - - [17/Mar/2020 17:22:08] "POST /new_wallet/simple/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/paddy/.local/lib/python3.6/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/paddy/.local/lib/python3.6/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/home/paddy/.local/lib/python3.6/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/paddy/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/paddy/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/paddy/.local/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/paddy/.local/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/paddy/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/paddy/.local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/paddy/.local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/paddy/.local/lib/python3.6/site-packages/flask_login/utils.py", line 269, in decorated_view
    return func(*args, **kwargs)
  File "/home/paddy/.local/lib/python3.6/site-packages/cryptoadvance/specter/controller.py", line 225, in new_wallet_simple
    wallet = app.specter.wallets.create_simple(wallet_name, wallet_type, key, device)
  File "/home/paddy/.local/lib/python3.6/site-packages/cryptoadvance/specter/logic.py", line 433, in create_simple
    w = Wallet(o, self)
  File "/home/paddy/.local/lib/python3.6/site-packages/cryptoadvance/specter/logic.py", line 513, in __init__
    self._dict["address"] = self.get_address(0)
  File "/home/paddy/.local/lib/python3.6/site-packages/cryptoadvance/specter/logic.py", line 611, in get_address
    return self.cli.deriveaddresses(self._dict[desc], [index, index+1])[0]
  File "/home/paddy/.local/lib/python3.6/site-packages/cryptoadvance/specter/rpc.py", line 208, in fn
    raise RpcError("Server responded with error code %d: %s" % (r.status_code, r.text), r)
cryptoadvance.specter.rpc.RpcError: Server responded with error code 500: {"result":null,"error":{"code":-5,"message":"Fingerprint is not 4 bytes (11 characters instead of 8 characters)"},"id":0}
INFO:werkzeug:127.0.0.1 - - [17/Mar/2020 17:22:08] "GET /new_wallet/simple/?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [17/Mar/2020 17:22:08] "GET /new_wallet/simple/?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [17/Mar/2020 17:22:08] "GET /new_wallet/simple/?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [17/Mar/2020 17:22:08] "GET /new_wallet/simple/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [17/Mar/2020 17:22:08] "GET /new_wallet/simple/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
```

### bitcoin core `debug.log`:
```
2020-03-18T00:22:08Z Using BerkeleyDB version Berkeley DB 4.8.30: (April  9, 2010)
2020-03-18T00:22:08Z Using wallet /home/paddy/.bitcoin/specter977a002719b56150/test
2020-03-18T00:22:08Z BerkeleyEnvironment::Open: LogDir=/home/paddy/.bitcoin/specter977a002719b56150/test/database ErrorFile=/home/paddy/.bitcoin/specter977a002719b56150/test/db.log
2020-03-18T00:22:08Z init message: Loading wallet...
2020-03-18T00:22:08Z BerkeleyEnvironment::Open: LogDir=/home/paddy/.bitcoin/specter977a002719b56150/test/database ErrorFile=/home/paddy/.bitcoin/specter977a002719b56150/test/db.log
2020-03-18T00:22:08Z [specter977a002719b56150/test] Wallet File Version = 10500
2020-03-18T00:22:08Z [specter977a002719b56150/test] Keys: 0 plaintext, 0 encrypted, 0 w/ metadata, 0 total. Unknown wallet records: 0
2020-03-18T00:22:08Z [specter977a002719b56150/test] Performing wallet upgrade to 169900
2020-03-18T00:22:08Z [specter977a002719b56150/test] Wallet completed loading in              27ms
2020-03-18T00:22:08Z [specter977a002719b56150/test] setKeyPool.size() = 0
2020-03-18T00:22:08Z [specter977a002719b56150/test] mapWallet.size() = 0
2020-03-18T00:22:08Z [specter977a002719b56150/test] mapAddressBook.size() = 0
```

**Comment by paddyquinn** [comment]
You can mostly ignore the original comment. The issue is as follows. Bitcoin Core expects a fingerprint of the format xxxxxxxx. Specter parses coldcard wallet files as xx-xx-xx-xx. This causes the `Fingerprint is not 4 bytes (11 characters instead of 8 characters)` error. An example testnet wallet file is pasted below with its parsed output and its expected output.

### wallet.json
```
{
  "keystore": {
    "ckcc_xpub": "tpubD6NzVbkrYhZ4YQdaEuMzpMngnNzaAV4SzKZvSLVqVw38bNm22Xockewg4oBp6AGfhksFn4fjYCvZb8YgbFW24q7p52RE4dyXh2vicSXE1i7",
    "xpub": "vpub5ZZjHd9xqqpCy1NznFZjU9T2HyoHGnpENc3eYaLTsdU6SWab1YTXbpGoJWhZZXeujDWq1dm5dtVbKAVAVn6QezUQbRcGwF9fByhuAWsocau",
    "label": "Coldcard Import FA496EA4",
    "ckcc_xfp": 2758691322,
    "type": "hardware",
    "hw_type": "coldcard",
    "derivation": "m/84'/1'/0'"
  },
  "wallet_type": "standard",
  "use_encryption": false,
  "seed_version": 17
}
```

### parsed xpub
```
[fa-b7-92-5c/84'/1'/0']vpub5ZZjHd9xqqpCy1NznFZjU9T2HyoHGnpENc3eYaLTsdU6SWab1YTXbpGoJWhZZXeujDWq1dm5dtVbKAVAVn6QezUQbRcGwF9fByhuAWsocau
```

### expected xpub
```
[fab7925c/84'/1'/0']vpub5ZZjHd9xqqpCy1NznFZjU9T2HyoHGnpENc3eYaLTsdU6SWab1YTXbpGoJWhZZXeujDWq1dm5dtVbKAVAVn6QezUQbRcGwF9fByhuAWsocau

**Comment by stepansnigirev** [comment]
Should be fixed with https://github.com/cryptoadvance/specter-desktop/pull/93
I didn't know that `>>` operator in javascript can mess up the sign :)

Sidenote: in your case expected xpub should have a fingerprint of `fa496ea4`...

**Comment by paddyquinn** [comment]
Thanks for the quick fix on this @stepansnigirev. One thing I've noticed with the fix is the fingerprint is still backwards. Now what is being parsed is `a46e49fa` instead of `fa496ea4`. It doesn't seem to affect the functioning of the wallet though. What is the fingerprint actually used for?
