### ISSUE TITLE
CSRF token is missing (Specter Desktop v1.2.1)

### ISSUE THREAD

**Issue by gathulb** [cryptoadvance/specter-desktop#969]
I created a Send transaction to two different recipients (no change address), and tried to sign via USB-connected Trezor-T.

After the Trezor successfully confirms, Specter displays the following:

Server error!
Exception: 400 Bad Request: The CSRF token is missing.

Details:
Traceback (most recent call last):
  File "flask_wtf/csrf.py", line 256, in protect
  File "flask_wtf/csrf.py", line 91, in validate_csrf
wtforms.validators.ValidationError: The CSRF token is missing.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "flask/app.py", line 1948, in full_dispatch_request
  File "flask/app.py", line 2242, in preprocess_request
  File "flask_wtf/csrf.py", line 224, in csrf_protect
  File "flask_wtf/csrf.py", line 259, in protect
  File "flask_wtf/csrf.py", line 302, in _error_response
flask_wtf.csrf.CSRFError: 400 Bad Request: The CSRF token is missing.

**Comment by ben-kaufman** [comment]
Hi, yes we have got reports on the issue and it was fixed in #968 
We will release a new version today with that fix.

**Comment by ben-kaufman** [comment]
We have release v1.2.2 which fixes the issue. Closing this for now.
